In [ ]:
#step:1 Extracting data with API from sportsradar.com

import requests

url = "https://api.sportradar.com/tennis/trial/v3/en/competitions.json?api_key=rrUKuG1XtLDSIfQvyOAxO7Vl8tpqL7SGtiZ6aogP"

headers = {"accept": "application/json"}

response = requests.get(url, headers=headers)

print(response.text)

data=response.json()

{"generated_at":"2025-01-21T15:22:32+00:00","competitions":[{"id":"sr:competition:620","name":"Hopman Cup","type":"mixed","gender":"mixed","category":{"id":"sr:category:181","name":"Hopman Cup"}},{"id":"sr:competition:660","name":"World Team Cup","type":"mixed","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"atp_250"},{"id":"sr:competition:990","name":"ATP Challenger Tour Finals","parent_id":"sr:competition:6239","type":"singles","gender":"men","category":{"id":"sr:category:72","name":"Challenger"}},{"id":"sr:competition:1207","name":"Championship International Series","type":"singles","gender":"women","category":{"id":"sr:category:6","name":"WTA"},"level":"wta_championships"},{"id":"sr:competition:2100","name":"Davis Cup","type":"mixed","gender":"men","category":{"id":"sr:category:76","name":"Davis Cup"}},{"id":"sr:competition:2102","name":"Billie Jean King Cup","type":"mixed","gender":"women","category":{"id":"sr:category:74","name":"Federation Cup"}},{"id":"sr:competition:2555","name":"Wimbledon Men Singles","parent_id":"sr:competition:2553","type":"singles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"grand_slam"},{"id":"sr:competition:2557","name":"Wimbledon Men Doubles","parent_id":"sr:competition:2553","type":"doubles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"grand_slam"},{"id":"sr:competition:2559","name":"Wimbledon Women Singles","parent_id":"sr:competition:2553","type":"singles","gender":"women","category":{"id":"sr:category:6","name":"WTA"},"level":"grand_slam"},{"id":"sr:competition:2561","name":"Wimbledon Women Doubles","parent_id":"sr:competition:2553","type":"doubles","gender":"women","category":{"id":"sr:category:6","name":"WTA"},"level":"grand_slam"},{"id":"sr:competition:2563","name":"Wimbledon Mixed Doubles","parent_id":"sr:competition:2553","type":"mixed_doubles","gender":"mixed","category":{"id":"sr:category:3","name":"ATP"},"level":"grand_slam"},{"id":"sr:competition:2567","name":"Australian Open Men Singles","parent_id":"sr:competition:2565","type":"singles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"grand_slam"},{"id":"sr:competition:2569","name":"Australian Open Men Doubles","parent_id":"sr:competition:2565","type":"doubles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"grand_slam"},{"id":"sr:competition:2571","name":"Australian Open Women Singles","parent_id":"sr:competition:2565","type":"singles","gender":"women","category":{"id":"sr:category:6","name":"WTA"},"level":"grand_slam"},{"id":"sr:competition:2573","name":"Australian Open Women Doubles","parent_id":"sr:competition:2565","type":"doubles","gender":"women","category":{"id":"sr:category:6","name":"WTA"},"level":"grand_slam"},{"id":"sr:competition:2575","name":"Australian Open Mixed Doubles","parent_id":"sr:competition:2565","type":"mixed_doubles","gender":"mixed","category":{"id":"sr:category:3","name":"ATP"},"level":"grand_slam"},{"id":"sr:competition:2579","name":"French Open Men Singles","parent_id":"sr:competition:2577","type":"singles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"grand_slam"},{"id":"sr:competition:2581","name":"French Open Men Doubles","parent_id":"sr:competition:2577","type":"doubles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"grand_slam"},{"id":"sr:competition:2583","name":"French Open Women Singles","parent_id":"sr:competition:2577","type":"singles","gender":"women","category":{"id":"sr:category:6","name":"WTA"},"level":"grand_slam"},{"id":"sr:competition:2585","name":"French Open Women Doubles","parent_id":"sr:competition:2577","type":"doubles","gender":"women","category":{"id":"sr:category:6","name":"WTA"},"level":"grand_slam"},{"id":"sr:competition:2587","name":"French Open Mixed Doubles","parent_id":"sr:competition:2577","type":"mixed_doubles","gender":"mixed","category":{"id":"sr:category:3","name":"ATP"},"level":"grand_slam"},{"id":"sr:competition:2591","name":"US Open Men Singles","parent_id":"sr:competition:2589","type":"singles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"grand_slam"},{"id":"sr:competition:2593","name":"US Open Men Doubles","parent_id":"sr:competition:2589","type":"doubles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"grand_slam"},{"id":"sr:competition:2595","name":"US Open Women Singles","parent_id":"sr:competition:2589","type":"singles","gender":"women","category":{"id":"sr:category:6","name":"WTA"},"level":"grand_slam"},{"id":"sr:competition:2597","name":"US Open Women Doubles","parent_id":"sr:competition:2589","type":"doubles","gender":"women","category":{"id":"sr:category:6","name":"WTA"},"level":"grand_slam"},{"id":"sr:competition:2599","name":"US Open Mixed Doubles","parent_id":"sr:competition:2589","type":"mixed_doubles","gender":"mixed","category":{"id":"sr:category:3","name":"ATP"},"level":"grand_slam"},{"id":"sr:competition:2603","name":"ATP Doha, Qatar Men Singles","parent_id":"sr:competition:2601","type":"singles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"atp_500"},{"id":"sr:competition:2605","name":"ATP Doha, Qatar Men Doubles","parent_id":"sr:competition:2601","type":"doubles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"atp_500"},{"id":"sr:competition:2613","name":"ATP Basel, Switzerland Men Singles","parent_id":"sr:competition:2611","type":"singles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"atp_500"},{"id":"sr:competition:2615","name":"ATP Basel, Switzerland Men Doubles","parent_id":"sr:competition:2611","type":"doubles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"atp_500"},{"id":"sr:competition:2619","name":"ATP Brisbane, Australia Men Singles","parent_id":"sr:competition:2617","type":"singles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"atp_250"},{"id":"sr:competition:2621","name":"ATP Brisbane, Australia Men Doubles","parent_id":"sr:competition:2617","type":"doubles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"atp_250"},{"id":"sr:competition:2625","name":"ATP Chennai, India Men Singles","parent_id":"sr:competition:2623","type":"singles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"atp_250"},{"id":"sr:competition:2627","name":"ATP Chennai, India Men Doubles","parent_id":"sr:competition:2623","type":"doubles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"atp_250"},{"id":"sr:competition:2631","name":"ATP Auckland, New Zealand Men Singles","parent_id":"sr:competition:2629","type":"singles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"atp_250"},{"id":"sr:competition:2633","name":"ATP Auckland, New Zealand Men Doubles","parent_id":"sr:competition:2629","type":"doubles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"atp_250"},{"id":"sr:competition:2637","name":"ATP Sydney, Australia Men Singles","parent_id":"sr:competition:2635","type":"singles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"atp_250"},{"id":"sr:competition:2639","name":"ATP Sydney, Australia Men Doubles","parent_id":"sr:competition:2635","type":"doubles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"atp_250"},{"id":"sr:competition:2649","name":"ATP Zagreb, Croatia Men Singles","parent_id":"sr:competition:2647","type":"singles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"atp_250"},{"id":"sr:competition:2651","name":"ATP Zagreb, Croatia Men Double","parent_id":"sr:competition:2647","type":"doubles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"atp_250"},{"id":"sr:competition:2661","name":"ATP Paris, France Men Singles","parent_id":"sr:competition:2659","type":"singles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"atp_1000"},{"id":"sr:competition:2663","name":"ATP Paris, France Men Doubles","parent_id":"sr:competition:2659","type":"doubles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"atp_1000"},{"id":"sr:competition:2667","name":"ATP Dubai, UAE Men Singles","parent_id":"sr:competition:2665","type":"singles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"atp_500"},{"id":"sr:competition:2669","name":"ATP Dubai, UAE Men Doubles","parent_id":"sr:competition:2665","type":"doubles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"atp_500"},{"id":"sr:competition:2673","name":"WTA Pattaya City, Thailand Women Singles","parent_id":"sr:competition:2671","type":"singles","gender":"women","category":{"id":"sr:category:6","name":"WTA"},"level":"wta_international"},{"id":"sr:competition:2675","name":"WTA Pattaya City, Thailand Women Doubles","parent_id":"sr:competition:2671","type":"doubles","gender":"women","category":{"id":"sr:category:6","name":"WTA"},"level":"wta_international"},{"id":"sr:competition:2679","name":"ATP Rotterdam, Netherlands Men Singles","parent_id":"sr:competition:2677","type":"singles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"atp_500"},{"id":"sr:competition:2681","name":"ATP Rotterdam, Netherlands Men Doubles","parent_id":"sr:competition:2677","type":"doubles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"atp_500"},{"id":"sr:competition:2697","name":"ATP Memphis, USA Men Singles","parent_id":"sr:competition:2695","type":"singles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"atp_250"},{"id":"sr:competition:2699","name":"ATP Memphis, USA Men Doubles","parent_id":"sr:competition:2695","type":"doubles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"atp_250"},{"id":"sr:competition:2703","name":"WTA Bogota, Colombia Women Singles","parent_id":"sr:competition:2701","type":"singles","gender":"women","category":{"id":"sr:category:6","name":"WTA"},"level":"wta_250"},{"id":"sr:competition:2705","name":"WTA Bogota, Colombia Women Doubles","parent_id":"sr:competition:2701","type":"doubles","gender":"women","category":{"id":"sr:category:6","name":"WTA"},"level":"wta_250"},{"id":"sr:competition:2709","name":"ATP Acapulco, Mexico Men Singles","parent_id":"sr:competition:2707","type":"singles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"atp_500"},{"id":"sr:competition:2711","name":"ATP Acapulco, Mexico Men Doubles","parent_id":"sr:competition:2707","type":"doubles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"atp_500"},{"id":"sr:competition:2715","name":"WTA Monterrey, Mexico Women Singles","parent_id":"sr:competition:2713","type":"singles","gender":"women","category":{"id":"sr:category:6","name":"WTA"},"level":"wta_500"},{"id":"sr:competition:2717","name":"WTA Monterrey, Mexico Women Doubles","parent_id":"sr:competition:2713","type":"doubles","gender":"women","category":{"id":"sr:category:6","name":"WTA"},"level":"wta_500"},{"id":"sr:competition:2721","name":"ATP Marseille, France Men Singles","parent_id":"sr:competition:2719","type":"singles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"atp_250"},{"id":"sr:competition:2723","name":"ATP Marseille, France Men Doubles","parent_id":"sr:competition:2719","type":"doubles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"atp_250"},{"id":"sr:competition:2727","name":"ATP Buenos Aires, Argentina Men Singles","parent_id":"sr:competition:2725","type":"singles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"atp_250"},{"id":"sr:competition:2729","name":"ATP Buenos Aires, Argentina Men Doubles","parent_id":"sr:competition:2725","type":"doubles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"atp_250"},{"id":"sr:competition:2733","name":"ATP Delray Beach, USA Men Singles","parent_id":"sr:competition:2731","type":"singles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"atp_250"},{"id":"sr:competition:2735","name":"ATP Delray Beach, USA Men Doubles","parent_id":"sr:competition:2731","type":"doubles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"atp_250"},{"id":"sr:competition:2739","name":"ATP Indian Wells, USA Men Singles","parent_id":"sr:competition:2737","type":"singles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"atp_1000"},{"id":"sr:competition:2741","name":"ATP Indian Wells, USA Men Doubles","parent_id":"sr:competition:2737","type":"doubles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"atp_1000"},{"id":"sr:competition:2745","name":"ATP Miami, USA Men Singles","parent_id":"sr:competition:2743","type":"singles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"atp_1000"},{"id":"sr:competition:2747","name":"ATP Miami, USA Men Doubles","parent_id":"sr:competition:2743","type":"doubles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"atp_1000"},{"id":"sr:competition:2751","name":"ATP Houston, USA Men Singles","parent_id":"sr:competition:2749","type":"singles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"atp_250"},{"id":"sr:competition:2753","name":"ATP Houston, USA Men Doubles","parent_id":"sr:competition:2749","type":"doubles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"atp_250"},{"id":"sr:competition:2757","name":"ATP Casablanca, Morocco Men Singles","parent_id":"sr:competition:2755","type":"singles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"atp_250"},{"id":"sr:competition:2759","name":"ATP Casablanca, Morocco Men Doubles","parent_id":"sr:competition:2755","type":"doubles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"atp_250"},{"id":"sr:competition:2763","name":"WTA Charleston, USA Women Singles","parent_id":"sr:competition:2761","type":"singles","gender":"women","category":{"id":"sr:category:6","name":"WTA"},"level":"wta_500"},{"id":"sr:competition:2765","name":"WTA Charleston, USA Women Doubles","parent_id":"sr:competition:2761","type":"doubles","gender":"women","category":{"id":"sr:category:6","name":"WTA"},"level":"wta_500"},{"id":"sr:competition:2769","name":"ATP Barcelona, Spain Men Singles","parent_id":"sr:competition:2767","type":"singles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"atp_500"},{"id":"sr:competition:2771","name":"ATP Barcelona, Spain Men Doubles","parent_id":"sr:competition:2767","type":"doubles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"atp_500"},{"id":"sr:competition:2775","name":"ATP Stuttgart, Germany Men Singles","parent_id":"sr:competition:2773","type":"singles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"atp_250"},{"id":"sr:competition:2777","name":"ATP Stuttgart, Germany Men Doubles","parent_id":"sr:competition:2773","type":"doubles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"atp_250"},{"id":"sr:competition:2781","name":"ATP Rome, Italy Men Singles","parent_id":"sr:competition:2779","type":"singles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"atp_1000"},{"id":"sr:competition:2783","name":"ATP Rome, Italy Men Doubles","parent_id":"sr:competition:2779","type":"doubles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"atp_1000"},{"id":"sr:competition:2787","name":"ATP Madrid, Spain Men Singles","parent_id":"sr:competition:2785","type":"singles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"atp_1000"},{"id":"sr:competition:2789","name":"ATP Madrid, Spain Men Doubles","parent_id":"sr:competition:2785","type":"doubles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"atp_1000"},{"id":"sr:competition:2793","name":"Berlin, Germany Women Singles","parent_id":"sr:competition:2791","type":"singles","gender":"women","category":{"id":"sr:category:6","name":"WTA"},"level":"wta_500"},{"id":"sr:competition:2795","name":"Berlin, Germany Women Doubles","parent_id":"sr:competition:2791","type":"doubles","gender":"women","category":{"id":"sr:category:6","name":"WTA"},"level":"wta_500"},{"id":"sr:competition:2805","name":"WTA Hobart, Australia Women Singles","parent_id":"sr:competition:2803","type":"singles","gender":"women","category":{"id":"sr:category:6","name":"WTA"},"level":"wta_250"},{"id":"sr:competition:2807","name":"WTA Hobart, Australia Women Doubles","parent_id":"sr:competition:2803","type":"doubles","gender":"women","category":{"id":"sr:category:6","name":"WTA"},"level":"wta_250"},{"id":"sr:competition:2817","name":"WTA Marrakech, Morocco Women Singles","parent_id":"sr:competition:2815","type":"singles","gender":"women","category":{"id":"sr:category:6","name":"WTA"},"level":"wta_international"},{"id":"sr:competition:2819","name":"WTA Marrakech, Morocco Women Doubles","parent_id":"sr:competition:2815","type":"doubles","gender":"women","category":{"id":"sr:category:6","name":"WTA"},"level":"wta_international"},{"id":"sr:competition:2823","name":"WTA Strasbourg, France Women Singles","parent_id":"sr:competition:2821","type":"singles","gender":"women","category":{"id":"sr:category:6","name":"WTA"},"level":"wta_500"},{"id":"sr:competition:2825","name":"WTA Strasbourg, France Women Doubles","parent_id":"sr:competition:2821","type":"doubles","gender":"women","category":{"id":"sr:category:6","name":"WTA"},"level":"wta_500"},{"id":"sr:competition:2829","name":"ATP Challenger Amersfoort, Netherlands Men Singles","parent_id":"sr:competition:2827","type":"singles","gender":"men","category":{"id":"sr:category:72","name":"Challenger"}},{"id":"sr:competition:2831","name":"ATP Challenger Amersfoort, Netherlands Men Doubles","parent_id":"sr:competition:2827","type":"doubles","gender":"men","category":{"id":"sr:category:72","name":"Challenger"}},{"id":"sr:competition:2835","name":"ATP Munich, Germany Men Singles","parent_id":"sr:competition:2833","type":"singles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"atp_250"},{"id":"sr:competition:2837","name":"ATP Munich, Germany Men Doubles","parent_id":"sr:competition:2833","type":"doubles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"atp_250"},{"id":"sr:competition:2853","name":"WTA Birmingham, Great Britain Women Singles","parent_id":"sr:competition:2851","type":"singles","gender":"women","category":{"id":"sr:category:6","name":"WTA"},"level":"wta_250"},{"id":"sr:competition:2855","name":"WTA Birmingham, Great Britain Women Doubles","parent_id":"sr:competition:2851","type":"doubles","gender":"women","category":{"id":"sr:category:6","name":"WTA"},"level":"wta_250"},{"id":"sr:competition:2859","name":"ATP Halle, Germany Men Singles","parent_id":"sr:competition:2857","type":"singles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"atp_500"},{"id":"sr:competition:2861","name":"ATP Halle, Germany Men Doubles","parent_id":"sr:competition:2857","type":"doubles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"atp_500"},{"id":"sr:competition:2865","name":"ATP London, Great Britain Men Singles","parent_id":"sr:competition:2863","type":"singles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"atp_500"},{"id":"sr:competition:2867","name":"ATP London, Great Britain Men Doubles","parent_id":"sr:competition:2863","type":"doubles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"atp_500"},{"id":"sr:competition:2871","name":"ATP S-Hertogenbosch, Netherlands Men Singles","parent_id":"sr:competition:2869","type":"singles","gender":"men","category":{"id":"sr:category:3","name":"ATP"},"level":"atp_250"},{"id":"sr:competition:2873","name":"ATP S-Hertogenbosch, Netherlands Men Doubles","parent_id":"sr:competition:28

In [ ]:
#Extracting competitions data
competitions_data=[]

In [ ]:
for competition in data["competitions"]:   
        
        
        competition_details = {
            "id": competition.get("id"),
            "name": competition.get("name"),
            "type": competition.get("type"),
            "gender": competition.get("gender"),
            "category_id": competition.get("category", {}).get("id"),
            "parent_id": competition.get("parent_id")
    
            
        
        }

        competitions_data.append(competition_details)

In [4]:
import pandas as pd

In [13]:
df1 = pd.DataFrame(competitions_data)

In [14]:
df1.count()

id             5848
name           5848
type           5848
gender         5848
category_id    5848
parent_id      5771
dtype: int64

In [15]:
df1.fillna("NOT",inplace=True)

In [16]:
df1.count()

id             5848
name           5848
type           5848
gender         5848
category_id    5848
parent_id      5848
dtype: int64

In [17]:
df1.shape

(5848, 6)

In [18]:
df1

,id,name,type,gender,category_id,parent_id
0,sr:competition:620,Hopman Cup,mixed,mixed,sr:category:181,NOT
1,sr:competition:660,World Team Cup,mixed,men,sr:category:3,NOT
2,sr:competition:990,ATP Challenger Tour Finals,singles,men,sr:category:72,sr:competition:6239
3,sr:competition:1207,Championship International Series,singles,women,sr:category:6,NOT
4,sr:competition:2100,Davis Cup,mixed,men,sr:category:76,NOT
...,...,...,...,...,...,...
5843,sr:competition:45753,UTR Gyor M01,singles,men,sr:category:2516,NOT
5844,sr:competition:45755,UTR Alvor M02,singles,men,sr:category:2516,NOT
5845,sr:competition:45757,UTR Newport Beach M03,singles,men,sr:category:2516,NOT
5846,sr:competition:45761,UTR Yokohama W01,singles,women,sr:category:2517,NOT
5847,sr:competition:45763,UTR Dubai W02,singles,women,sr:category:2517,NOT

In [20]:
df1.to_csv("competitions_table.csv",index=False)

In [11]:
import pandas as pd

In [ ]:
# Extracting the category data from competitions details
category_data=[]

In [ ]:
for category in data["competitions"]:
     category_details = {
          "category_id": category.get("category", {}).get("id"),
          "category_name": category.get("category", {}).get("name")
        
     }
     category_data.append(category_details)

In [16]:
df2=pd.DataFrame(category_data)

In [17]:
df2

           category_id category_name
0      sr:category:181    Hopman Cup
1        sr:category:3           ATP
2       sr:category:72    Challenger
3        sr:category:6           WTA
4       sr:category:76     Davis Cup
...                ...           ...
5843  sr:category:2516       UTR Men
5844  sr:category:2516       UTR Men
5845  sr:category:2516       UTR Men
5846  sr:category:2517     UTR Women
5847  sr:category:2517     UTR Women

[5848 rows x 2 columns]

In [18]:
df2.count()

category_id      5848
category_name    5848
dtype: int64

In [19]:
df2.nunique()

category_id      18
category_name    18
dtype: int64

In [20]:
# Removing duplicate category details
df2.drop_duplicates(inplace=True)

In [21]:
df2

           category_id        category_name
0      sr:category:181           Hopman Cup
1        sr:category:3                  ATP
2       sr:category:72           Challenger
3        sr:category:6                  WTA
4       sr:category:76            Davis Cup
5       sr:category:74       Federation Cup
356    sr:category:785              ITF Men
374    sr:category:213            ITF Women
677    sr:category:871             WTA 125K
918   sr:category:1012                 IPTL
919     sr:category:79           Exhibition
1337  sr:category:1474              Juniors
1341  sr:category:1476          Wheelchairs
1345  sr:category:1475              Legends
4842  sr:category:2400  Wheelchairs Juniors
5003  sr:category:2414           United Cup
5793  sr:category:2517            UTR Women
5795  sr:category:2516              UTR Men

In [22]:
df2.to_csv("category_table.csv",index=False)

In [1]:
# step 2: Extracting complexes data
import requests

url = "https://api.sportradar.com/tennis/trial/v3/en/complexes.json?api_key=rrUKuG1XtLDSIfQvyOAxO7Vl8tpqL7SGtiZ6aogP"

headers = {"accept": "application/json"}

response = requests.get(url, headers=headers)

print(response.text)

{"generated_at":"2025-01-21T15:23:17+00:00","complexes":[{"id":"sr:complex:705","name":"Nacional","venues":[{"id":"sr:venue:70045","name":"Cancha Central","city_name":"Santiago","country_name":"Chile","country_code":"CHL","timezone":"America\/Santiago"}]},{"id":"sr:complex:1078","name":"Estadio de la Cartuja","venues":[{"id":"sr:venue:74856","name":"Centre Court","city_name":"Seville","country_name":"Spain","country_code":"ESP","timezone":"Europe\/Madrid"},{"id":"sr:venue:74858","name":"Court One","city_name":"Seville","country_name":"Spain","country_code":"ESP","timezone":"Europe\/Madrid"}]},{"id":"sr:complex:1495","name":"Sibur Arena","venues":[{"id":"sr:venue:1496","name":"COURT 1","city_name":"Saint Petersburg","country_name":"Russia","country_code":"RUS","timezone":"Europe\/Moscow"},{"id":"sr:venue:1500","name":"CENTER COURT","city_name":"Saint Petersburg","country_name":"Russia","country_code":"RUS","timezone":"Europe\/Moscow"},{"id":"sr:venue:62149","name":"Sibur Arena","city_name":"Saint Petersburg","country_name":"Russia","country_code":"RUS","timezone":"Europe\/Moscow"},{"id":"sr:venue:62153","name":"TC Dynamo","city_name":"Saint Petersburg","country_name":"Russia","country_code":"RUS","timezone":"Europe\/Moscow"}]},{"id":"sr:complex:2375","name":"Complexo de Tenis do Jamor","venues":[{"id":"sr:venue:57912","name":"Central","city_name":"Oeiras","country_name":"Portugal","country_code":"PRT","timezone":"Europe\/Lisbon"},{"id":"sr:venue:70805","name":"Campo 3","city_name":"Oeiras","country_name":"Portugal","country_code":"PRT","timezone":"Europe\/Lisbon"},{"id":"sr:venue:70807","name":"Campo 4","city_name":"Oeiras","country_name":"Portugal","country_code":"PRT","timezone":"Europe\/Lisbon"},{"id":"sr:venue:77423","name":"Campo 1","city_name":"Oeiras","country_name":"Portugal","country_code":"PRT","timezone":"Europe\/Lisbon"},{"id":"sr:venue:77437","name":"Campo 8","city_name":"Oeiras","country_name":"Portugal","country_code":"PRT","timezone":"Europe\/Lisbon"}]},{"id":"sr:complex:4032","name":"Shree Shiv Chhatrapati Sports Complex"},{"id":"sr:complex:5520","name":"O2 Arena"},{"id":"sr:complex:5526","name":"Ostravar Arena","venues":[{"id":"sr:venue:13912","name":"Centre Court","city_name":"Ostrava","country_name":"Czechia","country_code":"CZE","timezone":"Europe\/Prague"},{"id":"sr:venue:13914","name":"Court 3","city_name":"Ostrava","country_name":"Czechia","country_code":"CZE","timezone":"Europe\/Prague"},{"id":"sr:venue:13916","name":"Court 6","city_name":"Ostrava","country_name":"Czechia","country_code":"CZE","timezone":"Europe\/Prague"},{"id":"sr:venue:13942","name":"Court 4","city_name":"Ostrava","country_name":"Czechia","country_code":"CZE","timezone":"Europe\/Prague"},{"id":"sr:venue:55221","name":"Court 1","capacity":1,"city_name":"Ostrava","country_name":"Czechia","country_code":"CZE","timezone":"Europe\/Prague"},{"id":"sr:venue:55223","name":"Court 2","capacity":1,"city_name":"Ostrava","country_name":"Czechia","country_code":"CZE","timezone":"Europe\/Prague"}]},{"id":"sr:complex:6310","name":"Varazdin Arena","venues":[{"id":"sr:venue:77271","name":"Table 1","city_name":"Varazdin","country_name":"Croatia","country_code":"HRV","timezone":"Europe\/Zagreb"},{"id":"sr:venue:77273","name":"Table 2","city_name":"Varazdin","country_name":"Croatia","country_code":"HRV","timezone":"Europe\/Zagreb"},{"id":"sr:venue:77275","name":"Table 3","city_name":"Varazdin","country_name":"Croatia","country_code":"HRV","timezone":"Europe\/Zagreb"},{"id":"sr:venue:77277","name":"Table 4","city_name":"Varazdin","country_name":"Croatia","country_code":"HRV","timezone":"Europe\/Zagreb"},{"id":"sr:venue:77279","name":"Table 5","city_name":"Varazdin","country_name":"Croatia","country_code":"HRV","timezone":"Europe\/Zagreb"},{"id":"sr:venue:77281","name":"Table 6","city_name":"Varazdin","country_name":"Croatia","country_code":"HRV","timezone":"Europe\/Zagreb"},{"id":"sr:venue:77283","name":"Table 7","city_name":"Varazdin","country_name":"Croatia","country_code":"HRV","timezone":"Europe\/Zagreb"},{"id":"sr:venue:77285","name":"Table 8","city_name":"Varazdin","country_name":"Croatia","country_code":"HRV","timezone":"Europe\/Zagreb"}]},{"id":"sr:complex:6484","name":"Arena Montpellier","venues":[{"id":"sr:venue:2146","name":"Court 1","city_name":"Montpellier","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:19477","name":"Court Patrice Dominguez","city_name":"Montpellier","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:30567","name":"Court Central","city_name":"Montpellier","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:30569","name":"Court 2","city_name":"Montpellier","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:39934","name":"Court 3","city_name":"Montpellier","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"}]},{"id":"sr:complex:6736","name":"Arenes de Metz"},{"id":"sr:complex:6888","name":"Palais des sports de Pau"},{"id":"sr:complex:6890","name":"Palais des Sports Orleans","venues":[{"id":"sr:venue:66107","name":"Court 2","city_name":"Orchies","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:66109","name":"Court 3","city_name":"Orleans","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:66111","name":"Court 4","city_name":"Orleans","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:70605","name":"Court 5","city_name":"Orleans","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:74195","name":"Center Court","city_name":"Orleans","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:74197","name":"Court 1","city_name":"Orleans","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"}]},{"id":"sr:complex:6904","name":"Stade Pierre-de-Coubertin"},{"id":"sr:complex:7048","name":"Palacio de Deportes Jose Maria Martin Carpena","venues":[{"id":"sr:venue:72565","name":"Pista Cental","city_name":"Malaga","country_name":"Spain","country_code":"ESP","timezone":"Europe\/Madrid"},{"id":"sr:venue:72567","name":"Pista 2","city_name":"Malaga","country_name":"Spain","country_code":"ESP","timezone":"Europe\/Madrid"},{"id":"sr:venue:72569","name":"Pista 3","city_name":"Malaga","country_name":"Spain","country_code":"ESP","timezone":"Europe\/Madrid"},{"id":"sr:venue:72571","name":"Pista 4","city_name":"Malaga","country_name":"Spain","country_code":"ESP","timezone":"Europe\/Madrid"}]},{"id":"sr:complex:7052","name":"Pabellon Municipal Fuente San Luis"},{"id":"sr:complex:7208","name":"Unipol Arena"},{"id":"sr:complex:7778","name":"Arena Gripe"},{"id":"sr:complex:9725","name":"Arena Armeets Sofia","venues":[{"id":"sr:venue:17756","name":"Center Court","city_name":"Sofia","country_name":"Bulgaria","country_code":"BGR","timezone":"Europe\/Sofia"},{"id":"sr:venue:17758","name":"Court 1","city_name":"Sofia","country_name":"Bulgaria","country_code":"BGR","timezone":"Europe\/Sofia"},{"id":"sr:venue:23352","name":"Court 3","city_name":"Sofia","country_name":"Bulgaria","country_code":"BGR","timezone":"Europe\/Sofia"},{"id":"sr:venue:23354","name":"Court 4","city_name":"Sofia","country_name":"Bulgaria","country_code":"BGR","timezone":"Europe\/Sofia"},{"id":"sr:venue:23356","name":"Court 2","city_name":"Sofia","country_name":"Bulgaria","country_code":"BGR","timezone":"Europe\/Sofia"}]},{"id":"sr:complex:10063","name":"Kindarena","venues":[{"id":"sr:venue:66889","name":"Center Court","city_name":"Rouen","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:66925","name":"Amelie Mauresmo","city_name":"Rouen","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:66979","name":"Celine Dumerc","city_name":"Rouen","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:74546","name":"Court 1","city_name":"Rouen","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"}]},{"id":"sr:complex:11769","name":"Estadio German Becker","venues":[{"id":"sr:venue:67857","name":"Cancha Central","city_name":"Temuco","country_name":"Chile","country_code":"CHL","timezone":"America\/Santiago"},{"id":"sr:venue:67859","name":"Cancha 1","city_name":"Temuco","country_name":"Chile","country_code":"CHL","timezone":"America\/Santiago"},{"id":"sr:venue:67861","name":"Cancha 2","city_name":"Temuco","country_name":"Chile","country_code":"CHL","timezone":"America\/Santiago"},{"id":"sr:venue:67863","name":"Cancha 3","city_name":"Temuco","country_name":"Chile","country_code":"CHL","timezone":"America\/Santiago"}]},{"id":"sr:complex:12241","name":"Palais des sports de Gerland","venues":[{"id":"sr:venue:30465","name":"Indoor 1","city_name":"Lyon","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:30467","name":"Indoor 2","city_name":"Lyon","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:30469","name":"Indoor 3","city_name":"Lyon","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:39773","name":"Court 23","capacity":1,"city_name":"Lyon","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:39842","name":"Court 14","city_name":"Lyon","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:39844","name":"Court 15","city_name":"Lyon","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:58692","name":"Court 12","capacity":1,"city_name":"Lyon","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"}]},{"id":"sr:complex:15014","name":"Palais Des Sport","venues":[{"id":"sr:venue:15010","name":"La Foret 3","city_name":"Orleans","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:16880","name":"Central Court","city_name":"Orleans","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:23652","name":"La Foret 2","city_name":"Orleans","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:66105","name":"Court 1","city_name":"Orleans","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:66137","name":"La Foret 4","capacity":1,"city_name":"Orleans","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:66139","name":"La Foret 1","capacity":1,"city_name":"Orleans","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:70603","name":"Court 2","city_name":"Orleans","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"}]},{"id":"sr:complex:15371","name":"Palasport","venues":[{"id":"sr:venue:67869","name":"Court 2","city_name":"Andria","country_name":"Italy","country_code":"ITA","timezone":"Europe\/Rome"},{"id":"sr:venue:67871","name":"Court 3","city_name":"Andria","country_name":"Italy","country_code":"ITA","timezone":"Europe\/Rome"},{"id":"sr:venue:68095","name":"Campo Tato Paride","city_name":"Andria","country_name":"Italy","country_code":"ITA","timezone":"Europe\/Rome"},{"id":"sr:venue:68097","name":"Campo Arpex","city_name":"Andria","country_name":"Italy","country_code":"ITA","timezone":"Europe\/Rome"}]},{"id":"sr:complex:16020","name":"Salle Steredenn","venues":[{"id":"sr:venue:16022","name":"Atg 3","city_name":"Saint-Brieuc","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:18015","name":"Atg 4","city_name":"Saint-Brieuc","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:28371","name":"Tcsb 4","city_name":"Saint-Brieuc","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:28373","name":"Tcsb 3","city_name":"Saint-Brieuc","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:62697","name":"Court Steredenn","city_name":"Saint-Brieuc","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:80523","name":"Court TCSB","city_name":"Saint-Brieuc","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"}]},{"id":"sr:complex:16069","name":"Garanti Koza Arena","venues":[{"id":"sr:venue:14874","name":"Court Limak Enerji","city_name":"Istanbul","country_name":"Turkiye","country_code":"TUR","timezone":"Europe\/Istanbul"}]},{"id":"sr:complex:16612","name":"Porsche-Arena","venues":[{"id":"sr:venue:1765","name":"Centre Court","city_name":"Stuttgart","country_name":"Germany","country_code":"DEU","timezone":"Europe\/Berlin"},{"id":"sr:venue:77411","name":"Court 1","city_name":"Stuttgart","country_name":"Germany","country_code":"DEU","timezone":"Europe\/Berlin"},{"id":"sr:venue:77413","name":"Court 2","city_name":"Stuttgart","country_name":"Germany","country_code":"DEU","timezone":"Europe\/Berlin"}]},{"id":"sr:complex:17254","name":"Poliesportiu d'Andorra"},{"id":"sr:complex:17945","name":"Rotterdam Ahoy","venues":[{"id":"sr:venue:1648","name":"Court 1","city_name":"Rotterdam","country_name":"Netherlands","country_code":"NLD","timezone":"Europe\/Brussels"},{"id":"sr:venue:3696","name":"Court 2","city_name":"Rotterdam","country_name":"Netherlands","country_code":"NLD","timezone":"Europe\/Brussels"},{"id":"sr:venue:22854","name":"Centre Court","city_name":"Rotterdam","country_name":"Netherlands","country_code":"NLD","timezone":"Europe\/Brussels"}]},{"id":"sr:complex:18201","name":"The O2","venues":[{"id":"sr:venue:66121","name":"Centre Court","city_name":"London","country_name":"England","country_code":"ENG","timezone":"Europe\/London"}]},{"id":"sr:complex:18221","name":"Bluesun Tennis Center","venues":[{"id":"sr:venue:18223","name":"Cedevita Court","city_name":"Bol","country_name":"Croatia","country_code":"HRV","timezone":"Europe\/Zagreb"},{"id":"sr:venue:18225","name":"Cockta Court","city_name":"Bol","country_name":"Croatia","country_code":"HRV","timezone":"Europe\/Zagreb"},{"id":"sr:venue:18227","name":"Kala Court","city_name":"Bol","country_name":"Croatia","country_code":"HRV","timezone":"Europe\/Zagreb"},{"id":"sr:venue:21412","name":"INA Court","city_name":"Bol","country_name":"Croatia","country_code":"HRV","timezone":"Europe\/Zagreb"},{"id":"sr:venue:21422","name":"Raiffeisen Court","city_name":"Bol","country_name":"Croatia","country_code":"HRV","timezone":"Europe\/Zagreb"},{"id":"sr:venue:30195","name":"Lukas Court","city_name":"Bol","country_name":"Croatia","country_code":"HRV","timezone":"Europe\/Zagreb"},{"id":"sr:venue:39715","name":"Center Court","city_name":"Bol","country_name":"Croatia","country_code":"HRV","timezone":"Europe\/Zagreb"},{"id":"sr:venue:39717","name":"Court 1","city_name":"Bol","country_name":"Croatia","country_code":"HRV","timezone":"Europe\/Zagreb"}]},{"id":"sr:complex:19166","name":"Shlomo Group Arena"},{"id":"sr:complex:19737","name":"Club Sonoma, Estadio Gnp Seguros","venues":[{"id":"sr:venue:1695","name":"Center Court","city_name":"Monterrey","country_name":"Mexico","country_code":"MEX","timezone":"America\/Mexico_City"},{"id":"sr:venue:1696","name":"Court 1","city_name":"Monterrey","country_name":"Mexico","country_code":"MEX","timezone":"America\/Mexico_City"},{"id":"sr:venue:62341","name":"Court 4","city_name":"Monterrey","country_name":"Mexico","country_code":"MEX","timezone":"America\/Mexico_City"}]},{"id":"sr:complex:19951","name":"Accor Arena","venues":[{"id":"sr:venue:1520","name":"Court Central","city_name":"Paris","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:1521","name":"Court 1","city_name":"Paris","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"},{"id":"sr:venue:1522","name":"Court 2","city_name":"Paris","country_name":"France","country_code":"FRA","timezone":"Europe\/Paris"}]},{"id":"sr:complex:21870","name":"Stadium Goran Ivanisevic in ITC Stella Maris","venues":[{"id":"sr:venue:21868","name":"Next Gen Arena","city_name":"Umag","country_name":"Croatia","country_code":"HRV","timezone":"Europe\/Zagreb"}]},{"id":"sr:complex:21910","name":"Roy Emerson Arena","venues":[{"id":"sr:venue:1938","name":"Roy Emerson Arena","city_name":"Gstaad","country_name":"Switzerland","country_code":"CHE","timezone":"Europe\/Zurich"},{"id":"sr:venue:1939","name":"Court 1","city_name":"Gstaad","country_name":"Switzerland","country_code":"CHE","timezone":"Europe\/Zurich"},{"id":"sr:venue:1953","name":"Sportzentrum 1","city_name":"Gstaad","country_name":"Switzerland","country_code":"CHE","timezone":"Europe\/Zurich"},{"id":"sr:venue:2461","name":"Sportzentrum 3","city_name":"Gstaad","country_name":"Switzerland","country_code":"CHE","timezone":"Europe\/Zurich"}]},{"id":"sr:complex:26983","name":"Club de Tenis Puente Romano","venues":[{"id":"sr:venue:1728","name":"Centre Court","city_name":"Marbella","country_name":"Spain","country_code":"ESP","timezone":"Europe\/Madrid"},{"id":"sr:venue:1729","name":"Court 1","city_name":"Marbella","country_name":"Spain","country_code":"ESP","timezone":"Europe\/Madrid"},{"id":"sr:venue:1730","name":"Court 7","city_name":"Marbella","country_name":"Spain","country_code":"ESP","timezone":"Europe\/Madrid"},{"id":"sr:venue:28357","name":"Court 2","city_name":"Marbella","country_name":"Spain","country_code":"ESP","timezone":"Europe\/Madrid"},{"id":"sr:venue:33908","name":"Court 3","city_name":"Marbella","country_name":"Spain","country_code":"ESP","timezone":"Europe\/Madrid"},{"id":"sr:venue:33916","name":"Court 4","city_name":"Marbella","country_name":"Spain","country_code":"ESP","timezone":"Europe\/Madrid"},{"id":"sr:venue:57732","name":"Estadio Manolo Santana","city_name":"Marbella","country_name":"Spain","country_code":"ESP","timezone":"Europe\/Madrid"},{"id":"sr:venue:62729","name":"Court 8","city_name":"Marbella","country_name":"Spain","country_code":"ESP","timezone":"Europe\/Madrid"},{"id":"sr:venue:62731","name":"Court 9","city_name":"Marbella","country_name":"Spain","country_code":"ESP","timezone":"Europe\/Madrid"}]},{"id":"sr:complex:26985","name":"National Tennis Center","venues":[{"id":"sr:venue:1383","name":"Astana Arena","capacity":30000,"city_name":"Astana","country_name":"Kazakhstan","map_coordinates":"51.108244,71.402584","country_code":"KAZ","timezone":"Asia\/Almaty"},{"id":"sr:venue:2595","name":"Astana","city_name":"Astana","country_name":"Kazakhstan","country_code":"KAZ","timezone":"Asia\/Almaty"},{"id":"sr:venue:14620","name":"Center Court","city_name":"Astana","country_name":"Kazakhstan","country_code":"KAZ","timezone":"Asia\/Almaty"},{"id":"sr:venue:14622","name":"Court 1","city_name":"Astana","country_name":"Kazakhstan","country_code":"KAZ","timezone":"Asia\/Almaty"},{"id":"sr:venue:14624","name":"Court 2","city_name":"Astana","country_name":"Kazakhstan","country_code":"KAZ","timezone":"Asia\/Almaty"},{"id":"sr:venue:14626","name":"Court 3","city_name":"Astana","country_name":"Kazakhstan","country_code":"KAZ","timezone":"Asia\/Almaty"},{"id":"sr:venue:14628","name":"Court 6","city_name":"Astana","country_name":"Kazakhstan","country_code":"KAZ","timezone":"Asia\/Almaty"},{"id":"sr:venue:18439","name":"Court 4","city_name":"Astana","country_name":"Kazakhstan","country_code":"KAZ","timezone":"Asia\/Almaty"},{"id":"sr:venue:31557","name":"Court 9","city_name":"Astana","country_name":"Kazakhstan","country_code":"KAZ","timezone":"Asia\/Almaty"},{"id":"sr:venue:32005","name":"Indoor Center Court","city_name":"Astana","country_name":"Kazakhstan","country_code":"KAZ","timezone":"Asia\/Almaty"},{"id":"sr:venue:43100","name":"Court 5","city_name":"Astana","country_name":"Kazakhstan","country_code":"KAZ","timezone":"Asia\/Almaty"},{"id":"sr:venue:59164","name":"Indoor Court 3","city_name":"Astana","country_name":"Kazakhstan","country_code":"KAZ","timezone"

In [ ]:
complexes_data=response.json()

In [ ]:
complx_data=[]

In [4]:
for complexes in complexes_data["complexes"]:
     complexes_details = {
          "complex_id": complexes.get("id"),
          "complex_name": complexes.get("name")
        
     }
     complx_data.append(complexes_details)

#complexes_info is complexes_details

In [6]:
import pandas as pd

In [7]:
df3=pd.DataFrame(complx_data)

In [8]:
df3

           complex_id                                      complex_name
0      sr:complex:705                                          Nacional
1     sr:complex:1078                             Estadio de la Cartuja
2     sr:complex:1495                                       Sibur Arena
3     sr:complex:2375                        Complexo de Tenis do Jamor
4     sr:complex:4032             Shree Shiv Chhatrapati Sports Complex
..                ...                                               ...
615  sr:complex:81681  Tennis Courts of the SW University Neofit Rilski
616  sr:complex:81713                        Penina Hotel & Golf Resort
617  sr:complex:81717                                       Bloomington
618  sr:complex:81745                              Clube Tenis Portimao
619  sr:complex:81751                             Kallang Tennis Centre

[620 rows x 2 columns]

In [9]:
df3.count()

complex_id      620
complex_name    620
dtype: int64

In [10]:
df3.to_csv("complexes_table.csv",index=False)

In [23]:
venue_data=[]

In [24]:
complexes = complexes_data['complexes']

In [25]:
for complexe in complexes_data["complexes"]:
    for venue in complexe.get('venues', []):
        venue_info = {
            "complex_id": complexe['id'],
            
            "venue_id": venue['id'],
            "venue_name": venue['name'],
            "city_name": venue['city_name'],
            "country_name": venue['country_name'],
            "country_code": venue['country_code'],
            "timezone": venue['timezone']
        }
        venue_data.append(venue_info)

In [26]:
import pandas as pd

In [27]:
df4=pd.DataFrame(venue_data)

In [28]:
df4

,complex_id,venue_id,venue_name,city_name,country_name,country_code,timezone
0,sr:complex:705,sr:venue:70045,Cancha Central,Santiago,Chile,CHL,America/Santiago
1,sr:complex:1078,sr:venue:74856,Centre Court,Seville,Spain,ESP,Europe/Madrid
2,sr:complex:1078,sr:venue:74858,Court One,Seville,Spain,ESP,Europe/Madrid
3,sr:complex:1495,sr:venue:1496,COURT 1,Saint Petersburg,Russia,RUS,Europe/Moscow
4,sr:complex:1495,sr:venue:1500,CENTER COURT,Saint Petersburg,Russia,RUS,Europe/Moscow
...,...,...,...,...,...,...,...
3188,sr:complex:81717,sr:venue:81721,Bloomington - Court 7,Bloomington,USA,USA,America/New_York
3189,sr:complex:81717,sr:venue:81723,Bloomington - Court 6,Bloomington,USA,USA,America/New_York
3190,sr:complex:81717,sr:venue:81725,Bloomington - Court 5,Bloomington,USA,USA,America/New_York
3191,sr:complex:81745,sr:venue:81741,Clube Tenis Portimao - Court FREDGIL (Indoor),Alvor,Portugal,PRT,Europe/Lisbon
3192,sr:complex:81745,sr:venue:81743,Clube Tenis Portimao - Court Portimão (Indoor),Alvor,Portugal,PRT,Europe/Lisbon

In [29]:
df4.count()

complex_id      3193
venue_id        3193
venue_name      3193
city_name       3193
country_name    3193
country_code    3193
timezone        3193
dtype: int64

In [30]:
df4.to_csv("venues_table.csv",index=False)

In [33]:
# Step 3: Extracting Doubles competitor rankings

import requests

url = "https://api.sportradar.com/tennis/trial/v3/en/double_competitors_rankings.json?api_key=rrUKuG1XtLDSIfQvyOAxO7Vl8tpqL7SGtiZ6aogP"

headers = {"accept": "application/json"}

response = requests.get(url, headers=headers)

print(response.text)

{"generated_at":"2025-01-21T17:20:17+00:00","rankings":[{"type_id":2,"name":"ATP","year":2025,"week":4,"gender":"men","competitor_rankings":[{"rank":1,"movement":0,"points":7350,"competitions_played":22,"competitor":{"id":"sr:competitor:49363","name":"Pavic, Mate","country":"Croatia","country_code":"HRV","abbreviation":"PAV"}},{"rank":1,"movement":0,"points":7350,"competitions_played":22,"competitor":{"id":"sr:competitor:51836","name":"Arevalo-Gonzalez, Marcelo","country":"El Salvador","country_code":"SLV","abbreviation":"ARE"}},{"rank":3,"movement":0,"points":6565,"competitions_played":22,"competitor":{"id":"sr:competitor:87690","name":"Thompson, Jordan","country":"Australia","country_code":"AUS","abbreviation":"THO"}},{"rank":4,"movement":0,"points":6350,"competitions_played":17,"competitor":{"id":"sr:competitor:15568","name":"Granollers, Marcel","country":"Spain","country_code":"ESP","abbreviation":"GRA"}},{"rank":4,"movement":0,"points":6350,"competitions_played":17,"competitor":{"id":"sr:competitor:16160","name":"Zeballos, Horacio","country":"Argentina","country_code":"ARG","abbreviation":"ZEB"}},{"rank":6,"movement":3,"points":5990,"competitions_played":20,"competitor":{"id":"sr:competitor:15310","name":"Bolelli, Simone","country":"Italy","country_code":"ITA","abbreviation":"BOL"}},{"rank":7,"movement":1,"points":5990,"competitions_played":22,"competitor":{"id":"sr:competitor:95801","name":"Vavassori, Andrea","country":"Italy","country_code":"ITA","abbreviation":"VAV"}},{"rank":8,"movement":-2,"points":5930,"competitions_played":24,"competitor":{"id":"sr:competitor:16608","name":"Mektic, Nikola","country":"Croatia","country_code":"HRV","abbreviation":"MEK"}},{"rank":9,"movement":1,"points":5880,"competitions_played":20,"competitor":{"id":"sr:competitor:36593","name":"Krawietz, Kevin","country":"Germany","country_code":"DEU","abbreviation":"KRA"}},{"rank":10,"movement":1,"points":5790,"competitions_played":19,"competitor":{"id":"sr:competitor:52293","name":"Putz, Tim","country":"Germany","country_code":"DEU","abbreviation":"PUT"}},{"rank":11,"movement":-4,"points":5680,"competitions_played":22,"competitor":{"id":"sr:competitor:50954","name":"Koolhof, Wesley","country":"Netherlands","country_code":"NLD","abbreviation":"KOO"}},{"rank":12,"movement":0,"points":5640,"competitions_played":20,"competitor":{"id":"sr:competitor:124658","name":"Purcell, Max","country":"Australia","country_code":"AUS","abbreviation":"PUR"}},{"rank":13,"movement":1,"points":5165,"competitions_played":31,"competitor":{"id":"sr:competitor:637970","name":"Patten, Henry","country":"Great Britain","country_code":"GBR","abbreviation":"PAT"}},{"rank":14,"movement":2,"points":5145,"competitions_played":28,"competitor":{"id":"sr:competitor:14898","name":"Heliovaara, Harri","country":"Finland","country_code":"FIN","abbreviation":"HEL"}},{"rank":15,"movement":-2,"points":5105,"competitions_played":20,"competitor":{"id":"sr:competitor:16409","name":"Ebden, Matthew","country":"Australia","country_code":"AUS","abbreviation":"EBD"}},{"rank":16,"movement":-1,"points":5000,"competitions_played":20,"competitor":{"id":"sr:competitor:15307","name":"Bopanna, Rohan","country":"India","country_code":"IND","abbreviation":"BRO"}},{"rank":17,"movement":0,"points":4025,"competitions_played":28,"competitor":{"id":"sr:competitor:16151","name":"Venus, Michael","country":"New Zealand","country_code":"NZL","abbreviation":"VEN"}},{"rank":18,"movement":0,"points":3670,"competitions_played":27,"competitor":{"id":"sr:competitor:53785","name":"Skupski, Neal","country":"Great Britain","country_code":"GBR","abbreviation":"SKU"}},{"rank":19,"movement":2,"points":3330,"competitions_played":24,"competitor":{"id":"sr:competitor:38181","name":"Molteni, Andres","country":"Argentina","country_code":"ARG","abbreviation":"MOL"}},{"rank":20,"movement":-1,"points":3320,"competitions_played":34,"competitor":{"id":"sr:competitor:55989","name":"Withrow, Jackson","country":"USA","country_code":"USA","abbreviation":"WIT"}},{"rank":20,"movement":-1,"points":3320,"competitions_played":34,"competitor":{"id":"sr:competitor:210736","name":"Lammons, Nathaniel","country":"USA","country_code":"USA","abbreviation":"LAM"}},{"rank":22,"movement":0,"points":3150,"competitions_played":19,"competitor":{"id":"sr:competitor:15548","name":"Gonzalez, Maximo","country":"Argentina","country_code":"ARG","abbreviation":"GON"}},{"rank":23,"movement":0,"points":2940,"competitions_played":35,"competitor":{"id":"sr:competitor:59131","name":"Glasspool, Lloyd","country":"Great Britain","country_code":"GBR","abbreviation":"GLA"}},{"rank":24,"movement":0,"points":2870,"competitions_played":27,"competitor":{"id":"sr:competitor:52202","name":"Nys, Hugo","country":"Monaco","country_code":"MCO","abbreviation":"NYS"}},{"rank":25,"movement":0,"points":2780,"competitions_played":25,"competitor":{"id":"sr:competitor:112805","name":"Zielinski, Jan","country":"Poland","country_code":"POL","abbreviation":"ZIE"}},{"rank":26,"movement":0,"points":2760,"competitions_played":25,"competitor":{"id":"sr:competitor:16275","name":"Dodig, Ivan","country":"Croatia","country_code":"HRV","abbreviation":"DOD"}},{"rank":27,"movement":0,"points":2710,"competitions_played":27,"competitor":{"id":"sr:competitor:47834","name":"Murray, Jamie","country":"Great Britain","country_code":"GBR","abbreviation":"MUR"}},{"rank":28,"movement":1,"points":2695,"competitions_played":27,"competitor":{"id":"sr:competitor:106349","name":"Reboul, Fabien","country":"France","country_code":"FRA","abbreviation":"REB"}},{"rank":29,"movement":-1,"points":2595,"competitions_played":23,"competitor":{"id":"sr:competitor:14553","name":"Ram, Rajeev","country":"USA","country_code":"USA","abbreviation":"RAM"}},{"rank":30,"movement":0,"points":2595,"competitions_played":26,"competitor":{"id":"sr:competitor:59324","name":"Pavlasek, Adam","country":"Czechia","country_code":"CZE","abbreviation":"PAV"}},{"rank":31,"movement":0,"points":2515,"competitions_played":34,"competitor":{"id":"sr:competitor:108099","name":"Cash, Julian","country":"Great Britain","country_code":"GBR","abbreviation":"CAS"}},{"rank":32,"movement":1,"points":2450,"competitions_played":33,"competitor":{"id":"sr:competitor:206889","name":"Galloway, Robert","country":"USA","country_code":"USA","abbreviation":"GAL"}},{"rank":33,"movement":1,"points":2445,"competitions_played":31,"competitor":{"id":"sr:competitor:56629","name":"Peers, John","country":"Australia","country_code":"AUS","abbreviation":"PEE"}},{"rank":34,"movement":1,"points":2440,"competitions_played":27,"competitor":{"id":"sr:competitor:104917","name":"Vliegen, Joran","country":"Belgium","country_code":"BEL","abbreviation":"VLI"}},{"rank":35,"movement":1,"points":2412,"competitions_played":27,"competitor":{"id":"sr:competitor:76263","name":"Matos, Rafael","country":"Brazil","country_code":"BRA","abbreviation":"MAT"}},{"rank":36,"movement":2,"points":2335,"competitions_played":32,"competitor":{"id":"sr:competitor:106559","name":"Doumbia, Sadio","country":"France","country_code":"FRA","abbreviation":"DOU"}},{"rank":37,"movement":0,"points":2305,"competitions_played":27,"competitor":{"id":"sr:competitor:81059","name":"Gille, Sander","country":"Belgium","country_code":"BEL","abbreviation":"GIL"}},{"rank":38,"movement":1,"points":2295,"competitions_played":26,"competitor":{"id":"sr:competitor:16124","name":"Melo, Marcelo","country":"Brazil","country_code":"BRA","abbreviation":"MEL"}},{"rank":39,"movement":1,"points":2280,"competitions_played":25,"competitor":{"id":"sr:competitor:14835","name":"Roger-Vasselin, Edouard","country":"France","country_code":"FRA","abbreviation":"ROG"}},{"rank":40,"movement":-8,"points":2220,"competitions_played":20,"competitor":{"id":"sr:competitor:74173","name":"Salisbury, Joe","country":"Great Britain","country_code":"GBR","abbreviation":"SAL"}},{"rank":41,"movement":0,"points":2152,"competitions_played":29,"competitor":{"id":"sr:competitor:114831","name":"Erler, Alexander","country":"Austria","country_code":"AUT","abbreviation":"ERL"}},{"rank":42,"movement":1,"points":2111,"competitions_played":27,"competitor":{"id":"sr:competitor:45105","name":"Behar, Ariel","country":"Uruguay","country_code":"URY","abbreviation":"BEH"}},{"rank":43,"movement":-1,"points":2070,"competitions_played":22,"competitor":{"id":"sr:competitor:25189","name":"Krajicek, Austin","country":"USA","country_code":"USA","abbreviation":"KRA"}},{"rank":44,"movement":0,"points":2030,"competitions_played":27,"competitor":{"id":"sr:competitor:47966","name":"Olivetti, Albano","country":"France","country_code":"FRA","abbreviation":"OLI"}},{"rank":45,"movement":0,"points":1980,"competitions_played":30,"competitor":{"id":"sr:competitor:15305","name":"Gonzalez, Santiago","country":"Mexico","country_code":"MEX","abbreviation":"GON"}},{"rank":46,"movement":0,"points":1948,"competitions_played":30,"competitor":{"id":"sr:competitor:78793","name":"Miedler, Lucas","country":"Austria","country_code":"AUT","abbreviation":"MIE"}},{"rank":47,"movement":1,"points":1895,"competitions_played":26,"competitor":{"id":"sr:competitor:22967","name":"Bhambri, Yuki","country":"India","country_code":"IND","abbreviation":"BHA"}},{"rank":48,"movement":-1,"points":1860,"competitions_played":34,"competitor":{"id":"sr:competitor:48646","name":"Barrientos, Nicolas","country":"Colombia","country_code":"COL","abbreviation":"BAR"}},{"rank":49,"movement":0,"points":1825,"competitions_played":11,"competitor":{"id":"sr:competitor:300540","name":"Machac, Tomas","country":"Czechia","country_code":"CZE","abbreviation":"MAC"}},{"rank":50,"movement":0,"points":1780,"competitions_played":10,"competitor":{"id":"sr:competitor:75813","name":"Zhang, Zhizhen","country":"China","country_code":"CHN","abbreviation":"ZHA"}},{"rank":51,"movement":0,"points":1770,"competitions_played":32,"competitor":{"id":"sr:competitor:15588","name":"Rojer, Jean-Julien","country":"Netherlands","country_code":"NLD","abbreviation":"ROJ"}},{"rank":52,"movement":0,"points":1760,"competitions_played":33,"competitor":{"id":"sr:competitor:66864","name":"Arends, Sander","country":"Netherlands","country_code":"NLD","abbreviation":"ARE"}},{"rank":53,"movement":0,"points":1738,"competitions_played":33,"competitor":{"id":"sr:competitor:62410","name":"Johnson, Luke","country":"Great Britain","country_code":"GBR","abbreviation":"JOH"}},{"rank":54,"movement":0,"points":1645,"competitions_played":35,"competitor":{"id":"sr:competitor:69362","name":"Mansouri, Skander","country":"Tunisia","country_code":"TUN","abbreviation":"MAN"}},{"rank":55,"movement":2,"points":1600,"competitions_played":30,"competitor":{"id":"sr:competitor:230186","name":"Verbeek, Sem","country":"Netherlands","country_code":"NLD","abbreviation":"VER"}},{"rank":56,"movement":2,"points":1600,"competitions_played":32,"competitor":{"id":"sr:competitor:47295","name":"Andreozzi, Guido","country":"Argentina","country_code":"ARG","abbreviation":"AND"}},{"rank":57,"movement":-2,"points":1586,"competitions_played":34,"competitor":{"id":"sr:competitor:108755","name":"Jebens, Hendrik","country":"Germany","country_code":"DEU","abbreviation":"JEB"}},{"rank":57,"movement":-2,"points":1586,"competitions_played":34,"competitor":{"id":"sr:competitor:231188","name":"Frantzen, Constantin","country":"Germany","country_code":"DEU","abbreviation":"FRA"}},{"rank":59,"movement":0,"points":1467,"competitions_played":32,"competitor":{"id":"sr:competitor:49306","name":"Reyes-Varela, Miguel","country":"Mexico","country_code":"MEX","abbreviation":"REY"}},{"rank":60,"movement":0,"points":1401,"competitions_played":26,"competitor":{"id":"sr:competitor:25457","name":"Nedovyesov, Aleksandr","country":"Kazakhstan","country_code":"KAZ","abbreviation":"NED"}},{"rank":61,"movement":1,"points":1360,"competitions_played":26,"competitor":{"id":"sr:competitor:104421","name":"Mies, Andreas","country":"Germany","country_code":"DEU","abbreviation":"MIE"}},{"rank":62,"movement":-1,"points":1355,"competitions_played":26,"competitor":{"id":"sr:competitor:16198","name":"Escobar, Gonzalo","country":"Ecuador","country_code":"ECU","abbreviation":"ESC"}},{"rank":63,"movement":1,"points":1355,"competitions_played":43,"competitor":{"id":"sr:competitor:231090","name":"Arribage, Theo","country":"France","country_code":"FRA","abbreviation":"ARR"}},{"rank":64,"movement":-1,"points":1325,"competitions_played":31,"competitor":{"id":"sr:competitor:81763","name":"Jacq, Gregoire","country":"France","country_code":"FRA","abbreviation":"JAC"}},{"rank":65,"movement":0,"points":1316,"competitions_played":32,"competitor":{"id":"sr:competitor:52244","name":"Balaji, N. Sriram","country":"India","country_code":"IND","abbreviation":"BAL"}},{"rank":66,"movement":1,"points":1285,"competitions_played":36,"competitor":{"id":"sr:competitor:111195","name":"Luz, Orlando","country":"Brazil","country_code":"BRA","abbreviation":"LUZ"}},{"rank":67,"movement":1,"points":1270,"competitions_played":10,"competitor":{"id":"sr:competitor:203681","name":"Korda, Sebastian","country":"USA","country_code":"USA","abbreviation":"KOR"}},{"rank":68,"movement":1,"points":1265,"competitions_played":30,"competitor":{"id":"sr:competitor:70348","name":"Goransson, Andre","country":"Sweden","country_code":"SWE","abbreviation":"GOR"}},{"rank":69,"movement":1,"points":1250,"competitions_played":30,"competitor":{"id":"sr:competitor:17038","name":"Smith, John-Patrick","country":"Australia","country_code":"AUS","abbreviation":"SMI"}},{"rank":70,"movement":-4,"points":1226,"competitions_played":24,"competitor":{"id":"sr:competitor:121182","name":"Guinard, Manuel","country":"France","country_code":"FRA","abbreviation":"GUI"}},{"rank":71,"movement":0,"points":1206,"competitions_played":31,"competitor":{"id":"sr:competitor:16042","name":"Haase, Robin","country":"Netherlands","country_code":"NLD","abbreviation":"HAA"}},{"rank":72,"movement":0,"points":1182,"competitions_played":33,"competitor":{"id":"sr:competitor:918463","name":"Bollipalli, Rithvik Choudary","country":"India","country_code":"IND","abbreviation":"BOL"}},{"rank":73,"movement":1,"points":1182,"competitions_played":33,"competitor":{"id":"sr:competitor:204781","name":"Nouza, Petr","country":"Czechia","country_code":"CZE","abbreviation":"NOU"}},{"rank":74,"movement":1,"points":1175,"competitions_played":29,"competitor":{"id":"sr:competitor:152900","name":"Rikl, Patrik","country":"Czechia","country_code":"CZE","abbreviation":"RIK"}},{"rank":75,"movement":9,"points":1161,"competitions_played":36,"competitor":{"id":"sr:competitor:52065","name":"Harrison, Christian","country":"USA","country_code":"USA","abbreviation":"HAR"}},{"rank":76,"movement":0,"points":1149,"competitions_played":32,"competitor":{"id":"sr:competitor:127646","name":"Cabral, Francisco","country":"Portugal","country_code":"PRT","abbreviation":"CAB"}},{"rank":77,"movement":-4,"points":1140,"competitions_played":28,"competitor":{"id":"sr:competitor:41475","name":"Arneodo, Romain","country":"Monaco","country_code":"MCO","abbreviation":"ARN"}},{"rank":78,"movement":-1,"points":1140,"competitions_played":35,"competitor":{"id":"sr:competitor:287215","name":"Seggerman, Ryan","country":"USA","country_code":"USA","abbreviation":"SEG"}},{"rank":79,"movement":-1,"points":1118,"competitions_played":38,"competitor":{"id":"sr:competitor:23899","name":"King, Evan","country":"USA","country_code":"USA","abbreviation":"KIN"}},{"rank":80,"movement":1,"points":1073,"competitions_played":42,"competitor":{"id":"sr:competitor:112969","name":"Schnaitter, Jakob","country":"Germany","country_code":"DEU","abbreviation":"SCH"}},{"rank":80,"movement":1,"points":1073,"competitions_played":42,"competitor":{"id":"sr:competitor:936355","name":"Wallner, Mark","country":"Germany","country_code":"DEU","abbreviation":"WAL"}},{"rank":82,"movement":1,"points":1070,"competitions_played":28,"competitor":{"id":"sr:competitor:16043","name":"Middelkoop, Matwe","country":"Netherlands","country_code":"NLD","abbreviation":"MID"}},{"rank":83,"movement":-4,"points":1069,"competitions_played":36,"competitor":{"id":"sr:competitor:223868","name":"Matuszewski, Piotr","country":"Poland","country_code":"POL","abbreviation":"MAT"}},{"rank":84,"movement":-4,"points":1067,"competitions_played":30,"competitor":{"id":"sr:competitor:76361","name":"Kadhe, Arjun","country":"India","country_code":"IND","abbreviation":"KAD"}},{"rank":85,"movement":0,"points":1015,"competitions_played":8,"competitor":{"id":"sr:competitor:47975","name":"Hanfmann, Yannick","country":"Germany","country_code":"DEU","abbreviation":"HAN"}},{"rank":86,"movement":0,"points":1005,"competitions_played":12,"competitor":{"id":"sr:competitor:63438","name":"McDonald, Mackenzie","country":"USA","country_code":"USA","abbreviation":"MCD"}},{"rank":87,"movement":0,"points":990,"competitions_played":9,"competitor":{"id":"sr:competitor:129368","name":"Koepfer, Dominik","country":"Germany","country_code":"DEU","abbreviation":"KOE"}},{"rank":88,"movement":0,"points":961,"competitions_played":28,"competitor":{"id":"sr:competitor:52263","name":"Hidalgo, Diego","country":"Ecuador","country_code":"ECU","abbreviation":"HID"}},{"rank":89,"movement":0,"points":960,"competitions_played":7,"competitor":{"id":"sr:competitor:57163","name":"Zverev, Alexander","country":"Germany","country_code":"DEU","abbreviation":"ZVE"}},{"rank":90,"movement":0,"points":958,"competitions_played":34,"competitor":{"id":"sr:competitor:1020797","name":"Trhac, Patrik","country":"USA","country_code":"USA","abbreviation":"TRH"}},{"rank":91,"movement":1,"points":948,"competitions_played":38,"competitor":{"id":"sr:competitor:77653","name":"Cornea, Victor","country":"Romania","country_code":"ROU","abbreviation":"COR"}},{"rank":92,"movement":1,"points":937,"competitions_played":19,"competitor":{"id":"sr:competitor:299130","name":"Hijikata, Rinky","country":"Australia","country_code":"AUS","abbreviation":"HIJ"}},{"rank":93,"movement":2,"points":922,"competitions_played":36,"competitor":{"id":"sr:competitor:73572","name":"Zormann, Marcelo","country":"Brazil","country_code":"BRA","abbreviation":"ZOR"}},{"rank":94,"movement":2,"points":915,"competitions_played":9,"competitor":{"id":"sr:competitor:871495","name":"Michelsen, Alex","country":"USA","country_code":"USA","abbreviation":"MIC"}},{"rank":95,"movement":-1,"points":907,"competitions_played":35,"competitor":{"id":"sr:competitor:16992","name":"Willis, Marcus","country":"Great Britain","country_code":"GBR","abbreviation":"WIL"}},{"rank":96,"movement":-5,"points":890,"competitions_played":36,"competitor":{"id":"sr:competitor:98413","name":"Drzewiecki, Karol","country":"Poland","country_code":"POL","abbreviation":"DRZ"}},{"rank":97,"movement":1,"points":887,"competitions_played":38,"competitor":{"id":"sr:competitor:147104","name":"Romios, Matthew Christopher","country":"Australia","country_code":"AUS","abbreviation":"ROM"}},{"rank":98,"movement":-1,"points":883,"competitions_played":29,"competitor":{"id":"sr:competitor:60920","name":"Nedunchezhiyan, Jeevan","country":"India","country_code":"IND","abbreviation":"NED"}},{"rank":99,"movement":0,"points":882,"competitions_played":36,"competitor":{"id":"sr:competitor:16492","name":"Eysseric, Jonathan","country":"France","country_code":"FRA","abbreviation":"EYS"}},{"rank":100,"movement":0,"points":880,"competitions_played":39,"competitor":{"id":"sr:competitor:16823","name":"Romboli, Fernando","country":"Brazil","country_code":"BRA","abbreviation":"ROM"}},{"rank":101,"movement":0,"points":871,"competitions_played":33,"competitor":{"id":"sr:competitor:16854","name":"Molchanov, Denys","country":"Ukraine","country_code":"UKR","abbreviation":"MOL"}},{"rank":102,"movement":0,"points":855,"competitions_played":14,"competitor":{"id":"sr:competitor:808628","name":"Shelton, Ben","country":"USA","country_code":"USA","abbreviation":"SHE"}},{"rank":103,"movement":0,"points":834,"competitions_played":27,"competitor":{"id":"sr:competito

In [ ]:
doubles_data=response.json()

In [ ]:
doubles_rank=[]

In [36]:
for comptns in doubles_data["rankings"]:
    for ranks in comptns.get( "competitor_rankings",[]):
        rank_details={
            "rank":ranks["rank"],
            "movement":ranks["movement"],
            "points":ranks["points"],
            "competitions_played":ranks["competitions_played"],
            "competitor_id":ranks["competitor"].get("id")
        }
        doubles_rank.append(rank_details)

#rank_info is rank_details

In [37]:
import pandas as pd

In [38]:
df5=pd.DataFrame(doubles_rank)

In [39]:
df5

     rank  movement  points  competitions_played         competitor_id
0       1         0    7350                   22   sr:competitor:49363
1       1         0    7350                   22   sr:competitor:51836
2       3         0    6565                   22   sr:competitor:87690
3       4         0    6350                   17   sr:competitor:15568
4       4         0    6350                   17   sr:competitor:16160
..    ...       ...     ...                  ...                   ...
995   498         3     126                   26   sr:competitor:69964
996   499         3     126                    9   sr:competitor:18350
997   500      -110     125                    6   sr:competitor:60276
998   501         2     125                    9  sr:competitor:107327
999   502         2     125                   11  sr:competitor:759784

[1000 rows x 5 columns]

In [40]:
df5.count()

rank                   1000
movement               1000
points                 1000
competitions_played    1000
competitor_id          1000
dtype: int64

In [41]:
df5.to_csv("rankings_table.csv",index=False)

In [ ]:
# Extracting data for competitors table
competitors=[]

In [ ]:
for comptrs in doubles_data["rankings"]:
    for ranks in comptrs.get( "competitor_rankings",[]):
        competitors_details={
            "competitor_id":ranks["competitor"].get("id"),
            "name":ranks["competitor"].get("name"),
            "country":ranks["competitor"].get("country"),
            "country_code":ranks["competitor"].get("country_code"),
            "abbreviation":ranks["competitor"].get("abbreviation")
        }
        competitors.append(competitors_details)

In [44]:
df6=pd.DataFrame(competitors)

In [45]:
df6

,competitor_id,name,country,country_code,abbreviation
0,sr:competitor:49363,"Pavic, Mate",Croatia,HRV,PAV
1,sr:competitor:51836,"Arevalo-Gonzalez, Marcelo",El Salvador,SLV,ARE
2,sr:competitor:87690,"Thompson, Jordan",Australia,AUS,THO
3,sr:competitor:15568,"Granollers, Marcel",Spain,ESP,GRA
4,sr:competitor:16160,"Zeballos, Horacio",Argentina,ARG,ZEB
...,...,...,...,...,...
995,sr:competitor:69964,"Estable, Julieta",Argentina,ARG,EST
996,sr:competitor:18350,"Voracova, Renata",Czechia,CZE,VOR
997,sr:competitor:60276,"Podoroska, Nadia",Argentina,ARG,POD
998,sr:competitor:107327,"In-Albon, Ylena",Switzerland,CHE,IN-
999,sr:competitor:759784,"El Aouni, Aya",Morocco,MAR,EL

In [46]:
df6.count()

competitor_id    1000
name             1000
country          1000
country_code      936
abbreviation     1000
dtype: int64

In [47]:
df6.fillna("NULL",inplace=True)

In [48]:
df6

,competitor_id,name,country,country_code,abbreviation
0,sr:competitor:49363,"Pavic, Mate",Croatia,HRV,PAV
1,sr:competitor:51836,"Arevalo-Gonzalez, Marcelo",El Salvador,SLV,ARE
2,sr:competitor:87690,"Thompson, Jordan",Australia,AUS,THO
3,sr:competitor:15568,"Granollers, Marcel",Spain,ESP,GRA
4,sr:competitor:16160,"Zeballos, Horacio",Argentina,ARG,ZEB
...,...,...,...,...,...
995,sr:competitor:69964,"Estable, Julieta",Argentina,ARG,EST
996,sr:competitor:18350,"Voracova, Renata",Czechia,CZE,VOR
997,sr:competitor:60276,"Podoroska, Nadia",Argentina,ARG,POD
998,sr:competitor:107327,"In-Albon, Ylena",Switzerland,CHE,IN-
999,sr:competitor:759784,"El Aouni, Aya",Morocco,MAR,EL

In [49]:
df6.to_csv("competitors_table.csv",index=False)

In [1]:
!pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\taufi\appdata\local\programs\python\python312\lib\site-packages (9.1.0)

In [2]:
import mysql.connector




connection= mysql.connector.connect(
 host= "localhost",
 user= "root",
 password="Coffers@06",
 database="tennis_data"


)


print(connection)
mycursor = connection.cursor()

<mysql.connector.connection_cext.CMySQLConnection object at 0x00000202C9883AD0>

In [4]:
!pip install tabulate

Requirement already satisfied: tabulate in c:\users\taufi\appdata\local\programs\python\python312\lib\site-packages (0.9.0)

In [5]:
from tabulate import tabulate

COMPETITIONS QUERIES

In [8]:
#1.#List all competitions along with their category name

mycursor.execute(
    '''SELECT c.competition_name,cat.category_name
FROM competitions c JOIN categories cat
ON c.category_id = cat.category_id;
    
    '''             
)
results = mycursor.fetchall()
headers = ["Competition Name", "Category Name"]
table = tabulate(results, headers, tablefmt="grid")
print(table)

+--------------------------------------------------------------------+---------------------+
| Competition Name                                                   | Category Name       |
+====================================================================+=====================+
| IPTL                                                               | IPTL                |
+--------------------------------------------------------------------+---------------------+
| Juniors AO, Melbourne, Australia Men Singles                       | Juniors             |
+--------------------------------------------------------------------+---------------------+
| Juniors AO, Melbourne, Australia Men Doubles                       | Juniors             |
+--------------------------------------------------------------------+---------------------+
| Juniors AO, Melbourne, Australia Women Singles                     | Juniors             |
+--------------------------------------------------------------------+---------------------+
| Juniors AO, Melbourne, Australia Women Doubles                     | Juniors             |
+--------------------------------------------------------------------+---------------------+
| Juniors French Open, Paris, France Men Singles                     | Juniors             |
+--------------------------------------------------------------------+---------------------+
| Juniors French Open, Paris, France Men Doubles                     | Juniors             |
+--------------------------------------------------------------------+---------------------+
| Juniors French Open, Paris, France Women Singles                   | Juniors             |
+--------------------------------------------------------------------+---------------------+
| Juniors French Open, Paris, France Women Doubles                   | Juniors             |
+--------------------------------------------------------------------+---------------------+
| Juniors Wimbledon, London, GB Women Singles                        | Juniors             |
+--------------------------------------------------------------------+---------------------+
| Juniors Wimbledon, London, GB Men Singles                          | Juniors             |
+--------------------------------------------------------------------+---------------------+
| Juniors Wimbledon, London, GB Men Doubles                          | Juniors             |
+--------------------------------------------------------------------+---------------------+
| Juniors Wimbledon, London, GB Women Doubles                        | Juniors             |
+--------------------------------------------------------------------+---------------------+
| Juniors US Open, New York, USA Men Singles                         | Juniors             |
+--------------------------------------------------------------------+---------------------+
| Juniors US Open, New York, USA Men Doubles                         | Juniors             |
+--------------------------------------------------------------------+---------------------+
| Juniors US Open, New York, USA Women Singles                       | Juniors             |
+--------------------------------------------------------------------+---------------------+
| Juniors US Open, New York, USA Women Doubles                       | Juniors             |
+--------------------------------------------------------------------+---------------------+
| Legends AO, Melbourne, Australia Men Doubles                       | Legends             |
+--------------------------------------------------------------------+---------------------+
| Legends AO, Melbourne, Australia Women Doubles                     | Legends             |
+--------------------------------------------------------------------+---------------------+
| Legends French Open, Paris, France Men Doubles                     | Legends             |
+--------------------------------------------------------------------+---------------------+
| Legends French Open, Paris, France Women Doubles                   | Legends             |
+--------------------------------------------------------------------+---------------------+
| Legends Wimbledon, London, GB Men Doubles                          | Legends             |
+--------------------------------------------------------------------+---------------------+
| Legends Wimbledon, London, GB Women Doubles                        | Legends             |
+--------------------------------------------------------------------+---------------------+
| Legends US Open, New York, USA Men Doubles                         | Legends             |
+--------------------------------------------------------------------+---------------------+
| Legends US Open, New York, USA Women Doubles                       | Legends             |
+--------------------------------------------------------------------+---------------------+
| Legends Australian Open, Melbourne, Australia, Mixed Doubles       | Legends             |
+--------------------------------------------------------------------+---------------------+
| Legends Wimbledon, London, Great Britain Mixed Doubles             | Legends             |
+--------------------------------------------------------------------+---------------------+
| Legends French Open, Paris, France Mixed Doubles                   | Legends             |
+--------------------------------------------------------------------+---------------------+
| Wheelchairs AO, Melbourne, Australia Men Singles                   | Wheelchairs         |
+--------------------------------------------------------------------+---------------------+
| Wheelchairs AO, Melbourne, Australia Men Doubles                   | Wheelchairs         |
+--------------------------------------------------------------------+---------------------+
| Wheelchairs AO, Melbourne, Australia Women Singles                 | Wheelchairs         |
+--------------------------------------------------------------------+---------------------+
| Wheelchairs AO, Melbourne, Australia Women Doubles                 | Wheelchairs         |
+--------------------------------------------------------------------+---------------------+
| Wheelchairs French Open, Paris, France Men Singles                 | Wheelchairs         |
+--------------------------------------------------------------------+---------------------+
| Wheelchairs French Open, Paris, France Men Doubles                 | Wheelchairs         |
+--------------------------------------------------------------------+---------------------+
| Wheelchairs French Open, Paris, France Women Singles               | Wheelchairs         |
+--------------------------------------------------------------------+---------------------+
| Wheelchairs French Open, Paris, France Women Doubles               | Wheelchairs         |
+--------------------------------------------------------------------+---------------------+
| Wheelchairs Wimbledon, London, GB Men Singles                      | Wheelchairs         |
+--------------------------------------------------------------------+---------------------+
| Wheelchairs Wimbledon, London, GB Men Doubles                      | Wheelchairs         |
+--------------------------------------------------------------------+---------------------+
| Wheelchairs Wimbledon, London, GB Women Singles                    | Wheelchairs         |
+--------------------------------------------------------------------+---------------------+
| Wheelchairs Wimbledon, London, GB Women Doubles                    | Wheelchairs         |
+--------------------------------------------------------------------+---------------------+
| Wheelchairs US Open, New York, USA Men Singles                     | Wheelchairs         |
+--------------------------------------------------------------------+---------------------+
| Wheelchairs US Open, New York, USA Men Doubles                     | Wheelchairs         |
+--------------------------------------------------------------------+---------------------+
| Wheelchairs US Open, New York, USA Women Singles                   | Wheelchairs         |
+--------------------------------------------------------------------+---------------------+
| Wheelchairs US Open, New York, USA Women Doubles                   | Wheelchairs         |
+--------------------------------------------------------------------+---------------------+
| Hopman Cup                                                         | Hopman Cup          |
+--------------------------------------------------------------------+---------------------+
| ITF Women Campos Do Jordao, Brazil Women Singles                   | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Women Campos Do Jordao, Brazil Women Doubles                   | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Women Brcko, Bosnia & Herzegovina Women Singles                | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Women Brcko, Bosnia & Herzegovina Women Doubles                | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Women Albena, Bulgaria Women Singles                           | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Women Albena, Bulgaria Women Doubles                           | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Women Monterrey, Mexico Women Singles                          | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Women Monterrey, Mexico Women Doubles                          | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Women Duino Aurisina, Italy Women Singles                      | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Women Duino Aurisina, Italy Women Doubles                      | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Women Melbourne, Australia Women Singles                       | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Women Melbourne, Australia Women Doubles                       | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Women Santa Fe, Argentina Women Singles                        | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Women Santa Fe, Argentina Women Doubles                        | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Women Eastbourne, Great Britain Women Singles                  | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Women Eastbourne, Great Britain Women Doubles                  | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Women Grand Baie La Croisette, Mauritius Women Singles         | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Women Grand Baie La Croisette, Mauritius Women Doubles         | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Women Baton Rouge, USA Women Singles                           | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Women Baton Rouge, USA Women Doubles                           | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Women Kaohsiung, Chinese Taipei Women Singles                  | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Women Kaohsiung, Chinese Taipei Women Doubles                  | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Women Bursa, Turkey Women Singles                              | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Women Bursa, Turkey Women Doubles                              | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Women Graz, Austria Women Singles                              | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Women Graz, Austria Women Doubles                              | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Women Koper, Slovenia Women Singles                            | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Women Koper, Slovenia Women Doubles                            | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Women Cakovec, Croatia Women Singles                           | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Women Cakovec, Croatia Women Doubles                           | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Women Kiryat Gat, Israel Women Singles                         | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Women Kiryat Gat, Israel Women Doubles                         | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Women Tiberias, Israel Women Singles                           | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Women Tiberias, Israel Women Doubles                           | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Women San Carlos, Argentina Women Singles                      | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Women San Carlos, Argentina Women Doubles                      | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Women Kirkland, USA Women Singles                              | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Women Kirkland, USA Women Doubles                              | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Women Raipur, India Women Singles                              | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Women Raipur, India Women Doubles                              | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Women Bratislava, Slovakia Women Singles                       | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Women Bratislava, Slovakia Women Doubles                       | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Women Gulbarga, India Women Singles                            | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Women Gulbarga, India Women Doubles                            | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Women Tel Aviv-Ramat Gan, Israel Women Singles                 | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Women Tel Aviv-Ramat Gan, Israel Women Doubles                 | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Women Indore, India Women Singles                              | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Women Indore, India Women Doubles                              | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Djibouti 02A, Women Singles                                    | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Djibouti 02A, Women Doubles                                    | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF USA 04A, Women Singles                                         | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF USA 04A, Women Doubles                                         | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Hong Kong 04A, Women Singles                                   | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Hong Kong 04A, Women Doubles                                   | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Women Lins, Brazil Women Singles                               | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Women Lins, Brazil Women Doubles                               | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Women Bauru, Brazil Women Singles                              | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Women Bauru, Brazil Women Doubles                              | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Georgia 02A, Women Singles                                     | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Georgia 02A, Women Doubles                                     | ITF Women           |
+--------------------------------------------------------------------+---------------------+
| ITF Russia 07A, Women Singles                                      | ITF Women           |
+--------------------------------------------------------------------+---------------------+

In [9]:
#2.Count the number of competitions in each category

mycursor.execute(
    '''SELECT Categories.category_name, COUNT(Competitions.competition_id) AS competition_count
FROM Competitions
JOIN Categories ON Competitions.category_id = Categories.category_id
GROUP BY Categories.category_name;
    '''             
)
results = mycursor.fetchall()
headers = ["category_name", "num_of_competitions"]
table = tabulate(results, headers, tablefmt="grid")
print(table)

+---------------------+-----------------------+
| category_name       |   num_of_competitions |
+=====================+=======================+
| IPTL                |                     1 |
+---------------------+-----------------------+
| Juniors             |                    16 |
+---------------------+-----------------------+
| Legends             |                    11 |
+---------------------+-----------------------+
| Wheelchairs         |                    16 |
+---------------------+-----------------------+
| Hopman Cup          |                     1 |
+---------------------+-----------------------+
| ITF Women           |                  2032 |
+---------------------+-----------------------+
| Wheelchairs Juniors |                     6 |
+---------------------+-----------------------+
| United Cup          |                     1 |
+---------------------+-----------------------+
| UTR Men             |                    21 |
+---------------------+-----------------------+
| UTR Women           |                    18 |
+---------------------+-----------------------+
| ATP                 |                   220 |
+---------------------+-----------------------+
| WTA                 |                   253 |
+---------------------+-----------------------+
| Challenger          |                   868 |
+---------------------+-----------------------+
| Federation Cup      |                     1 |
+---------------------+-----------------------+
| Davis Cup           |                     1 |
+---------------------+-----------------------+
| ITF Men             |                  2198 |
+---------------------+-----------------------+
| Exhibition          |                    32 |
+---------------------+-----------------------+
| WTA 125K            |                   152 |
+---------------------+-----------------------+

In [14]:
#3.Find all competitions of type 'doubles':

mycursor.execute(
    '''SELECT competition_name,type FROM Competitions WHERE type = 'doubles';
'''             
)
results = mycursor.fetchall()
headers = ["competition_name", "Type"]
table = tabulate(results, headers, tablefmt="grid")
print(table)

+--------------------------------------------------------------------+---------+
| competition_name                                                   | Type    |
+====================================================================+=========+
| ITF Men Stara Zagora, Bulgaria Men Doubles                         | doubles |
+--------------------------------------------------------------------+---------+
| ITF Men Sibiu, Romania Men Doubles                                 | doubles |
+--------------------------------------------------------------------+---------+
| ITF Men Busto Arsizio, Italy Men Doubles                           | doubles |
+--------------------------------------------------------------------+---------+
| ITF Men Sabac, Serbia Men Doubles                                  | doubles |
+--------------------------------------------------------------------+---------+
| ITF Men Seefeld, Austria Men Doubles                               | doubles |
+--------------------------------------------------------------------+---------+
| ATP Challenger Portoroz, Slovenia Men Doubles                      | doubles |
+--------------------------------------------------------------------+---------+
| ITF Men Focsani, Romania Men Doubles                               | doubles |
+--------------------------------------------------------------------+---------+
| ATP Challenger Eskisehir, Turkey Men Doubles                       | doubles |
+--------------------------------------------------------------------+---------+
| ITF Men Tallinn, Estonia Men Doubles                               | doubles |
+--------------------------------------------------------------------+---------+
| ITF Women Campos Do Jordao, Brazil Women Doubles                   | doubles |
+--------------------------------------------------------------------+---------+
| ITF Men Misiones, Argentina Men Doubles                            | doubles |
+--------------------------------------------------------------------+---------+
| ATP Challenger Liberec, Czech Republic Men Doubles                 | doubles |
+--------------------------------------------------------------------+---------+
| ITF Men Sleza, Poland Men Doubles                                  | doubles |
+--------------------------------------------------------------------+---------+
| ITF Men Bejar, Spain Men Doubles                                   | doubles |
+--------------------------------------------------------------------+---------+
| ATP Challenger Meerbusch, Germany Men Doubles                      | doubles |
+--------------------------------------------------------------------+---------+
| ITF Men Geneva, Switzerland Men Doubles                            | doubles |
+--------------------------------------------------------------------+---------+
| ITF Women Brcko, Bosnia & Herzegovina Women Doubles                | doubles |
+--------------------------------------------------------------------+---------+
| ITF Men Medias, Romania Men Doubles                                | doubles |
+--------------------------------------------------------------------+---------+
| ITF Men Este, Italy Men Doubles                                    | doubles |
+--------------------------------------------------------------------+---------+
| ITF Men Jupille-Sur-Meuse, Belgium Men Doubles                     | doubles |
+--------------------------------------------------------------------+---------+
| ITF Men Libreville, Gabon Men Doubles                              | doubles |
+--------------------------------------------------------------------+---------+
| ITF Men Campos Do Jordao, Brazil Men Doubles                       | doubles |
+--------------------------------------------------------------------+---------+
| ITF Men Manizales, Colombia Men Doubles                            | doubles |
+--------------------------------------------------------------------+---------+
| ITF Men Damme, Belgium Men Doubles                                 | doubles |
+--------------------------------------------------------------------+---------+
| ITF Men Lausanne, Switzerland Men Doubles                          | doubles |
+--------------------------------------------------------------------+---------+
| ITF Men Quito, Ecuador Men Doubles                                 | doubles |
+--------------------------------------------------------------------+---------+
| ATP Challenger Kenitra, Morocco Men Doubles                        | doubles |
+--------------------------------------------------------------------+---------+
| ATP Challenger Porto, Portugal Men Doubles                         | doubles |
+--------------------------------------------------------------------+---------+
| ITF Men Nis, Serbia Men Doubles                                    | doubles |
+--------------------------------------------------------------------+---------+
| ITF Men Sokobanja, Serbia Men Doubles                              | doubles |
+--------------------------------------------------------------------+---------+
| ITF Men Cochabamba, Bolivia Men Doubles                            | doubles |
+--------------------------------------------------------------------+---------+
| ITF Women Albena, Bulgaria Women Doubles                           | doubles |
+--------------------------------------------------------------------+---------+
| ITF Men Sant Cugat, Spain Men Doubles                              | doubles |
+--------------------------------------------------------------------+---------+
| ATP Challenger Mouilleron-Le-Captif, France Men Doubles            | doubles |
+--------------------------------------------------------------------+---------+
| ATP Challenger Traralgon, Australia Men Doubles                    | doubles |
+--------------------------------------------------------------------+---------+
| ATP Challenger Andria, Italy Men Doubles                           | doubles |
+--------------------------------------------------------------------+---------+
| ITF Men Nicosia, Cyprus Men Doubles                                | doubles |
+--------------------------------------------------------------------+---------+
| ITF Men Popayan, Colombia Men Doubles                              | doubles |
+--------------------------------------------------------------------+---------+
| ITF Men Bol, Croatia Men Doubles                                   | doubles |
+--------------------------------------------------------------------+---------+
| ITF Men Raipur, India Men Doubles                                  | doubles |
+--------------------------------------------------------------------+---------+
| ITF Women Monterrey, Mexico Women Doubles                          | doubles |
+--------------------------------------------------------------------+---------+
| ITF Men Larnaca, Cyprus Men Doubles                                | doubles |
+--------------------------------------------------------------------+---------+
| ITF Women Duino Aurisina, Italy Women Doubles                      | doubles |
+--------------------------------------------------------------------+---------+
| WTA Rio de Janeiro, Brazil Women Doubles                           | doubles |
+--------------------------------------------------------------------+---------+
| WTA Hong Kong, Hong Kong Women Doubles                             | doubles |
+--------------------------------------------------------------------+---------+
| WTA Wuhan, China Women Doubles                                     | doubles |
+--------------------------------------------------------------------+---------+
| ATP Shenzhen, China Men Doubles                                    | doubles |
+--------------------------------------------------------------------+---------+
| ATP Rio de Janeiro, Brazil Men Doubles                             | doubles |
+--------------------------------------------------------------------+---------+
| ATP Challenger Chennai, India Men Doubles                          | doubles |
+--------------------------------------------------------------------+---------+
| ATP Challenger Kolkata, India Men Doubles                          | doubles |
+--------------------------------------------------------------------+---------+
| ATP Challenger Morelos, Mexico Men Doubles                         | doubles |
+--------------------------------------------------------------------+---------+
| ATP Challenger New Delhi, India Men Doubles                        | doubles |
+--------------------------------------------------------------------+---------+
| ITF Men Kish, Iran Men Doubles                                     | doubles |
+--------------------------------------------------------------------+---------+
| ITF Men Bhimavaram, India Men Doubles                              | doubles |
+--------------------------------------------------------------------+---------+
| ATP Challenger Irving, USA Men Doubles                             | doubles |
+--------------------------------------------------------------------+---------+
| ITF Men Manila, Philippines Men Doubles                            | doubles |
+--------------------------------------------------------------------+---------+
| ITF Men Melbourne, Australia Men Doubles                           | doubles |
+--------------------------------------------------------------------+---------+
| ITF Men Oran, Algeria Men Doubles                                  | doubles |
+--------------------------------------------------------------------+---------+
| ITF Men Algiers, Algeria Men Doubles                               | doubles |
+--------------------------------------------------------------------+---------+
| ITF Women Melbourne, Australia Women Doubles                       | doubles |
+--------------------------------------------------------------------+---------+
| ITF Men Karshi, Uzbekistan Men Doubles                             | doubles |
+--------------------------------------------------------------------+---------+
| ATP Challenger Shenzhen, China Men Doubles                         | doubles |
+--------------------------------------------------------------------+---------+
| ATP Challenger Vercelli, Italy Men Doubles                         | doubles |
+--------------------------------------------------------------------+---------+
| ITF Men Queretaro, Mexico Men Doubles                              | doubles |
+--------------------------------------------------------------------+---------+
| ATP Challenger Taipei, Chinese Taipei Men Doubles                  | doubles |
+--------------------------------------------------------------------+---------+
| ATP Challenger Gimcheon, Korea Rep. Men Doubles                    | doubles |
+--------------------------------------------------------------------+---------+
| ATP Challenger Aix en Provence, France Men Doubles                 | doubles |
+--------------------------------------------------------------------+---------+
| ITF Men Galati, Romania Men Doubles                                | doubles |
+--------------------------------------------------------------------+---------+
| ATP Challenger Mestre, Italy Men Doubles                           | doubles |
+--------------------------------------------------------------------+---------+
| ATP Challenger Mohammedia, Morocco Men Doubles                     | doubles |
+--------------------------------------------------------------------+---------+
| ATP Challenger Nanchang, China Men Doubles                         | doubles |
+--------------------------------------------------------------------+---------+
| ATP Challenger Padova, Italy Men Doubles                           | doubles |
+--------------------------------------------------------------------+---------+
| ATP Challenger Vicenza, Italy Men Doubles                          | doubles |
+--------------------------------------------------------------------+---------+
| WTA Bucharest, Romania Women Doubles                               | doubles |
+--------------------------------------------------------------------+---------+
| WTA 125K Nanchang, China Women Doubles                             | doubles |
+--------------------------------------------------------------------+---------+
| ITF Men Chaco, Argentina Men Doubles                               | doubles |
+--------------------------------------------------------------------+---------+
| ATP Challenger Cortina, Italy Men Doubles                          | doubles |
+--------------------------------------------------------------------+---------+
| ITF Women Santa Fe, Argentina Women Doubles                        | doubles |
+--------------------------------------------------------------------+---------+
| ITF Men Tehran, Iran Men Doubles                                   | doubles |
+--------------------------------------------------------------------+---------+
| ITF Men Vsevolozhsk, Russia Men Doubles                            | doubles |
+--------------------------------------------------------------------+---------+
| ATP Challenger Brescia, Italy Men Doubles                          | doubles |
+--------------------------------------------------------------------+---------+
| ATP Challenger Pune, India Men Doubles                             | doubles |
+--------------------------------------------------------------------+---------+
| WTA 125K Limoges, France Women Doubles                             | doubles |
+--------------------------------------------------------------------+---------+
| WTA Tianjin, China Women Doubles                                   | doubles |
+--------------------------------------------------------------------+---------+
| ITF Men Wollongong, Australia Men Doubles                          | doubles |
+--------------------------------------------------------------------+---------+
| ITF Men Gwalior, India Men Doubles                                 | doubles |
+--------------------------------------------------------------------+---------+
| ATP Challenger Happy Valley, Australia Men Doubles                 | doubles |
+--------------------------------------------------------------------+---------+
| ATP Challenger Hong Kong, Hong Kong Men Doubles                    | doubles |
+--------------------------------------------------------------------+---------+
| ITF Men Santiago de los Caballeros, Dominican Republic Men Doubles | doubles |
+--------------------------------------------------------------------+---------+
| ATP Challenger Glasgow, Great Britain Men Doubles                  | doubles |
+--------------------------------------------------------------------+---------+
| ATP Challenger Santo Domingo, Dominican Republic Men Doubles       | doubles |
+--------------------------------------------------------------------+---------+
| ATP Challenger Wroclaw, Poland Men Doubles                         | doubles |
+--------------------------------------------------------------------+---------+
| ATP Challenger Drummondville, Canada Men Doubles                   | doubles |
+--------------------------------------------------------------------+---------+
| ATP Challenger Raanana, Israel Men Doubles                         | doubles |
+--------------------------------------------------------------------+---------+
| ATP Challenger Launceston, Australia Men Doubles                   | doubles |
+--------------------------------------------------------------------+---------+
| ATP Geneva, Switzerland Men Doubles                                | doubles |
+--------------------------------------------------------------------+---------+
| ATP Istanbul, Turkey Men Doubles                                   | doubles |
+--------------------------------------------------------------------+---------+
| ATP Quito, Ecuador Men Doubles                                     | doubles |
+--------------------------------------------------------------------+---------+
| WTA Nottingham, Great Britain Women Doubles                        | doubles |
+--------------------------------------------------------------------+---------+
| ATP Challenger Batman, Turkey Men Doubles                          | doubles |
+--------------------------------------------------------------------+---------+
| ATP Challenger Puebla, Mexico Men Doubles                          | doubles |
+--------------------------------------------------------------------+---------+
| ATP Challenger Ilkley, Great Britain Men Doubles                   | doubles |
+--------------------------------------------------------------------+---------+
| ATP Challenger Manchester, Great Britain Men Doubles               | doubles |
+--------------------------------------------------------------------+---------+
| ATP Challenger Surbiton, Great Britain Men Doubles                 | doubles |
+--------------------------------------------------------------------+---------+
| ATP Challenger Poprad Tatry, Slovakia Men Doubles                  | doubles |
+--------------------------------------------------------------------+---------+
| ATP Challenger Perugia, Italy Men Doubles                          | doubles |
+--------------------------------------------------------------------+---------+
| ATP Challenger Moscow, Russia Men Doubles                          | doubles |
+--------------------------------------------------------------------+---------+
| ATP Estoril, Portugal Men Doubles                                  | doubles |
+--------------------------------------------------------------------+---------+
| ITF Men Jassowal, India Men Doubles                                | doubles |
+--------------------------------------------------------------------+---------+
| ITF Women Eastbourne, Great Britain Women Doubles                  | doubles |
+--------------------------------------------------------------------+---------+
| ITF Men Sarajevo, Bosnia/Herzegovina Men Doubles                   | doubles |
+--------------------------------------------------------------------+---------+
| ITF Women Grand Baie La Croisette, Mauritius Women Doubles         | doubles |
+--------------------------------------------------------------------+---------+
| ITF Women Baton Rouge, USA Women Doubles                           | doubles |
+--------------------------------------------------------------------+---------+
| ITF Women Kaohsiung, Chinese Taipei Women Doubles                  | doubles |
+--------------------------------------------------------------------+---------+
| ITF Women Bursa, Turkey Women Doubles                              | doubles |
+--------------------------------------------------------------------+---------+
| ATP Challenger Manerbio, Italy Men Doubles                         | doubles |
+--------------------------------------------------------------------+---------+
| ATP Challenger Agri, Turkey Men Doubles                            | doubles |
+--------------------------------------------------------------------+---------+
| ATP Challenger Cary, USA Men Doubles                               | doubles |
+--------------------------------------------------------------------+---------+
| ATP Challenger Columbus, USA Men Doubles                           | doubles |
+--------------------------------------------------------------------+---------+
| WTA 125K Dalian, China Women Doubles                               | doubles |
+--------------------------------------------------------------------+---------+
| WTA 125K Carlsbad, USA Women Doubles                               | doubles |
+--------------------------------------------------------------------+---------+
| WTA 125K Hua Hin, Thailand Women Doubles                           | doubles |

In [15]:
#4.Get competitions that belong to a specific category (e.g., ITF Men)

mycursor.execute(
    '''SELECT c.competition_name, cat.category_name
FROM competitions c
JOIN categories cat ON c.category_id = cat.category_id
WHERE cat.category_name = 'ITF Men'; '''             
)
results = mycursor.fetchall()
headers = ["competition_name", "category_name"]
table = tabulate(results, headers, tablefmt="grid")
print(table)

+--------------------------------------------------------------------+-----------------+
| competition_name                                                   | category_name   |
+====================================================================+=================+
| ITF Men Stara Zagora, Bulgaria Men Singles                         | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Stara Zagora, Bulgaria Men Doubles                         | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Sibiu, Romania Men Singles                                 | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Sibiu, Romania Men Doubles                                 | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Busto Arsizio, Italy Men Singles                           | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Busto Arsizio, Italy Men Doubles                           | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Sabac, Serbia Men Singles                                  | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Sabac, Serbia Men Doubles                                  | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Seefeld, Austria Men Singles                               | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Seefeld, Austria Men Doubles                               | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Focsani, Romania Men Singles                               | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Focsani, Romania Men Doubles                               | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Tallinn, Estonia Men Singles                               | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Tallinn, Estonia Men Doubles                               | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Misiones, Argentina Men Singles                            | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Misiones, Argentina Men Doubles                            | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Sleza, Poland Men Singles                                  | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Sleza, Poland Men Doubles                                  | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Bejar, Spain Men Singles                                   | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Bejar, Spain Men Doubles                                   | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Geneva, Switzerland Men Singles                            | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Geneva, Switzerland Men Doubles                            | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Medias, Romania Men Singles                                | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Medias, Romania Men Doubles                                | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Este, Italy Men Singles                                    | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Este, Italy Men Doubles                                    | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Jupille-Sur-Meuse, Belgium Men Singles                     | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Jupille-Sur-Meuse, Belgium Men Doubles                     | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Libreville, Gabon Men Singles                              | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Libreville, Gabon Men Doubles                              | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Campos Do Jordao, Brazil Men Singles                       | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Campos Do Jordao, Brazil Men Doubles                       | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Manizales, Colombia Men Singles                            | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Manizales, Colombia Men Doubles                            | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Damme, Belgium Men Singles                                 | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Damme, Belgium Men Doubles                                 | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Lausanne, Switzerland Men Singles                          | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Lausanne, Switzerland Men Doubles                          | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Quito, Ecuador Men Singles                                 | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Quito, Ecuador Men Doubles                                 | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Nis, Serbia Men Singles                                    | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Nis, Serbia Men Doubles                                    | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Sokobanja, Serbia Men Singles                              | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Sokobanja, Serbia Men Doubles                              | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Cochabamba, Bolivia Men Singles                            | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Cochabamba, Bolivia Men Doubles                            | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Sant Cugat, Spain Men Singles                              | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Sant Cugat, Spain Men Doubles                              | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Nicosia, Cyprus Men Singles                                | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Nicosia, Cyprus Men Doubles                                | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Popayan, Colombia Men Singles                              | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Popayan, Colombia Men Doubles                              | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Bol, Croatia Men Singles                                   | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Bol, Croatia Men Doubles                                   | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Raipur, India Men Singles                                  | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Raipur, India Men Doubles                                  | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Larnaca, Cyprus Men Singles                                | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Larnaca, Cyprus Men Doubles                                | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Kish, Iran Men Singles                                     | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Kish, Iran Men Doubles                                     | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Bhimavaram, India Men Singles                              | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Bhimavaram, India Men Doubles                              | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Manila, Philippines Men Singles                            | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Manila, Philippines Men Doubles                            | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Melbourne, Australia Men Singles                           | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Melbourne, Australia Men Doubles                           | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Oran, Algeria Men Singles                                  | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Oran, Algeria Men Doubles                                  | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Algiers, Algeria Men Singles                               | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Algiers, Algeria Men Doubles                               | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Karshi, Uzbekistan Men Doubles                             | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Queretaro, Mexico Men Singles                              | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Queretaro, Mexico Men Doubles                              | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Galati, Romania Men Singles                                | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Galati, Romania Men Doubles                                | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Chaco, Argentina Men Singles                               | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Chaco, Argentina Men Doubles                               | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Tehran, Iran Men Singles                                   | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Tehran, Iran Men Doubles                                   | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Vsevolozhsk, Russia Men Singles                            | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Vsevolozhsk, Russia Men Doubles                            | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Wollongong, Australia Men Singles                          | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Wollongong, Australia Men Doubles                          | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Gwalior, India Men Singles                                 | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Gwalior, India Men Doubles                                 | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Santiago de los Caballeros, Dominican Republic Men Singles | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Santiago de los Caballeros, Dominican Republic Men Doubles | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Jassowal, India Men Singles                                | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Jassowal, India Men Doubles                                | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Sarajevo, Bosnia/Herzegovina Men Singles                   | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Sarajevo, Bosnia/Herzegovina Men Doubles                   | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Erzurum, Turkey Men Singles                                | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Erzurum, Turkey Men Doubles                                | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Duino Aurisina, Italy Men Singles                          | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Duino Aurisina, Italy Men Doubles                          | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Israel F14, Men Singles                                        | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Israel F14, Men Doubles                                        | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Middelkerke, Belgium Men Singles                           | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Middelkerke, Belgium Men Doubles                           | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Rancagua, Chile Men Singles                                | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Rancagua, Chile Men Doubles                                | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Ismaning, Germany Men Singles                              | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Ismaning, Germany Men Doubles                              | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Valledupar, Colombia Men Singles                           | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Valledupar, Colombia Men Doubles                           | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Margarita Island, Venezuela Men Singles                    | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Margarita Island, Venezuela Men Doubles                    | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men La Libertad, El Salvador Men Singles                       | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men La Libertad, El Salvador Men Doubles                       | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Limassol, Cyprus Men Singles                               | ITF Men         |
+--------------------------------------------------------------------+-----------------+
| ITF Men Limassol, Cyprus Men Doubles                               | ITF Men         |

In [16]:
#5.Identify parent competitions and their sub-competitions

mycursor.execute(
    '''SELECT a.competition_id, a.parent_id, b.category_name
FROM competitions a JOIN categories b ON a.category_id = b.category_id'''             
)

results = mycursor.fetchall()
headers = ["sub_competition","parent_competition","category_name"]
table = tabulate(results, headers, tablefmt="grid")
print(table)

+----------------------+----------------------+---------------------+
| sub_competition      | parent_competition   | category_name       |
+======================+======================+=====================+
| sr:competition:12229 | NOT                  | IPTL                |
+----------------------+----------------------+---------------------+
| sr:competition:14814 | sr:competition:14812 | Juniors             |
+----------------------+----------------------+---------------------+
| sr:competition:14816 | sr:competition:14812 | Juniors             |
+----------------------+----------------------+---------------------+
| sr:competition:14818 | sr:competition:14812 | Juniors             |
+----------------------+----------------------+---------------------+
| sr:competition:14820 | sr:competition:14812 | Juniors             |
+----------------------+----------------------+---------------------+
| sr:competition:15399 | sr:competition:15397 | Juniors             |
+----------------------+----------------------+---------------------+
| sr:competition:15401 | sr:competition:15397 | Juniors             |
+----------------------+----------------------+---------------------+
| sr:competition:15403 | sr:competition:15397 | Juniors             |
+----------------------+----------------------+---------------------+
| sr:competition:15405 | sr:competition:15397 | Juniors             |
+----------------------+----------------------+---------------------+
| sr:competition:15660 | sr:competition:15658 | Juniors             |
+----------------------+----------------------+---------------------+
| sr:competition:15678 | sr:competition:15658 | Juniors             |
+----------------------+----------------------+---------------------+
| sr:competition:15680 | sr:competition:15658 | Juniors             |
+----------------------+----------------------+---------------------+
| sr:competition:15682 | sr:competition:15658 | Juniors             |
+----------------------+----------------------+---------------------+
| sr:competition:18032 | sr:competition:18030 | Juniors             |
+----------------------+----------------------+---------------------+
| sr:competition:18034 | sr:competition:18030 | Juniors             |
+----------------------+----------------------+---------------------+
| sr:competition:18036 | sr:competition:18030 | Juniors             |
+----------------------+----------------------+---------------------+
| sr:competition:18038 | sr:competition:18030 | Juniors             |
+----------------------+----------------------+---------------------+
| sr:competition:14834 | sr:competition:14832 | Legends             |
+----------------------+----------------------+---------------------+
| sr:competition:14854 | sr:competition:14832 | Legends             |
+----------------------+----------------------+---------------------+
| sr:competition:15419 | sr:competition:15417 | Legends             |
+----------------------+----------------------+---------------------+
| sr:competition:15421 | sr:competition:15417 | Legends             |
+----------------------+----------------------+---------------------+
| sr:competition:15664 | sr:competition:15662 | Legends             |
+----------------------+----------------------+---------------------+
| sr:competition:15666 | sr:competition:15662 | Legends             |
+----------------------+----------------------+---------------------+
| sr:competition:18058 | sr:competition:18056 | Legends             |
+----------------------+----------------------+---------------------+
| sr:competition:18060 | sr:competition:18056 | Legends             |
+----------------------+----------------------+---------------------+
| sr:competition:36137 | sr:competition:14832 | Legends             |
+----------------------+----------------------+---------------------+
| sr:competition:37319 | sr:competition:15662 | Legends             |
+----------------------+----------------------+---------------------+
| sr:competition:40069 | sr:competition:15417 | Legends             |
+----------------------+----------------------+---------------------+
| sr:competition:14824 | sr:competition:14822 | Wheelchairs         |
+----------------------+----------------------+---------------------+
| sr:competition:14826 | sr:competition:14822 | Wheelchairs         |
+----------------------+----------------------+---------------------+
| sr:competition:14828 | sr:competition:14822 | Wheelchairs         |
+----------------------+----------------------+---------------------+
| sr:competition:14830 | sr:competition:14822 | Wheelchairs         |
+----------------------+----------------------+---------------------+
| sr:competition:15409 | sr:competition:15407 | Wheelchairs         |
+----------------------+----------------------+---------------------+
| sr:competition:15411 | sr:competition:15407 | Wheelchairs         |
+----------------------+----------------------+---------------------+
| sr:competition:15413 | sr:competition:15407 | Wheelchairs         |
+----------------------+----------------------+---------------------+
| sr:competition:15415 | sr:competition:15407 | Wheelchairs         |
+----------------------+----------------------+---------------------+
| sr:competition:15670 | sr:competition:15668 | Wheelchairs         |
+----------------------+----------------------+---------------------+
| sr:competition:15672 | sr:competition:15668 | Wheelchairs         |
+----------------------+----------------------+---------------------+
| sr:competition:15674 | sr:competition:15668 | Wheelchairs         |
+----------------------+----------------------+---------------------+
| sr:competition:15676 | sr:competition:15668 | Wheelchairs         |
+----------------------+----------------------+---------------------+
| sr:competition:18048 | sr:competition:18046 | Wheelchairs         |
+----------------------+----------------------+---------------------+
| sr:competition:18050 | sr:competition:18046 | Wheelchairs         |
+----------------------+----------------------+---------------------+
| sr:competition:18052 | sr:competition:18046 | Wheelchairs         |
+----------------------+----------------------+---------------------+
| sr:competition:18054 | sr:competition:18046 | Wheelchairs         |
+----------------------+----------------------+---------------------+
| sr:competition:620   | NOT                  | Hopman Cup          |
+----------------------+----------------------+---------------------+
| sr:competition:10181 | sr:competition:10179 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:10183 | sr:competition:10179 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:10421 | sr:competition:10419 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:10423 | sr:competition:10419 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:10757 | sr:competition:10755 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:10759 | sr:competition:10755 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:11051 | sr:competition:11049 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:11053 | sr:competition:11049 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:11081 | sr:competition:11079 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:11083 | sr:competition:11079 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:11403 | sr:competition:11401 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:11405 | sr:competition:11401 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:11913 | sr:competition:11911 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:11915 | sr:competition:11911 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:12663 | sr:competition:12661 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:12665 | sr:competition:12661 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:12723 | sr:competition:12721 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:12725 | sr:competition:12721 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:12741 | sr:competition:12739 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:12743 | sr:competition:12739 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:12747 | sr:competition:12745 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:12749 | sr:competition:12745 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:12819 | sr:competition:12817 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:12821 | sr:competition:12817 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:12975 | sr:competition:12973 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:12977 | sr:competition:12973 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:12981 | sr:competition:12979 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:12983 | sr:competition:12979 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:12987 | sr:competition:12985 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:12989 | sr:competition:12985 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:12999 | sr:competition:12997 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13001 | sr:competition:12997 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13035 | sr:competition:13033 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13037 | sr:competition:13033 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13047 | sr:competition:13045 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13049 | sr:competition:13045 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13101 | sr:competition:13099 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13103 | sr:competition:13099 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13191 | sr:competition:13189 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13193 | sr:competition:13189 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13251 | sr:competition:13249 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13253 | sr:competition:13249 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13269 | sr:competition:13267 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13271 | sr:competition:13267 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13281 | sr:competition:13279 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13283 | sr:competition:13279 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13317 | sr:competition:13315 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13319 | sr:competition:13315 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13413 | sr:competition:13411 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13415 | sr:competition:13411 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13437 | sr:competition:13435 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13439 | sr:competition:13435 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13557 | sr:competition:13555 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13559 | sr:competition:13555 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13587 | sr:competition:13585 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13589 | sr:competition:13585 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13599 | sr:competition:13597 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13601 | sr:competition:13597 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13605 | sr:competition:13603 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13607 | sr:competition:13603 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13611 | sr:competition:13609 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13613 | sr:competition:13609 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13617 | sr:competition:13615 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13619 | sr:competition:13615 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13623 | sr:competition:13621 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13625 | sr:competition:13621 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13703 | sr:competition:13701 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13705 | sr:competition:13701 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13709 | sr:competition:13707 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13711 | sr:competition:13707 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13749 | sr:competition:13747 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13751 | sr:competition:13747 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13819 | sr:competition:13817 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13821 | sr:competition:13817 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13825 | sr:competition:13823 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13827 | sr:competition:13823 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13831 | sr:competition:13829 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13833 | sr:competition:13829 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13873 | sr:competition:13871 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13875 | sr:competition:13871 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13929 | sr:competition:13927 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13931 | sr:competition:13927 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13959 | sr:competition:13957 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13961 | sr:competition:13957 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13991 | sr:competition:13989 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:13993 | sr:competition:13989 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:14023 | sr:competition:14021 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:14025 | sr:competition:14021 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:14171 | sr:competition:14169 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:14173 | sr:competition:14169 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:14275 | sr:competition:14273 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:14277 | sr:competition:14273 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:14387 | sr:competition:14385 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:14389 | sr:competition:14385 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:14399 | sr:competition:14397 | ITF Women           |
+----------------------+----------------------+---------------------+
| sr:competition:14401 | sr:competition:14397 | ITF Women           |
+----------------------+----------------------+---------------------+

In [17]:
#6.Analyze the distribution of competition types by category

mycursor.execute(
    '''SELECT Categories.category_name, Competitions.type, COUNT(Competitions.competition_id) AS count
FROM Competitions
JOIN Categories ON Competitions.category_id = Categories.category_id
GROUP BY Categories.category_name, Competitions.type;

'''
)
results=mycursor.fetchall()
headers=["category_name","competitions_types","num_of_competitions"]
table=tabulate(results,headers,tablefmt="grid")
print(table)

+---------------------+----------------------+-----------------------+
| category_name       | competitions_types   |   num_of_competitions |
+=====================+======================+=======================+
| IPTL                | singles              |                     1 |
+---------------------+----------------------+-----------------------+
| Juniors             | singles              |                     8 |
+---------------------+----------------------+-----------------------+
| Juniors             | doubles              |                     8 |
+---------------------+----------------------+-----------------------+
| Legends             | doubles              |                     8 |
+---------------------+----------------------+-----------------------+
| Legends             | mixed_doubles        |                     3 |
+---------------------+----------------------+-----------------------+
| Wheelchairs         | singles              |                     8 |
+---------------------+----------------------+-----------------------+
| Wheelchairs         | doubles              |                     8 |
+---------------------+----------------------+-----------------------+
| Hopman Cup          | mixed                |                     1 |
+---------------------+----------------------+-----------------------+
| ITF Women           | singles              |                  1014 |
+---------------------+----------------------+-----------------------+
| ITF Women           | doubles              |                  1018 |
+---------------------+----------------------+-----------------------+
| Wheelchairs Juniors | singles              |                     4 |
+---------------------+----------------------+-----------------------+
| Wheelchairs Juniors | doubles              |                     2 |
+---------------------+----------------------+-----------------------+
| United Cup          | mixed                |                     1 |
+---------------------+----------------------+-----------------------+
| UTR Men             | singles              |                    21 |
+---------------------+----------------------+-----------------------+
| UTR Women           | singles              |                    18 |
+---------------------+----------------------+-----------------------+
| ATP                 | singles              |                   107 |
+---------------------+----------------------+-----------------------+
| ATP                 | doubles              |                   106 |
+---------------------+----------------------+-----------------------+
| ATP                 | mixed_doubles        |                     5 |
+---------------------+----------------------+-----------------------+
| ATP                 | mixed                |                     2 |
+---------------------+----------------------+-----------------------+
| WTA                 | singles              |                   127 |
+---------------------+----------------------+-----------------------+
| WTA                 | doubles              |                   126 |
+---------------------+----------------------+-----------------------+
| Challenger          | singles              |                   435 |
+---------------------+----------------------+-----------------------+
| Challenger          | doubles              |                   433 |
+---------------------+----------------------+-----------------------+
| Federation Cup      | mixed                |                     1 |
+---------------------+----------------------+-----------------------+
| Davis Cup           | mixed                |                     1 |
+---------------------+----------------------+-----------------------+
| ITF Men             | singles              |                  1099 |
+---------------------+----------------------+-----------------------+
| ITF Men             | doubles              |                  1099 |
+---------------------+----------------------+-----------------------+
| Exhibition          | singles              |                    22 |
+---------------------+----------------------+-----------------------+
| Exhibition          | doubles              |                     8 |
+---------------------+----------------------+-----------------------+
| Exhibition          | mixed_doubles        |                     2 |
+---------------------+----------------------+-----------------------+
| WTA 125K            | singles              |                    76 |
+---------------------+----------------------+-----------------------+
| WTA 125K            | doubles              |                    76 |
+---------------------+----------------------+-----------------------+

In [18]:
#7.List all competitions with no parent (top-level competitions)
mycursor.execute(
    '''SELECT * FROM competitions WHERE parent_id="NOT"'''             
)
results = mycursor.fetchall()
headers = ["competition_id", "competition_name","parent_id","type","gender","category_id"]
table = tabulate(results, headers, tablefmt="grid")
print(table)

+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| competition_id       | competition_name                            | parent_id   | type    | gender   | category_id      |
+======================+=============================================+=============+=========+==========+==================+
| sr:competition:1207  | Championship International Series           | NOT         | singles | women    | sr:category:6    |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:12229 | IPTL                                        | NOT         | singles | men      | sr:category:1012 |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:15393 | ITF Men San Jose, Costa Rica Men Singles    | NOT         | singles | men      | sr:category:785  |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:15395 | ITF Men San Jose, Costa Rica Men Doubles    | NOT         | doubles | men      | sr:category:785  |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:2100  | Davis Cup                                   | NOT         | mixed   | men      | sr:category:76   |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:2102  | Billie Jean King Cup                        | NOT         | mixed   | women    | sr:category:74   |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:21028 | ITF Colombia 02A, Women Singles             | NOT         | singles | women    | sr:category:213  |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:21228 | ITF Australia 02B, Women Doubles            | NOT         | doubles | women    | sr:category:213  |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:22334 | ITF Uzbekistan 01A, Women Singles           | NOT         | singles | women    | sr:category:213  |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:22763 | ITF Tunisia 39A, Women Doubles              | NOT         | doubles | women    | sr:category:213  |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:22787 | ITF Egypt F38, Men Doubles                  | NOT         | doubles | men      | sr:category:785  |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:22959 | ITF USA 17A, Women Singles                  | NOT         | singles | women    | sr:category:213  |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:22997 | ITF Bosnia & Herzegovina 01A, Women Doubles | NOT         | doubles | women    | sr:category:213  |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:29204 | ITF Mexico F13, Men Singles                 | NOT         | singles | men      | sr:category:785  |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:29206 | ITF Mexico F13, Men Doubles                 | NOT         | doubles | men      | sr:category:785  |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:29386 | ITF Mexico 17A, Women Singles               | NOT         | singles | women    | sr:category:213  |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:31137 | ITF Mexico F30, Men Singles                 | NOT         | singles | men      | sr:category:785  |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:31139 | ITF Mexico F30, Men Doubles                 | NOT         | doubles | men      | sr:category:785  |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:31263 | ATP Cup                                     | NOT         | mixed   | men      | sr:category:3    |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:31481 | NIU                                         | NOT         | doubles | men      | sr:category:3    |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:32469 | UTR Pro Match Series Men Singles            | NOT         | singles | men      | sr:category:79   |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:32557 | LiveScore Cup, Women                        | NOT         | singles | women    | sr:category:79   |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:32683 | Battle of the Brits, Men Doubles            | NOT         | doubles | men      | sr:category:79   |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:32685 | Battle of the Brits, Men Singles            | NOT         | singles | men      | sr:category:79   |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:33007 | WTA 125K Prague, Czech Republic             | NOT         | singles | women    | sr:category:871  |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:33009 | WTA 125K Prague, Czech Republic Doubles     | NOT         | doubles | women    | sr:category:871  |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:33107 | ITF France 31A, Women Singles               | NOT         | singles | women    | sr:category:213  |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:33109 | ITF France 31A, Women Doubles               | NOT         | doubles | women    | sr:category:213  |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:35697 | ITF Colombia F7, Men Doubles                | NOT         | doubles | men      | sr:category:785  |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:37671 | ITF Sweden 09A, Women Doubles               | NOT         | doubles | women    | sr:category:213  |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:37933 | ITF Sweden F9, Men Doubles                  | NOT         | doubles | men      | sr:category:785  |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:38335 | ITF USA 53A, Women Singles                  | NOT         | singles | women    | sr:category:213  |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:38341 | United Cup                                  | NOT         | mixed   | mixed    | sr:category:2414 |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:38755 | ITF Tunisia F61 Men Singles                 | NOT         | singles | men      | sr:category:785  |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:44567 | Riyadh Exhibition                           | NOT         | singles | men      | sr:category:79   |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:45133 | ITF Tunisia 59A, Women Singles              | NOT         | singles | women    | sr:category:213  |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:45347 | UTR Newport Beach W03                       | NOT         | singles | women    | sr:category:2517 |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:45349 | UTR Olomouc W01                             | NOT         | singles | women    | sr:category:2517 |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:45357 | UTR Norman M01                              | NOT         | singles | men      | sr:category:2516 |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:45359 | UTR Los Angeles M01                         | NOT         | singles | men      | sr:category:2516 |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:45361 | UTR Cornella de Llobregat M01               | NOT         | singles | men      | sr:category:2516 |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:45363 | UTR Boca Raton W01                          | NOT         | singles | women    | sr:category:2517 |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:45365 | UTR Norman W01                              | NOT         | singles | women    | sr:category:2517 |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:45367 | UTR Newport Beach W01                       | NOT         | singles | women    | sr:category:2517 |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:45391 | UTR Olomouc M01                             | NOT         | singles | men      | sr:category:2516 |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:45427 | UTR Baton Rouge M01                         | NOT         | singles | men      | sr:category:2516 |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:45431 | UTR Tucson M01                              | NOT         | singles | men      | sr:category:2516 |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:45437 | UTR Noda M01                                | NOT         | singles | men      | sr:category:2516 |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:45471 | Winston-Salem M01                           | NOT         | singles | men      | sr:category:2516 |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:45473 | UTR Cornella de Llobregat M02               | NOT         | singles | men      | sr:category:2516 |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:45475 | UTR Baton Rogue W01                         | NOT         | singles | women    | sr:category:2517 |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:45477 | UTR Noda W01                                | NOT         | singles | women    | sr:category:2517 |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:45479 | Winston-Salem W01                           | NOT         | singles | women    | sr:category:2517 |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:45481 | UTR Newport Beach W02                       | NOT         | singles | women    | sr:category:2517 |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:45483 | UTR Cornella de Llobregat W01               | NOT         | singles | women    | sr:category:2517 |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:45493 | UTR Baton Rouge M02                         | NOT         | singles | men      | sr:category:2516 |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:45495 | UTR Noda M02                                | NOT         | singles | men      | sr:category:2516 |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:45497 | UTR Blagoevgrad M01                         | NOT         | singles | men      | sr:category:2516 |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:45499 | UTR Newport Beach M01                       | NOT         | singles | men      | sr:category:2516 |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:45501 | UTR Cornella de Llobregat W02               | NOT         | singles | women    | sr:category:2517 |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:45505 | UTR Bonita Springs W01                      | NOT         | singles | women    | sr:category:2517 |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:45595 | UTR Noda W02                                | NOT         | singles | women    | sr:category:2517 |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:45635 | UTR Olomouc M02                             | NOT         | singles | men      | sr:category:2516 |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:45637 | UTR Alvor M01                               | NOT         | singles | men      | sr:category:2516 |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:45639 | UTR Boca Raton M02                          | NOT         | singles | men      | sr:category:2516 |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:45643 | UTR Bloomington M01                         | NOT         | singles | men      | sr:category:2516 |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:45651 | UTR Dubai W01                               | NOT         | singles | women    | sr:category:2517 |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:45657 | UTR Blagoevgrad W01                         | NOT         | singles | women    | sr:category:2517 |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:45659 | UTR Boca Raton W01                          | NOT         | singles | women    | sr:category:2517 |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:45747 | UTR Yokohama M01                            | NOT         | singles | men      | sr:category:2516 |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:45753 | UTR Gyor M01                                | NOT         | singles | men      | sr:category:2516 |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:45755 | UTR Alvor M02                               | NOT         | singles | men      | sr:category:2516 |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:45757 | UTR Newport Beach M03                       | NOT         | singles | men      | sr:category:2516 |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:45761 | UTR Yokohama W01                            | NOT         | singles | women    | sr:category:2517 |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:45763 | UTR Dubai W02                               | NOT         | singles | women    | sr:category:2517 |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:620   | Hopman Cup                                  | NOT         | mixed   | mixed    | sr:category:181  |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+
| sr:competition:660   | World Team Cup                              | NOT         | mixed   | men      | sr:category:3    |
+----------------------+---------------------------------------------+-------------+---------+----------+------------------+

COMPLEXES VENUES QUERIES

In [1]:
!pip install tabulate

Requirement already satisfied: tabulate in c:\users\taufi\appdata\local\programs\python\python312\lib\site-packages (0.9.0)

In [2]:
from tabulate import tabulate

In [8]:
#1.List all venues along with their associated complex name:

mycursor.execute(
'''SELECT venue_name,complex_name
FROM Venues
JOIN Complexes ON venues.complex_id = complexes.complex_id;'''
)

results = mycursor.fetchall()
headers = ["venue_name", "complexe_name"]
table = tabulate(results, headers, tablefmt="grid")
print(table)

+------------------------------------------------------------+------------------------------------------------------------+
| venue_name                                                 | complexe_name                                              |
+============================================================+============================================================+
| Estadio Monumental                                         | Club Tennis Las Terrazas de Miraflores                     |
+------------------------------------------------------------+------------------------------------------------------------+
| Stadium                                                    | Shenzhen International Tennis Center                       |
+------------------------------------------------------------+------------------------------------------------------------+
| Court 2                                                    | Shenzhen Longgang Sports Center                            |
+------------------------------------------------------------+------------------------------------------------------------+
| Court 7                                                    | Olympic Park Tennis Center                                 |
+------------------------------------------------------------+------------------------------------------------------------+
| Court 20                                                   | Melbourne Park                                             |
+------------------------------------------------------------+------------------------------------------------------------+
| Court 22                                                   | Melbourne Park                                             |
+------------------------------------------------------------+------------------------------------------------------------+
| Estadio Ivan Elias Moreno                                  | Club Tennis Las Terrazas de Miraflores                     |
+------------------------------------------------------------+------------------------------------------------------------+
| Stade Numa-Daly Magenta                                    | Complexe Tennistique Marie-Louise Lhuillier                |
+------------------------------------------------------------+------------------------------------------------------------+
| Noevir Stadium                                             | Miki Disaster Management Park                              |
+------------------------------------------------------------+------------------------------------------------------------+
| Shanghai Stadium                                           | Qi Zhong Tennis Center                                     |
+------------------------------------------------------------+------------------------------------------------------------+
| Cancha 5                                                   | Acapulco Princess Mundo Imperial                           |
+------------------------------------------------------------+------------------------------------------------------------+
| Court 13                                                   | Indian Wells Tennis Garden                                 |
+------------------------------------------------------------+------------------------------------------------------------+
| Center Court                                               | Royal Tennis Club de Marrakech                             |
+------------------------------------------------------------+------------------------------------------------------------+
| Court 1                                                    | Royal Tennis Club de Marrakech                             |
+------------------------------------------------------------+------------------------------------------------------------+
| Court 2                                                    | Royal Tennis Club de Marrakech                             |
+------------------------------------------------------------+------------------------------------------------------------+
| Court 4                                                    | Royal Tennis Club de Marrakech                             |
+------------------------------------------------------------+------------------------------------------------------------+
| SZ Court                                                   | MTTC Iphitos e.V.                                          |
+------------------------------------------------------------+------------------------------------------------------------+
| Court 1                                                    | Centro De Ténis Do Jamor                                   |
+------------------------------------------------------------+------------------------------------------------------------+
| Center Court                                               | Tennis Club 1.FCN                                          |
+------------------------------------------------------------+------------------------------------------------------------+
| Show Court                                                 | Tennis Club 1.FCN                                          |
+------------------------------------------------------------+------------------------------------------------------------+
| Court 1                                                    | Tennis Club 1.FCN                                          |
+------------------------------------------------------------+------------------------------------------------------------+
| Court 2                                                    | Tennis Club 1.FCN                                          |
+------------------------------------------------------------+------------------------------------------------------------+
| Court 9                                                    | Country Time Club                                          |
+------------------------------------------------------------+------------------------------------------------------------+
| Estadio Alejandro Villanueva                               | Club Tennis Las Terrazas de Miraflores                     |
+------------------------------------------------------------+------------------------------------------------------------+
| Court 11                                                   | Country Time Club                                          |
+------------------------------------------------------------+------------------------------------------------------------+
| Halle des Sports                                           | Parc des Expositions Quimper Cornouaille                   |
+------------------------------------------------------------+------------------------------------------------------------+
| Court 4                                                    | USTA Billie Jean King National Tennis Center               |
+------------------------------------------------------------+------------------------------------------------------------+
| Arthur Ashe Stadium                                        | USTA Billie Jean King National Tennis Center               |
+------------------------------------------------------------+------------------------------------------------------------+
| Court 5                                                    | USTA Billie Jean King National Tennis Center               |
+------------------------------------------------------------+------------------------------------------------------------+
| Court 6                                                    | USTA Billie Jean King National Tennis Center               |
+------------------------------------------------------------+------------------------------------------------------------+
| Court 7                                                    | USTA Billie Jean King National Tennis Center               |
+------------------------------------------------------------+------------------------------------------------------------+
| Court 8                                                    | USTA Billie Jean King National Tennis Center               |
+------------------------------------------------------------+------------------------------------------------------------+
| Court 9                                                    | USTA Billie Jean King National Tennis Center               |
+------------------------------------------------------------+------------------------------------------------------------+
| Court 10                                                   | USTA Billie Jean King National Tennis Center               |
+------------------------------------------------------------+------------------------------------------------------------+
| Court 11                                                   | USTA Billie Jean King National Tennis Center               |
+------------------------------------------------------------+------------------------------------------------------------+
| Court 12                                                   | USTA Billie Jean King National Tennis Center               |
+------------------------------------------------------------+------------------------------------------------------------+
| Court 9                                                    | Ariake Tennis Forest Park Ariake Colesseum                 |
+------------------------------------------------------------+------------------------------------------------------------+
| Court 13                                                   | USTA Billie Jean King National Tennis Center               |
+------------------------------------------------------------+------------------------------------------------------------+
| Court A                                                    | Qi Zhong Tennis Center                                     |
+------------------------------------------------------------+------------------------------------------------------------+
| Court B                                                    | Qi Zhong Tennis Center                                     |
+------------------------------------------------------------+------------------------------------------------------------+
| Court 14                                                   | USTA Billie Jean King National Tennis Center               |
+------------------------------------------------------------+------------------------------------------------------------+
| Court C                                                    | Qi Zhong Tennis Center                                     |
+------------------------------------------------------------+------------------------------------------------------------+
| Court 15                                                   | USTA Billie Jean King National Tennis Center               |
+------------------------------------------------------------+------------------------------------------------------------+
| Cancha 10                                                  | Buenos Aires Lawn Tennis Club                              |
+------------------------------------------------------------+------------------------------------------------------------+
| Cancha 11                                                  | Buenos Aires Lawn Tennis Club                              |
+------------------------------------------------------------+------------------------------------------------------------+
| Cancha 2                                                   | Buenos Aires Lawn Tennis Club                              |
+------------------------------------------------------------+------------------------------------------------------------+
| Court 16                                                   | USTA Billie Jean King National Tennis Center               |
+------------------------------------------------------------+------------------------------------------------------------+
| Stadium 17                                                 | USTA Billie Jean King National Tennis Center               |
+------------------------------------------------------------+------------------------------------------------------------+
| Louis Armstrong Stadium                                    | USTA Billie Jean King National Tennis Center               |
+------------------------------------------------------------+------------------------------------------------------------+
| Grandstand                                                 | USTA Billie Jean King National Tennis Center               |
+------------------------------------------------------------+------------------------------------------------------------+
| Center Court                                               | Shenzhen Longgang Sports Center                            |
+------------------------------------------------------------+------------------------------------------------------------+
| Court 2                                                    | Sud de France Arena                                        |
+------------------------------------------------------------+------------------------------------------------------------+
| Court Central                                              | Les Arenes de Metz                                         |
+------------------------------------------------------------+------------------------------------------------------------+
| Court 1                                                    | Les Arenes de Metz                                         |
+------------------------------------------------------------+------------------------------------------------------------+
| CENTRALA                                                   | BNR arena                                                  |
+------------------------------------------------------------+------------------------------------------------------------+
| SEMI CENTRALA                                              | BNR arena                                                  |
+------------------------------------------------------------+------------------------------------------------------------+
| COURT 2                                                    | Tiriac Stadium                                             |
+------------------------------------------------------------+------------------------------------------------------------+
| CENTRE                                                     | Olympic Tennis School                                      |
+------------------------------------------------------------+------------------------------------------------------------+
| COURT 3                                                    | Olympic Tennis School                                      |
+------------------------------------------------------------+------------------------------------------------------------+
| COURT 4                                                    | Olympic Tennis School                                      |
+------------------------------------------------------------+------------------------------------------------------------+
| COURT 5                                                    | Olympic Tennis School                                      |
+------------------------------------------------------------+------------------------------------------------------------+
| COURT 3                                                    | BNR arena                                                  |
+------------------------------------------------------------+------------------------------------------------------------+
| Center Court                                               | Olympic Tennis Courts                                      |
+------------------------------------------------------------+------------------------------------------------------------+
| Court 2                                                    | Olympic Tennis Courts                                      |
+------------------------------------------------------------+------------------------------------------------------------+
| Court 13                                                   | Olympic Tennis Courts                                      |
+------------------------------------------------------------+------------------------------------------------------------+
| Court 11                                                   | Seoul Olympic Park Tennis Center                           |
+------------------------------------------------------------+------------------------------------------------------------+
| Quadra Guga Kuerten                                        | Jockey Club Brasileiro                                     |
+------------------------------------------------------------+------------------------------------------------------------+
| Quadra 2                                                   | Jockey Club Brasileiro                                     |
+------------------------------------------------------------+------------------------------------------------------------+
| Court 1                                                    | Ariake Tennis Forest Park Ariake Colesseum                 |
+------------------------------------------------------------+------------------------------------------------------------+
| Court 2                                                    | Ariake Tennis Forest Park Ariake Colesseum                 |
+------------------------------------------------------------+------------------------------------------------------------+
| Center Court                                               | Ariake Tennis Forest Park Ariake Colesseum                 |
+------------------------------------------------------------+------------------------------------------------------------+
| Grandstand                                                 | Arena GNP Seguros                                          |
+------------------------------------------------------------+------------------------------------------------------------+
| Centre Court                                               | Rama Gardens Hotel                                         |
+------------------------------------------------------------+------------------------------------------------------------+
| COURT 1                                                    | Rama Gardens Hotel                                         |
+------------------------------------------------------------+------------------------------------------------------------+
| Court 3                                                    | Ariake Tennis Forest Park Ariake Colesseum                 |
+------------------------------------------------------------+------------------------------------------------------------+
| Court 4                                                    | Ariake Tennis Forest Park Ariake Colesseum                 |
+------------------------------------------------------------+------------------------------------------------------------+
| Center                                                     | National Tennis Center                                     |
+------------------------------------------------------------+------------------------------------------------------------+
| Court 1                                                    | National Tennis Center                                     |
+------------------------------------------------------------+------------------------------------------------------------+
| Court 4                                                    | National Tennis Center                                     |
+------------------------------------------------------------+------------------------------------------------------------+

In [10]:
#2.Count the number of venues in each complex:

mycursor.execute(
'''SELECT complex_name, COUNT(venue_id) as num_of_venues
FROM Venues 
JOIN Complexes ON venues.complex_id = complexes.complex_id
GROUP BY complexes.complex_name;
'''
)

results = mycursor.fetchall()
headers = ["complexe_name", "num_of_venues"]
table = tabulate(results, headers, tablefmt="grid")
print(table)

+------------------------------------------------------------+-----------------+
| complexe_name                                              |   num_of_venues |
+============================================================+=================+
| Kindarena                                                  |               4 |
+------------------------------------------------------------+-----------------+
| Estadio de la Cartuja                                      |               2 |
+------------------------------------------------------------+-----------------+
| Estadio German Becker                                      |               4 |
+------------------------------------------------------------+-----------------+
| Palais des sports de Gerland                               |               7 |
+------------------------------------------------------------+-----------------+
| Sibur Arena                                                |               4 |
+------------------------------------------------------------+-----------------+
| Palais Des Sport                                           |               7 |
+------------------------------------------------------------+-----------------+
| Palasport                                                  |               4 |
+------------------------------------------------------------+-----------------+
| Salle Steredenn                                            |               6 |
+------------------------------------------------------------+-----------------+
| Garanti Koza Arena                                         |               1 |
+------------------------------------------------------------+-----------------+
| Porsche-Arena                                              |               3 |
+------------------------------------------------------------+-----------------+
| Rotterdam Ahoy                                             |               3 |
+------------------------------------------------------------+-----------------+
| The O2                                                     |               1 |
+------------------------------------------------------------+-----------------+
| Bluesun Tennis Center                                      |               8 |
+------------------------------------------------------------+-----------------+
| Club Sonoma, Estadio Gnp Seguros                           |               3 |
+------------------------------------------------------------+-----------------+
| Accor Arena                                                |               3 |
+------------------------------------------------------------+-----------------+
| Stadium Goran Ivanisevic in ITC Stella Maris               |               1 |
+------------------------------------------------------------+-----------------+
| Roy Emerson Arena                                          |               4 |
+------------------------------------------------------------+-----------------+
| Complexo de Tenis do Jamor                                 |               5 |
+------------------------------------------------------------+-----------------+
| Club de Tenis Puente Romano                                |               9 |
+------------------------------------------------------------+-----------------+
| National Tennis Center                                     |              49 |
+------------------------------------------------------------+-----------------+
| Canberra Tennis Centre                                     |               7 |
+------------------------------------------------------------+-----------------+
| BT Arena                                                   |               2 |
+------------------------------------------------------------+-----------------+
| Valletta Cambiaso ASD                                      |               9 |
+------------------------------------------------------------+-----------------+
| Porsche Arena                                              |               5 |
+------------------------------------------------------------+-----------------+
| Taipei Arena                                               |              10 |
+------------------------------------------------------------+-----------------+
| Singapore Indoor Stadium                                   |               5 |
+------------------------------------------------------------+-----------------+
| Palais des Sports de Marseille                             |               3 |
+------------------------------------------------------------+-----------------+
| Caja Magica                                                |               3 |
+------------------------------------------------------------+-----------------+
| All England Lawn Tennis and Croquet Club                   |              19 |
+------------------------------------------------------------+-----------------+
| Stade Roland Garros                                        |              17 |
+------------------------------------------------------------+-----------------+
| Melbourne Park                                             |              25 |
+------------------------------------------------------------+-----------------+
| Qi zhong Forest Sports City Arena                          |               2 |
+------------------------------------------------------------+-----------------+
| Wake Forest University Tennis Complex                      |               6 |
+------------------------------------------------------------+-----------------+
| The Drive                                                  |               5 |
+------------------------------------------------------------+-----------------+
| Atlantic Station                                           |               4 |
+------------------------------------------------------------+-----------------+
| International Tennis Hall of Fame                          |               7 |
+------------------------------------------------------------+-----------------+
| Club Jacaranda Cumbaya                                     |              15 |
+------------------------------------------------------------+-----------------+
| Hengqin International Tennis Center Zhuhai                 |              14 |
+------------------------------------------------------------+-----------------+
| Buenos Aires Lawn Tennis Club                              |              29 |
+------------------------------------------------------------+-----------------+
| Delray Beach Tennis Center                                 |               7 |
+------------------------------------------------------------+-----------------+
| CK Sportcenter Kockelscheuer                               |               5 |
+------------------------------------------------------------+-----------------+
| Luzhniki Olympic Complex                                   |               2 |
+------------------------------------------------------------+-----------------+
| Ariake Colosseum                                           |               4 |
+------------------------------------------------------------+-----------------+
| Optics Valley International Tennis Center                  |              13 |
+------------------------------------------------------------+-----------------+
| Guangzhou Tianhe Sports Center                             |               8 |
+------------------------------------------------------------+-----------------+
| Olympic Park Tennis Center                                 |              12 |
+------------------------------------------------------------+-----------------+
| Victoria Park Tennis Court                                 |              16 |
+------------------------------------------------------------+-----------------+
| Tianjin Tuanbo International Tennis Center                 |              10 |
+------------------------------------------------------------+-----------------+
| Tashkent Tennis Centreake                                  |               2 |
+------------------------------------------------------------+-----------------+
| China National Tennis Center                               |               1 |
+------------------------------------------------------------+-----------------+
| Utsubo Tennis Center                                       |               7 |
+------------------------------------------------------------+-----------------+
| Connecticut Tennis Center                                  |              11 |
+------------------------------------------------------------+-----------------+
| Sobeys Stadium                                             |              14 |
+------------------------------------------------------------+-----------------+
| Lindner Family Tennis Center                               |              15 |
+------------------------------------------------------------+-----------------+
| Tennis Club de Strasbourg                                  |              11 |
+------------------------------------------------------------+-----------------+
| Edgbaston Priory Club                                      |               8 |
+------------------------------------------------------------+-----------------+
| Royal Tennis Club de Marrakech                             |               6 |
+------------------------------------------------------------+-----------------+
| Tennis Club 1.FCN                                          |               7 |
+------------------------------------------------------------+-----------------+
| Devonshire Park International Tennis Centre                |              12 |
+------------------------------------------------------------+-----------------+
| Tennis Club Sparta Praha                                   |              16 |
+------------------------------------------------------------+-----------------+
| Khalifa International Tennis & Squash Complex              |              12 |
+------------------------------------------------------------+-----------------+
| Club Sonoma                                                |              11 |
+------------------------------------------------------------+-----------------+
| Jockey Club Brasileiro                                     |              17 |
+------------------------------------------------------------+-----------------+
| Acapulco Princess Mundo Imperial                           |               4 |
+------------------------------------------------------------+-----------------+
| Family Circle Tennis Center                                |               6 |
+------------------------------------------------------------+-----------------+
| St. Jakobshalle Basel                                      |              11 |
+------------------------------------------------------------+-----------------+
| Wien, Wiener Stadthalle                                    |               2 |
+------------------------------------------------------------+-----------------+
| Shenzhen Longgang Sports Center                            |               2 |
+------------------------------------------------------------+-----------------+
| Queensland Tennis Centre                                   |              20 |
+------------------------------------------------------------+-----------------+
| Am Rothenbaum                                              |              12 |
+------------------------------------------------------------+-----------------+
| Kungliga Tennishallen                                      |               5 |
+------------------------------------------------------------+-----------------+
| Kitzbuehel Tennis Club Sportfeld 2                         |               8 |
+------------------------------------------------------------+-----------------+
| Gerry Weber Stadium                                        |               1 |
+------------------------------------------------------------+-----------------+
| Nottingham Tennis Centre                                   |              18 |
+------------------------------------------------------------+-----------------+
| Bastad Tennis Stadium                                      |               6 |
+------------------------------------------------------------+-----------------+
| Tennis Club de Geneve                                      |               5 |
+------------------------------------------------------------+-----------------+
| Autotron Rosmalen                                          |               7 |
+------------------------------------------------------------+-----------------+
| BNR arena                                                  |              10 |
+------------------------------------------------------------+-----------------+
| MTTC Iphitos e.V.                                          |               9 |
+------------------------------------------------------------+-----------------+
| Real Club de Tenis Barcelona                               |              11 |
+------------------------------------------------------------+-----------------+
| Hiroshima Regional Park                                    |              10 |
+------------------------------------------------------------+-----------------+
| Lyon Tennis Club                                           |               4 |
+------------------------------------------------------------+-----------------+
| Sichuan International Tennis Center                        |               9 |
+------------------------------------------------------------+-----------------+
| Swiss Tennis Arena                                         |               1 |
+------------------------------------------------------------+-----------------+
| Shenzhen Luohu Tennis Centre                               |               6 |
+------------------------------------------------------------+-----------------+
| Country Club Santa Ponsa                                   |              13 |
+------------------------------------------------------------+-----------------+
| Tennis Center Novak                                        |              10 |
+------------------------------------------------------------+-----------------+
| Madrid Arena                                               |              14 |
+------------------------------------------------------------+-----------------+
| Rama Gardens Hotel                                         |               6 |
+------------------------------------------------------------+-----------------+
| Country Time Club                                          |               9 |
+------------------------------------------------------------+-----------------+
| ŠRC MARINA PORTOROŽ                                        |               6 |
+------------------------------------------------------------+-----------------+
| I. Czech Lawn Tennis Club Praha                            |               4 |
+------------------------------------------------------------+-----------------+
| LTTC Rot-Weiss                                             |               3 |
+------------------------------------------------------------+-----------------+
| Romai Tennis Academy                                       |               4 |
+------------------------------------------------------------+-----------------+
| Tokyo Metropolitan Gymnasium                               |               1 |
+------------------------------------------------------------+-----------------+
| Sporting Club de Tenis Valencia                            |              13 |
+------------------------------------------------------------+-----------------+
| Club Naval de Campo las Salinas                            |               4 |
+------------------------------------------------------------+-----------------+
| USTA Billie Jean King National Tennis Center               |              17 |
+------------------------------------------------------------+-----------------+
| Lanxess Arena                                              |               2 |
+------------------------------------------------------------+-----------------+
| Tiburon Peninsula Club                                     |               9 |
+------------------------------------------------------------+-----------------+
| Country Club de Bogota                                     |               3 |
+------------------------------------------------------------+-----------------+
| Almaty Tennis Center                                       |               7 |
+------------------------------------------------------------+-----------------+
| Sociedade Hipica de Campinas                               |              11 |
+------------------------------------------------------------+-----------------+
| Eve Zimmermann Tennis Center                               |               8 |
+------------------------------------------------------------+-----------------+
| Sanchez-Casal Tennis Academy                               |               1 |
+------------------------------------------------------------+-----------------+
| Santo Domingo Tennis Club La Bocha                         |              18 |
+------------------------------------------------------------+-----------------+
| Lotto Arena                                                |               4 |
+------------------------------------------------------------+-----------------+
| TC Ismaning                                                |               2 |
+------------------------------------------------------------+-----------------+
| Osten & Victor Alberta Tennis Centre                       |               9 |
+------------------------------------------------------------+-----------------+
| Ningbo Tennis Center of WTA Ningbo, China w42              |              12 |
+------------------------------------------------------------+-----------------+
| Club Tennis Las Terrazas de Miraflores                     |              22 |
+------------------------------------------------------------+-----------------+
| Liuzhou Tennis Center                                      |               7 |
+------------------------------------------------------------+-----------------+
| The Boar's Head Sports Club                                |               8 |
+------------------------------------------------------------+-----------------+
| Anexo Guayaquil Tenis Club                                 |               6 |
+------------------------------------------------------------+-----------------+
| Vendéspace                                                 |               2 |
+------------------------------------------------------------+-----------------+
| Carrasco Lawn Tennis Club                                  |               4 |
+------------------------------------------------------------+-----------------+
| Goodfriend Indoor Tennis Center                            |               6 |
+------------------------------------------------------------+-----------------+
| Palais des sports de Beaublanc                             |               3 |
+------------------------------------------------------------+-----------------+
| Miki Disaster Management Park                              |               9 |
+------------------------------------------------------------+-----------------+
| Karnataka State Lawn Tennis Association                    |               7 |
+------------------------------------------------------------+-----------------+
| Racket Club, Argentina                                     |               2 |
+------------------------------------------------------------+-----------------+
| Atkins Tennis Center                                       |               9 |

In [16]:
#3.Get details of venues in a specific country (e.g., Chile):

mycursor.execute(
'''SELECT * FROM Venues
WHERE country_name = 'Chile';

'''
)

results = mycursor.fetchall()
headers = ["venues_id","venue_name","city_name","country_name","country_code","timezone","complexe_id"]
table = tabulate(results, headers, tablefmt="grid")
print(table)

+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| venues_id      | venue_name              | city_name    | country_name   | country_code   | timezone         | complexe_id      |
+================+=========================+==============+================+================+==================+==================+
| sr:venue:13830 | Cancha 1                | Santiago     | Chile          | CHL            | America/Santiago | sr:complex:62419 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:13832 | Cancha 3                | Santiago     | Chile          | CHL            | America/Santiago | sr:complex:62419 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:15858 | Centre Court            | Santiago     | Chile          | CHL            | America/Santiago | sr:complex:62419 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:15860 | Court 16                | Santiago     | Chile          | CHL            | America/Santiago | sr:complex:62419 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:15862 | Court 15                | Santiago     | Chile          | CHL            | America/Santiago | sr:complex:62419 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:15864 | Court 11                | Santiago     | Chile          | CHL            | America/Santiago | sr:complex:62419 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:1602  | Cancha Central          | Santiago     | Chile          | CHL            | America/Santiago | sr:complex:62419 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:1603  | Cancha 2                | Santiago     | Chile          | CHL            | America/Santiago | sr:complex:62419 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:1604  | Cancha 4                | Santiago     | Chile          | CHL            | America/Santiago | sr:complex:62419 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:1605  | Cancha 6                | Santiago     | Chile          | CHL            | America/Santiago | sr:complex:62419 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:17100 | Cancha 1                | Santiago     | Chile          | CHL            | America/Santiago | sr:complex:50605 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:17102 | Cancha 2                | Santiago     | Chile          | CHL            | America/Santiago | sr:complex:50605 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:17104 | Court 3                 | Santiago     | Chile          | CHL            | America/Santiago | sr:complex:50605 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:2233  | Cancha 14               | Santiago     | Chile          | CHL            | America/Santiago | sr:complex:62419 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:2234  | Cancha 16               | Santiago     | Chile          | CHL            | America/Santiago | sr:complex:62419 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:2235  | Cancha 17               | Santiago     | Chile          | CHL            | America/Santiago | sr:complex:62419 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:25740 | Court 4                 | Santiago     | Chile          | CHL            | America/Santiago | sr:complex:62419 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:26008 | Cancha Central          | Santiago     | Chile          | CHL            | America/Santiago | sr:complex:50605 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:26188 | Central                 | Santiago     | Chile          | CHL            | America/Santiago | sr:complex:62419 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:26202 | Cancha 7                | Antofagasta  | Chile          | CHL            | America/Santiago | sr:complex:73997 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:26204 | Cancha 8                | Antofagasta  | Chile          | CHL            | America/Santiago | sr:complex:73997 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:2922  | Cancha 2                | Vina del Mar | Chile          | CHL            | America/Santiago | sr:complex:33486 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:2936  | Cancha 1                | Vina del Mar | Chile          | CHL            | America/Santiago | sr:complex:33486 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:35804 | Cancha Central          | Vina del Mar | Chile          | CHL            | America/Santiago | sr:complex:33486 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:35806 | Court 5                 | Vina del Mar | Chile          | CHL            | America/Santiago | sr:complex:33486 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:35892 | Court 6                 | Santiago     | Chile          | CHL            | America/Santiago | sr:complex:62419 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:35916 | Court 7                 | Santiago     | Chile          | CHL            | America/Santiago | sr:complex:62419 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:35918 | Court 8                 | Santiago     | Chile          | CHL            | America/Santiago | sr:complex:62419 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:50607 | San Carlos De Apoquindo | Santiago     | Chile          | CHL            | America/Santiago | sr:complex:50605 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:57190 | Cancha Central          | Concepcion   | Chile          | CHL            | America/Santiago | sr:complex:57188 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:57192 | Cancha 1                | Concepcion   | Chile          | CHL            | America/Santiago | sr:complex:57188 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:57194 | Cancha 2                | Concepcion   | Chile          | CHL            | America/Santiago | sr:complex:57188 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:57598 | Cancha 11               | Santiago     | Chile          | CHL            | America/Santiago | sr:complex:62419 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:63411 | Center Court            | Coquimbo     | Chile          | CHL            | America/Santiago | sr:complex:63409 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:63413 | Court 1                 | Coquimbo     | Chile          | CHL            | America/Santiago | sr:complex:63409 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:63415 | Court 3                 | Coquimbo     | Chile          | CHL            | America/Santiago | sr:complex:63409 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:63417 | Cancha 4                | Coquimbo     | Chile          | CHL            | America/Santiago | sr:complex:63409 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:63419 | Court 2                 | Coquimbo     | Chile          | CHL            | America/Santiago | sr:complex:63409 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:66897 | Cancha Central          | Coquimbo     | Chile          | CHL            | America/Santiago | sr:complex:63409 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:66899 | Cancha 2                | Coquimbo     | Chile          | CHL            | America/Santiago | sr:complex:63409 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:66901 | Cancha 3                | Coquimbo     | Chile          | CHL            | America/Santiago | sr:complex:63409 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:67651 | Court 5                 | Colina       | Chile          | CHL            | America/Santiago | sr:complex:75070 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:67857 | Cancha Central          | Temuco       | Chile          | CHL            | America/Santiago | sr:complex:11769 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:67859 | Cancha 1                | Temuco       | Chile          | CHL            | America/Santiago | sr:complex:11769 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:67861 | Cancha 2                | Temuco       | Chile          | CHL            | America/Santiago | sr:complex:11769 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:67863 | Cancha 3                | Temuco       | Chile          | CHL            | America/Santiago | sr:complex:11769 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:70045 | Cancha Central          | Santiago     | Chile          | CHL            | America/Santiago | sr:complex:705   |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:73999 | Cancha Central          | Antofagasta  | Chile          | CHL            | America/Santiago | sr:complex:73997 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:74001 | Court 1                 | Antofagasta  | Chile          | CHL            | America/Santiago | sr:complex:73997 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:74003 | Court 2                 | Antofagasta  | Chile          | CHL            | America/Santiago | sr:complex:73997 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:74005 | Court 3                 | Antofagasta  | Chile          | CHL            | America/Santiago | sr:complex:73997 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:74980 | Centre Court            | Colina       | Chile          | CHL            | America/Santiago | sr:complex:75070 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:74982 | Court 1                 | Colina       | Chile          | CHL            | America/Santiago | sr:complex:75070 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:74984 | Court 2                 | Colina       | Chile          | CHL            | America/Santiago | sr:complex:75070 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:75120 | Grandstand              | Colina       | Chile          | CHL            | America/Santiago | sr:complex:75070 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:76925 | Court Jaime Fillol      | Santiago     | Chile          | CHL            | America/Santiago | sr:complex:50605 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+
| sr:venue:77037 | Cancha 2                | Santiago     | Chile          | CHL            | America/Santiago | sr:complex:62419 |
+----------------+-------------------------+--------------+----------------+----------------+------------------+------------------+

In [17]:
#4.Identify all venues and their timezones:

mycursor.execute(
'''SELECT venue_name, timezone
FROM Venues;'''
)

results = mycursor.fetchall()
headers = ["venue_name","timezone"]
table = tabulate(results, headers, tablefmt="grid")
print(table)

+------------------------------------------------------------+--------------------------------+
| venue_name                                                 | timezone                       |
+============================================================+================================+
| Estadio Monumental                                         | America/Lima                   |
+------------------------------------------------------------+--------------------------------+
| Stadium                                                    | Asia/Shanghai                  |
+------------------------------------------------------------+--------------------------------+
| Court 2                                                    | Asia/Shanghai                  |
+------------------------------------------------------------+--------------------------------+
| Court 7                                                    | Australia/Sydney               |
+------------------------------------------------------------+--------------------------------+
| Court 20                                                   | Australia/Melbourne            |
+------------------------------------------------------------+--------------------------------+
| Court 22                                                   | Australia/Melbourne            |
+------------------------------------------------------------+--------------------------------+
| Estadio Ivan Elias Moreno                                  | America/Lima                   |
+------------------------------------------------------------+--------------------------------+
| Stade Numa-Daly Magenta                                    | Pacific/Noumea                 |
+------------------------------------------------------------+--------------------------------+
| Noevir Stadium                                             | Asia/Tokyo                     |
+------------------------------------------------------------+--------------------------------+
| Shanghai Stadium                                           | Asia/Shanghai                  |
+------------------------------------------------------------+--------------------------------+
| Cancha 5                                                   | America/Mexico_City            |
+------------------------------------------------------------+--------------------------------+
| Court 13                                                   | America/Los_Angeles            |
+------------------------------------------------------------+--------------------------------+
| Center Court                                               | Africa/Casablanca              |
+------------------------------------------------------------+--------------------------------+
| Court 1                                                    | Africa/Casablanca              |
+------------------------------------------------------------+--------------------------------+
| Court 2                                                    | Africa/Casablanca              |
+------------------------------------------------------------+--------------------------------+
| Court 4                                                    | Africa/Casablanca              |
+------------------------------------------------------------+--------------------------------+
| SZ Court                                                   | Europe/Berlin                  |
+------------------------------------------------------------+--------------------------------+
| Court 1                                                    | Europe/Lisbon                  |
+------------------------------------------------------------+--------------------------------+
| Center Court                                               | Europe/Berlin                  |
+------------------------------------------------------------+--------------------------------+
| Show Court                                                 | Europe/Berlin                  |
+------------------------------------------------------------+--------------------------------+
| Court 1                                                    | Europe/Berlin                  |
+------------------------------------------------------------+--------------------------------+
| Court 2                                                    | Europe/Berlin                  |
+------------------------------------------------------------+--------------------------------+
| Court 9                                                    | Europe/Rome                    |
+------------------------------------------------------------+--------------------------------+
| Estadio Alejandro Villanueva                               | America/Lima                   |
+------------------------------------------------------------+--------------------------------+
| Court 11                                                   | Europe/Rome                    |
+------------------------------------------------------------+--------------------------------+
| Halle des Sports                                           | Europe/Paris                   |
+------------------------------------------------------------+--------------------------------+
| Court 4                                                    | America/New_York               |
+------------------------------------------------------------+--------------------------------+
| Arthur Ashe Stadium                                        | America/New_York               |
+------------------------------------------------------------+--------------------------------+
| Court 5                                                    | America/New_York               |
+------------------------------------------------------------+--------------------------------+
| Court 6                                                    | America/New_York               |
+------------------------------------------------------------+--------------------------------+
| Court 7                                                    | America/New_York               |
+------------------------------------------------------------+--------------------------------+
| Court 8                                                    | America/New_York               |
+------------------------------------------------------------+--------------------------------+
| Court 9                                                    | America/New_York               |
+------------------------------------------------------------+--------------------------------+
| Court 10                                                   | America/New_York               |
+------------------------------------------------------------+--------------------------------+
| Court 11                                                   | America/New_York               |
+------------------------------------------------------------+--------------------------------+
| Court 12                                                   | America/New_York               |
+------------------------------------------------------------+--------------------------------+
| Court 9                                                    | Asia/Tokyo                     |
+------------------------------------------------------------+--------------------------------+
| Court 13                                                   | America/New_York               |
+------------------------------------------------------------+--------------------------------+
| Court A                                                    | Asia/Shanghai                  |
+------------------------------------------------------------+--------------------------------+
| Court B                                                    | Asia/Shanghai                  |
+------------------------------------------------------------+--------------------------------+
| Court 14                                                   | America/New_York               |
+------------------------------------------------------------+--------------------------------+
| Court C                                                    | Asia/Shanghai                  |
+------------------------------------------------------------+--------------------------------+
| Court 15                                                   | America/New_York               |
+------------------------------------------------------------+--------------------------------+
| Cancha 10                                                  | America/Argentina/Buenos_Aires |
+------------------------------------------------------------+--------------------------------+
| Cancha 11                                                  | America/Argentina/Buenos_Aires |
+------------------------------------------------------------+--------------------------------+
| Cancha 2                                                   | America/Argentina/Buenos_Aires |
+------------------------------------------------------------+--------------------------------+
| Court 16                                                   | America/New_York               |
+------------------------------------------------------------+--------------------------------+
| Stadium 17                                                 | America/New_York               |
+------------------------------------------------------------+--------------------------------+
| Louis Armstrong Stadium                                    | America/New_York               |
+------------------------------------------------------------+--------------------------------+
| Grandstand                                                 | America/New_York               |
+------------------------------------------------------------+--------------------------------+
| Center Court                                               | Asia/Shanghai                  |
+------------------------------------------------------------+--------------------------------+
| Court 2                                                    | Europe/Paris                   |
+------------------------------------------------------------+--------------------------------+
| Court Central                                              | Europe/Paris                   |
+------------------------------------------------------------+--------------------------------+
| Court 1                                                    | Europe/Paris                   |
+------------------------------------------------------------+--------------------------------+
| CENTRALA                                                   | Europe/Bucharest               |
+------------------------------------------------------------+--------------------------------+
| SEMI CENTRALA                                              | Europe/Bucharest               |
+------------------------------------------------------------+--------------------------------+
| COURT 2                                                    | Europe/Bucharest               |
+------------------------------------------------------------+--------------------------------+
| CENTRE                                                     | Asia/Tashkent                  |
+------------------------------------------------------------+--------------------------------+
| COURT 3                                                    | Asia/Tashkent                  |
+------------------------------------------------------------+--------------------------------+
| COURT 4                                                    | Asia/Tashkent                  |
+------------------------------------------------------------+--------------------------------+
| COURT 5                                                    | Asia/Tashkent                  |
+------------------------------------------------------------+--------------------------------+
| COURT 3                                                    | Europe/Bucharest               |
+------------------------------------------------------------+--------------------------------+
| Center Court                                               | Asia/Seoul                     |
+------------------------------------------------------------+--------------------------------+
| Court 2                                                    | Asia/Seoul                     |
+------------------------------------------------------------+--------------------------------+
| Court 13                                                   | Asia/Seoul                     |
+------------------------------------------------------------+--------------------------------+
| Court 11                                                   | Asia/Seoul                     |
+------------------------------------------------------------+--------------------------------+
| Quadra Guga Kuerten                                        | Brazil/East                    |
+------------------------------------------------------------+--------------------------------+
| Quadra 2                                                   | Brazil/East                    |
+------------------------------------------------------------+--------------------------------+
| Court 1                                                    | Asia/Tokyo                     |
+------------------------------------------------------------+--------------------------------+
| Court 2                                                    | Asia/Tokyo                     |
+------------------------------------------------------------+--------------------------------+
| Center Court                                               | Asia/Tokyo                     |
+------------------------------------------------------------+--------------------------------+
| Grandstand                                                 | America/Mexico_City            |
+------------------------------------------------------------+--------------------------------+
| Centre Court                                               | Asia/Bangkok                   |
+------------------------------------------------------------+--------------------------------+
| COURT 1                                                    | Asia/Bangkok                   |
+------------------------------------------------------------+--------------------------------+
| Court 3                                                    | Asia/Tokyo                     |
+------------------------------------------------------------+--------------------------------+
| Court 4                                                    | Asia/Tokyo                     |
+------------------------------------------------------------+--------------------------------+
| Center                                                     | Asia/Shanghai                  |
+------------------------------------------------------------+--------------------------------+
| Court 1                                                    | Asia/Shanghai                  |
+------------------------------------------------------------+--------------------------------+
| Court 4                                                    | Asia/Shanghai                  |
+------------------------------------------------------------+--------------------------------+
| Court 5                                                    | Asia/Shanghai                  |
+------------------------------------------------------------+--------------------------------+
| Court 7                                                    | Asia/Shanghai                  |
+------------------------------------------------------------+--------------------------------+
| Court 8                                                    | Asia/Shanghai                  |
+------------------------------------------------------------+--------------------------------+
| Court 9                                                    | Asia/Shanghai                  |
+------------------------------------------------------------+--------------------------------+
| Court 2                                                    | Asia/Shanghai                  |
+------------------------------------------------------------+--------------------------------+
| Grandstand                                                 | Asia/Shanghai                  |
+------------------------------------------------------------+--------------------------------+
| Estadio GNP Seguros                                        | America/Mexico_City            |
+------------------------------------------------------------+--------------------------------+
| Cancha 1                                                   | America/Mexico_City            |
+------------------------------------------------------------+--------------------------------+
| Cancha 2                                                   | America/Mexico_City            |
+------------------------------------------------------------+--------------------------------+
| Court 4                                                    | Asia/Shanghai                  |
+------------------------------------------------------------+--------------------------------+
| Court 5                                                    | Asia/Shanghai                  |
+------------------------------------------------------------+--------------------------------+
| Stadium Court                                              | Asia/Shanghai                  |
+------------------------------------------------------------+--------------------------------+
| Center                                                     | Asia/Tokyo                     |
+------------------------------------------------------------+--------------------------------+
| Court 1                                                    | Asia/Tokyo                     |
+------------------------------------------------------------+--------------------------------+
| Court 2                                                    | Asia/Tokyo                     |
+------------------------------------------------------------+--------------------------------+
| Astana Arena                                               | Asia/Almaty                    |
+------------------------------------------------------------+--------------------------------+
| Cancha 1                                                   | America/Santiago               |
+------------------------------------------------------------+--------------------------------+
| Cancha 3                                                   | America/Santiago               |
+------------------------------------------------------------+--------------------------------+
| Cancha 8                                                   | America/Mexico_City            |
+------------------------------------------------------------+--------------------------------+
| Cancha Central                                             | America/Mexico_City            |
+------------------------------------------------------------+--------------------------------+
| Court 3                                                    | America/Sao_Paulo              |
+------------------------------------------------------------+--------------------------------+
| Cancha 4                                                   | America/Mexico_City            |
+------------------------------------------------------------+--------------------------------+
| Cancha 3                                                   | America/Mexico_City            |
+------------------------------------------------------------+--------------------------------+
| Center                                                     | America/New_York               |

In [18]:
#5.Find complexes that have more than one venue:

mycursor.execute(
'''SELECT c.complex_name, COUNT(v.venue_id) as num_venues
FROM Venues v
JOIN Complexes c ON v.complex_id = c.complex_id
GROUP BY c.complex_name
HAVING COUNT(v.venue_id) > 1'''
)

results = mycursor.fetchall()
headers = ["complexe_name","num_of_venues"]
table = tabulate(results, headers, tablefmt="grid")
print(table)

+------------------------------------------------------------+-----------------+
| complexe_name                                              |   num_of_venues |
+============================================================+=================+
| Kindarena                                                  |               4 |
+------------------------------------------------------------+-----------------+
| Estadio de la Cartuja                                      |               2 |
+------------------------------------------------------------+-----------------+
| Estadio German Becker                                      |               4 |
+------------------------------------------------------------+-----------------+
| Palais des sports de Gerland                               |               7 |
+------------------------------------------------------------+-----------------+
| Sibur Arena                                                |               4 |
+------------------------------------------------------------+-----------------+
| Palais Des Sport                                           |               7 |
+------------------------------------------------------------+-----------------+
| Palasport                                                  |               4 |
+------------------------------------------------------------+-----------------+
| Salle Steredenn                                            |               6 |
+------------------------------------------------------------+-----------------+
| Porsche-Arena                                              |               3 |
+------------------------------------------------------------+-----------------+
| Rotterdam Ahoy                                             |               3 |
+------------------------------------------------------------+-----------------+
| Bluesun Tennis Center                                      |               8 |
+------------------------------------------------------------+-----------------+
| Club Sonoma, Estadio Gnp Seguros                           |               3 |
+------------------------------------------------------------+-----------------+
| Accor Arena                                                |               3 |
+------------------------------------------------------------+-----------------+
| Roy Emerson Arena                                          |               4 |
+------------------------------------------------------------+-----------------+
| Complexo de Tenis do Jamor                                 |               5 |
+------------------------------------------------------------+-----------------+
| Club de Tenis Puente Romano                                |               9 |
+------------------------------------------------------------+-----------------+
| National Tennis Center                                     |              49 |
+------------------------------------------------------------+-----------------+
| Canberra Tennis Centre                                     |               7 |
+------------------------------------------------------------+-----------------+
| BT Arena                                                   |               2 |
+------------------------------------------------------------+-----------------+
| Valletta Cambiaso ASD                                      |               9 |
+------------------------------------------------------------+-----------------+
| Porsche Arena                                              |               5 |
+------------------------------------------------------------+-----------------+
| Taipei Arena                                               |              10 |
+------------------------------------------------------------+-----------------+
| Singapore Indoor Stadium                                   |               5 |
+------------------------------------------------------------+-----------------+
| Palais des Sports de Marseille                             |               3 |
+------------------------------------------------------------+-----------------+
| Caja Magica                                                |               3 |
+------------------------------------------------------------+-----------------+
| All England Lawn Tennis and Croquet Club                   |              19 |
+------------------------------------------------------------+-----------------+
| Stade Roland Garros                                        |              17 |
+------------------------------------------------------------+-----------------+
| Melbourne Park                                             |              25 |
+------------------------------------------------------------+-----------------+
| Qi zhong Forest Sports City Arena                          |               2 |
+------------------------------------------------------------+-----------------+
| Wake Forest University Tennis Complex                      |               6 |
+------------------------------------------------------------+-----------------+
| The Drive                                                  |               5 |
+------------------------------------------------------------+-----------------+
| Atlantic Station                                           |               4 |
+------------------------------------------------------------+-----------------+
| International Tennis Hall of Fame                          |               7 |
+------------------------------------------------------------+-----------------+
| Club Jacaranda Cumbaya                                     |              15 |
+------------------------------------------------------------+-----------------+
| Hengqin International Tennis Center Zhuhai                 |              14 |
+------------------------------------------------------------+-----------------+
| Buenos Aires Lawn Tennis Club                              |              29 |
+------------------------------------------------------------+-----------------+
| Delray Beach Tennis Center                                 |               7 |
+------------------------------------------------------------+-----------------+
| CK Sportcenter Kockelscheuer                               |               5 |
+------------------------------------------------------------+-----------------+
| Luzhniki Olympic Complex                                   |               2 |
+------------------------------------------------------------+-----------------+
| Ariake Colosseum                                           |               4 |
+------------------------------------------------------------+-----------------+
| Optics Valley International Tennis Center                  |              13 |
+------------------------------------------------------------+-----------------+
| Guangzhou Tianhe Sports Center                             |               8 |
+------------------------------------------------------------+-----------------+
| Olympic Park Tennis Center                                 |              12 |
+------------------------------------------------------------+-----------------+
| Victoria Park Tennis Court                                 |              16 |
+------------------------------------------------------------+-----------------+
| Tianjin Tuanbo International Tennis Center                 |              10 |
+------------------------------------------------------------+-----------------+
| Tashkent Tennis Centreake                                  |               2 |
+------------------------------------------------------------+-----------------+
| Utsubo Tennis Center                                       |               7 |
+------------------------------------------------------------+-----------------+
| Connecticut Tennis Center                                  |              11 |
+------------------------------------------------------------+-----------------+
| Sobeys Stadium                                             |              14 |
+------------------------------------------------------------+-----------------+
| Lindner Family Tennis Center                               |              15 |
+------------------------------------------------------------+-----------------+
| Tennis Club de Strasbourg                                  |              11 |
+------------------------------------------------------------+-----------------+
| Edgbaston Priory Club                                      |               8 |
+------------------------------------------------------------+-----------------+
| Royal Tennis Club de Marrakech                             |               6 |
+------------------------------------------------------------+-----------------+
| Tennis Club 1.FCN                                          |               7 |
+------------------------------------------------------------+-----------------+
| Devonshire Park International Tennis Centre                |              12 |
+------------------------------------------------------------+-----------------+
| Tennis Club Sparta Praha                                   |              16 |
+------------------------------------------------------------+-----------------+
| Khalifa International Tennis & Squash Complex              |              12 |
+------------------------------------------------------------+-----------------+
| Club Sonoma                                                |              11 |
+------------------------------------------------------------+-----------------+
| Jockey Club Brasileiro                                     |              17 |
+------------------------------------------------------------+-----------------+
| Acapulco Princess Mundo Imperial                           |               4 |
+------------------------------------------------------------+-----------------+
| Family Circle Tennis Center                                |               6 |
+------------------------------------------------------------+-----------------+
| St. Jakobshalle Basel                                      |              11 |
+------------------------------------------------------------+-----------------+
| Wien, Wiener Stadthalle                                    |               2 |
+------------------------------------------------------------+-----------------+
| Shenzhen Longgang Sports Center                            |               2 |
+------------------------------------------------------------+-----------------+
| Queensland Tennis Centre                                   |              20 |
+------------------------------------------------------------+-----------------+
| Am Rothenbaum                                              |              12 |
+------------------------------------------------------------+-----------------+
| Kungliga Tennishallen                                      |               5 |
+------------------------------------------------------------+-----------------+
| Kitzbuehel Tennis Club Sportfeld 2                         |               8 |
+------------------------------------------------------------+-----------------+
| Nottingham Tennis Centre                                   |              18 |
+------------------------------------------------------------+-----------------+
| Bastad Tennis Stadium                                      |               6 |
+------------------------------------------------------------+-----------------+
| Tennis Club de Geneve                                      |               5 |
+------------------------------------------------------------+-----------------+
| Autotron Rosmalen                                          |               7 |
+------------------------------------------------------------+-----------------+
| BNR arena                                                  |              10 |
+------------------------------------------------------------+-----------------+
| MTTC Iphitos e.V.                                          |               9 |
+------------------------------------------------------------+-----------------+
| Real Club de Tenis Barcelona                               |              11 |
+------------------------------------------------------------+-----------------+
| Hiroshima Regional Park                                    |              10 |
+------------------------------------------------------------+-----------------+
| Lyon Tennis Club                                           |               4 |
+------------------------------------------------------------+-----------------+
| Sichuan International Tennis Center                        |               9 |
+------------------------------------------------------------+-----------------+
| Shenzhen Luohu Tennis Centre                               |               6 |
+------------------------------------------------------------+-----------------+
| Country Club Santa Ponsa                                   |              13 |
+------------------------------------------------------------+-----------------+
| Tennis Center Novak                                        |              10 |
+------------------------------------------------------------+-----------------+
| Madrid Arena                                               |              14 |
+------------------------------------------------------------+-----------------+
| Rama Gardens Hotel                                         |               6 |
+------------------------------------------------------------+-----------------+
| Country Time Club                                          |               9 |
+------------------------------------------------------------+-----------------+
| ŠRC MARINA PORTOROŽ                                        |               6 |
+------------------------------------------------------------+-----------------+
| I. Czech Lawn Tennis Club Praha                            |               4 |
+------------------------------------------------------------+-----------------+
| LTTC Rot-Weiss                                             |               3 |
+------------------------------------------------------------+-----------------+
| Romai Tennis Academy                                       |               4 |
+------------------------------------------------------------+-----------------+
| Sporting Club de Tenis Valencia                            |              13 |
+------------------------------------------------------------+-----------------+
| Club Naval de Campo las Salinas                            |               4 |
+------------------------------------------------------------+-----------------+
| USTA Billie Jean King National Tennis Center               |              17 |
+------------------------------------------------------------+-----------------+
| Lanxess Arena                                              |               2 |
+------------------------------------------------------------+-----------------+
| Tiburon Peninsula Club                                     |               9 |
+------------------------------------------------------------+-----------------+
| Country Club de Bogota                                     |               3 |
+------------------------------------------------------------+-----------------+
| Almaty Tennis Center                                       |               7 |
+------------------------------------------------------------+-----------------+
| Sociedade Hipica de Campinas                               |              11 |
+------------------------------------------------------------+-----------------+
| Eve Zimmermann Tennis Center                               |               8 |
+------------------------------------------------------------+-----------------+
| Santo Domingo Tennis Club La Bocha                         |              18 |
+------------------------------------------------------------+-----------------+
| Lotto Arena                                                |               4 |
+------------------------------------------------------------+-----------------+
| TC Ismaning                                                |               2 |
+------------------------------------------------------------+-----------------+
| Osten & Victor Alberta Tennis Centre                       |               9 |
+------------------------------------------------------------+-----------------+
| Ningbo Tennis Center of WTA Ningbo, China w42              |              12 |
+------------------------------------------------------------+-----------------+
| Club Tennis Las Terrazas de Miraflores                     |              22 |
+------------------------------------------------------------+-----------------+
| Liuzhou Tennis Center                                      |               7 |
+------------------------------------------------------------+-----------------+
| The Boar's Head Sports Club                                |               8 |
+------------------------------------------------------------+-----------------+
| Anexo Guayaquil Tenis Club                                 |               6 |
+------------------------------------------------------------+-----------------+
| Vendéspace                                                 |               2 |
+------------------------------------------------------------+-----------------+
| Carrasco Lawn Tennis Club                                  |               4 |
+------------------------------------------------------------+-----------------+
| Goodfriend Indoor Tennis Center                            |               6 |
+------------------------------------------------------------+-----------------+
| Palais des sports de Beaublanc                             |               3 |
+------------------------------------------------------------+-----------------+
| Miki Disaster Management Park                              |               9 |
+------------------------------------------------------------+-----------------+
| Karnataka State Lawn Tennis Association                    |               7 |
+------------------------------------------------------------+-----------------+
| Racket Club, Argentina                                     |               2 |
+------------------------------------------------------------+-----------------+
| Atkins Tennis Center                                       |               9 |
+------------------------------------------------------------+-----------------+
| Rice Stadium (Brian Patterson Sports Performance Center)   |               7 |
+------------------------------------------------------------+-----------------+
| Mhalunge Balewadi Tennis Complex                           |               7 |
+------------------------------------------------------------+-----------------+
| ASB Tennis Arena                                           |              14 |
+------------------------------------------------------------+-----------------+
| Domain Tennis Centre                                       |               3 |
+------------------------------------------------------------+-----------------+
| Ohio State Varsity Tennis Center                           |               7 |
+------------------------------------------------------------+-----------------+
| EPG Arena                                                  |               2 |
+------------------------------------------------------------+-----------------+
| Newport Beach Tennis Club                                  |               6 |
+------------------------------------------------------------+-----------------+
| Burnie Tennis Club                                         |               9 |

In [19]:
#6.List venues grouped by country:

mycursor.execute(
'''SELECT country_name, COUNT(venue_id) as num_venues
FROM Venues
GROUP BY country_name;'''
)

results = mycursor.fetchall()
headers = ["country_name","num_of_venues"]
table = tabulate(results, headers, tablefmt="grid")
print(table)

+----------------------+-----------------+
| country_name         |   num_of_venues |
+======================+=================+
| Peru                 |              37 |
+----------------------+-----------------+
| China                |             207 |
+----------------------+-----------------+
| Australia            |             100 |
+----------------------+-----------------+
| New Caledonia        |               6 |
+----------------------+-----------------+
| Japan                |              85 |
+----------------------+-----------------+
| Mexico               |             116 |
+----------------------+-----------------+
| USA                  |             441 |
+----------------------+-----------------+
| Morocco              |              10 |
+----------------------+-----------------+
| Germany              |             128 |
+----------------------+-----------------+
| Portugal             |              65 |
+----------------------+-----------------+
| Italy                |             236 |
+----------------------+-----------------+
| France               |             234 |
+----------------------+-----------------+
| Argentina            |              75 |
+----------------------+-----------------+
| Romania              |              37 |
+----------------------+-----------------+
| Uzbekistan           |              21 |
+----------------------+-----------------+
| Republic of Korea    |              34 |
+----------------------+-----------------+
| Brazil               |              95 |
+----------------------+-----------------+
| Thailand             |              19 |
+----------------------+-----------------+
| Kazakhstan           |              37 |
+----------------------+-----------------+
| Chile                |              57 |
+----------------------+-----------------+
| Austria              |              39 |
+----------------------+-----------------+
| Sweden               |              15 |
+----------------------+-----------------+
| Russia               |              22 |
+----------------------+-----------------+
| Tunisia              |              21 |
+----------------------+-----------------+
| Chinese Taipei       |              22 |
+----------------------+-----------------+
| Czechia              |              57 |
+----------------------+-----------------+
| Luxembourg           |               5 |
+----------------------+-----------------+
| England              |             110 |
+----------------------+-----------------+
| Slovenia             |              11 |
+----------------------+-----------------+
| Turkiye              |              52 |
+----------------------+-----------------+
| Canada               |              63 |
+----------------------+-----------------+
| Croatia              |              53 |
+----------------------+-----------------+
| Finland              |              13 |
+----------------------+-----------------+
| Spain                |             195 |
+----------------------+-----------------+
| San Marino           |               3 |
+----------------------+-----------------+
| Hong Kong, China     |              19 |
+----------------------+-----------------+
| Bosnia & Herzegovina |               9 |
+----------------------+-----------------+
| Poland               |              37 |
+----------------------+-----------------+
| Ecuador              |              54 |
+----------------------+-----------------+
| Qatar                |              12 |
+----------------------+-----------------+
| Switzerland          |              49 |
+----------------------+-----------------+
| India                |              22 |
+----------------------+-----------------+
| Singapore            |               6 |
+----------------------+-----------------+
| Slovakia             |              15 |
+----------------------+-----------------+
| Uruguay              |               9 |
+----------------------+-----------------+
| New Zealand          |              14 |
+----------------------+-----------------+
| United Arab Emirates |              13 |
+----------------------+-----------------+
| Belgium              |               6 |
+----------------------+-----------------+
| Dominican Republic   |              18 |
+----------------------+-----------------+
| Netherlands          |              17 |
+----------------------+-----------------+
| Colombia             |              44 |
+----------------------+-----------------+
| Monaco               |               9 |
+----------------------+-----------------+
| Serbia               |              18 |
+----------------------+-----------------+
| Bulgaria             |              16 |
+----------------------+-----------------+
| Hungary              |              17 |
+----------------------+-----------------+
| Ukraine              |               8 |
+----------------------+-----------------+
| Bolivia              |              18 |
+----------------------+-----------------+
| Bahrain              |               8 |
+----------------------+-----------------+
| Israel               |               2 |
+----------------------+-----------------+
| Lithuania            |              12 |
+----------------------+-----------------+
| South Africa         |               3 |
+----------------------+-----------------+
| Georgia              |               4 |
+----------------------+-----------------+
| Paraguay             |               3 |
+----------------------+-----------------+
| Egypt                |              10 |
+----------------------+-----------------+

In [8]:
#7.Find all venues for a specific complex (e.g., Nacional):

mycursor.execute(
'''SELECT venue_id, venue_name
FROM Venues 
JOIN Complexes ON venues.complex_id = complexes.complex_id
WHERE complexes.complex_name = 'Porsche-Arena';'''
)

results = mycursor.fetchall()
headers = ["venue_id","complexe_name"]
table = tabulate(results, headers, tablefmt="grid")
print(table)

+----------------+-----------------+
| venue_id       | complexe_name   |
+================+=================+
| sr:venue:1765  | Centre Court    |
+----------------+-----------------+
| sr:venue:77411 | Court 1         |
+----------------+-----------------+
| sr:venue:77413 | Court 2         |
+----------------+-----------------+

COMPETITOR RANKINGS QUERIES

In [4]:
from tabulate import tabulate

In [25]:
#1.Get all competitors with their rank and points:

mycursor.execute(
'''SELECT c.competitor_id, c.name, r.ranks, r.points
FROM Competitors c
JOIN Competitor_Rankings r ON c.competitor_id = r.competitor_id;'''
)

results = mycursor.fetchall()
headers = ["competitor_id","competitor_name","ranks","points"]
table = tabulate(results, headers, tablefmt="grid")
print(table)

+-----------------------+--------------------------------------+---------+----------+
| competitor_id         | competitor_name                      |   ranks |   points |
+=======================+======================================+=========+==========+
| sr:competitor:49363   | Pavic, Mate                          |       1 |     7350 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:51836   | Arevalo-Gonzalez, Marcelo            |       1 |     7350 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:87690   | Thompson, Jordan                     |       3 |     6565 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:15568   | Granollers, Marcel                   |       4 |     6350 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:16160   | Zeballos, Horacio                    |       4 |     6350 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:15310   | Bolelli, Simone                      |       6 |     5990 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:95801   | Vavassori, Andrea                    |       7 |     5990 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:16608   | Mektic, Nikola                       |       8 |     5930 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:36593   | Krawietz, Kevin                      |       9 |     5880 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:52293   | Putz, Tim                            |      10 |     5790 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:50954   | Koolhof, Wesley                      |      11 |     5680 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:124658  | Purcell, Max                         |      12 |     5640 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:637970  | Patten, Henry                        |      13 |     5165 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:14898   | Heliovaara, Harri                    |      14 |     5145 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:16409   | Ebden, Matthew                       |      15 |     5105 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:15307   | Bopanna, Rohan                       |      16 |     5000 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:16151   | Venus, Michael                       |      17 |     4025 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:53785   | Skupski, Neal                        |      18 |     3670 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:38181   | Molteni, Andres                      |      19 |     3330 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:55989   | Withrow, Jackson                     |      20 |     3320 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:210736  | Lammons, Nathaniel                   |      20 |     3320 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:15548   | Gonzalez, Maximo                     |      22 |     3150 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:59131   | Glasspool, Lloyd                     |      23 |     2940 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:52202   | Nys, Hugo                            |      24 |     2870 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:112805  | Zielinski, Jan                       |      25 |     2780 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:16275   | Dodig, Ivan                          |      26 |     2760 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:47834   | Murray, Jamie                        |      27 |     2710 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:106349  | Reboul, Fabien                       |      28 |     2695 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:14553   | Ram, Rajeev                          |      29 |     2595 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:59324   | Pavlasek, Adam                       |      30 |     2595 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:108099  | Cash, Julian                         |      31 |     2515 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:206889  | Galloway, Robert                     |      32 |     2450 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:56629   | Peers, John                          |      33 |     2445 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:104917  | Vliegen, Joran                       |      34 |     2440 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:76263   | Matos, Rafael                        |      35 |     2412 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:106559  | Doumbia, Sadio                       |      36 |     2335 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:81059   | Gille, Sander                        |      37 |     2305 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:16124   | Melo, Marcelo                        |      38 |     2295 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:14835   | Roger-Vasselin, Edouard              |      39 |     2280 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:74173   | Salisbury, Joe                       |      40 |     2220 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:114831  | Erler, Alexander                     |      41 |     2152 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:45105   | Behar, Ariel                         |      42 |     2111 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:25189   | Krajicek, Austin                     |      43 |     2070 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:47966   | Olivetti, Albano                     |      44 |     2030 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:15305   | Gonzalez, Santiago                   |      45 |     1980 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:78793   | Miedler, Lucas                       |      46 |     1948 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:22967   | Bhambri, Yuki                        |      47 |     1895 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:48646   | Barrientos, Nicolas                  |      48 |     1860 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:300540  | Machac, Tomas                        |      49 |     1825 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:75813   | Zhang, Zhizhen                       |      50 |     1780 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:15588   | Rojer, Jean-Julien                   |      51 |     1770 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:66864   | Arends, Sander                       |      52 |     1760 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:62410   | Johnson, Luke                        |      53 |     1738 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:69362   | Mansouri, Skander                    |      54 |     1645 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:230186  | Verbeek, Sem                         |      55 |     1600 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:47295   | Andreozzi, Guido                     |      56 |     1600 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:108755  | Jebens, Hendrik                      |      57 |     1586 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:231188  | Frantzen, Constantin                 |      57 |     1586 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:49306   | Reyes-Varela, Miguel                 |      59 |     1467 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:25457   | Nedovyesov, Aleksandr                |      60 |     1401 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:104421  | Mies, Andreas                        |      61 |     1360 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:16198   | Escobar, Gonzalo                     |      62 |     1355 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:231090  | Arribage, Theo                       |      63 |     1355 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:81763   | Jacq, Gregoire                       |      64 |     1325 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:52244   | Balaji, N. Sriram                    |      65 |     1316 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:111195  | Luz, Orlando                         |      66 |     1285 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:203681  | Korda, Sebastian                     |      67 |     1270 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:70348   | Goransson, Andre                     |      68 |     1265 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:17038   | Smith, John-Patrick                  |      69 |     1250 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:121182  | Guinard, Manuel                      |      70 |     1226 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:16042   | Haase, Robin                         |      71 |     1206 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:918463  | Bollipalli, Rithvik Choudary         |      72 |     1182 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:204781  | Nouza, Petr                          |      73 |     1182 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:152900  | Rikl, Patrik                         |      74 |     1175 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:52065   | Harrison, Christian                  |      75 |     1161 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:127646  | Cabral, Francisco                    |      76 |     1149 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:41475   | Arneodo, Romain                      |      77 |     1140 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:287215  | Seggerman, Ryan                      |      78 |     1140 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:23899   | King, Evan                           |      79 |     1118 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:112969  | Schnaitter, Jakob                    |      80 |     1073 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:936355  | Wallner, Mark                        |      80 |     1073 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:16043   | Middelkoop, Matwe                    |      82 |     1070 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:223868  | Matuszewski, Piotr                   |      83 |     1069 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:76361   | Kadhe, Arjun                         |      84 |     1067 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:47975   | Hanfmann, Yannick                    |      85 |     1015 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:63438   | McDonald, Mackenzie                  |      86 |     1005 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:129368  | Koepfer, Dominik                     |      87 |      990 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:52263   | Hidalgo, Diego                       |      88 |      961 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:57163   | Zverev, Alexander                    |      89 |      960 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:1020797 | Trhac, Patrik                        |      90 |      958 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:77653   | Cornea, Victor                       |      91 |      948 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:299130  | Hijikata, Rinky                      |      92 |      937 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:73572   | Zormann, Marcelo                     |      93 |      922 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:871495  | Michelsen, Alex                      |      94 |      915 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:16992   | Willis, Marcus                       |      95 |      907 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:98413   | Drzewiecki, Karol                    |      96 |      890 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:147104  | Romios, Matthew Christopher          |      97 |      887 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:60920   | Nedunchezhiyan, Jeevan               |      98 |      883 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:16492   | Eysseric, Jonathan                   |      99 |      882 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:16823   | Romboli, Fernando                    |     100 |      880 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:16854   | Molchanov, Denys                     |     101 |      871 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:808628  | Shelton, Ben                         |     102 |      855 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:113221  | Niklas-Salminen, Patrik              |     103 |      834 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:121032  | Stalder, Reese                       |     104 |      816 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:197678  | Tsitsipas, Petros                    |     105 |      811 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:53759   | Prashanth, N. Vijay Sundar           |     106 |      770 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:50037   | Bortolotti, Marco                    |     107 |      762 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:77011   | Martos Gornes, Sergio                |     108 |      762 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:102151  | Tabilo, Alejandro                    |     109 |      760 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:47760   | Weissborn, Tristan-Samuel            |     110 |      760 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:119150  | Fancutt, Thomas                      |     111 |      756 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:145936  | Kaliyanda Poonacha, Niki             |     112 |      740 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:35766   | Begemann, Andre                      |     113 |      732 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:14508   | Mahut, Nicolas                       |     114 |      730 |
+-----------------------+--------------------------------------+---------+----------+
| sr:competitor:234124  | Stevens, Bart                        |     115 |      724 |

In [28]:
#2.Find competitors ranked in the top 5:

mycursor.execute(
'''SELECT c.competitor_id, c.name, r.ranks, r.points
FROM Competitors c
JOIN Competitor_Rankings r ON c.competitor_id = r.competitor_id
WHERE r.ranks <= 5
ORDER BY r.ranks;'''
)

results = mycursor.fetchall()
headers = ["competitor_id","competitor_name","ranks","points"]
table = tabulate(results, headers, tablefmt="grid")
print(table)

+---------------------+---------------------------+---------+----------+
| competitor_id       | competitor_name           |   ranks |   points |
+=====================+===========================+=========+==========+
| sr:competitor:49363 | Pavic, Mate               |       1 |     7350 |
+---------------------+---------------------------+---------+----------+
| sr:competitor:51836 | Arevalo-Gonzalez, Marcelo |       1 |     7350 |
+---------------------+---------------------------+---------+----------+
| sr:competitor:72376 | Siniakova, Katerina       |       1 |     9530 |
+---------------------+---------------------------+---------+----------+
| sr:competitor:74949 | Routliffe, Erin           |       2 |     8165 |
+---------------------+---------------------------+---------+----------+
| sr:competitor:87690 | Thompson, Jordan          |       3 |     6565 |
+---------------------+---------------------------+---------+----------+
| sr:competitor:43860 | Dabrowski, Gabriela       |       3 |     6805 |
+---------------------+---------------------------+---------+----------+
| sr:competitor:15568 | Granollers, Marcel        |       4 |     6350 |
+---------------------+---------------------------+---------+----------+
| sr:competitor:16160 | Zeballos, Horacio         |       4 |     6350 |
+---------------------+---------------------------+---------+----------+
| sr:competitor:41520 | Kichenok, Lyudmyla        |       4 |     5785 |
+---------------------+---------------------------+---------+----------+
| sr:competitor:51387 | Townsend, Taylor          |       5 |     5618 |
+---------------------+---------------------------+---------+----------+

In [30]:
#3.List competitors with no rank movement (stable rank):

mycursor.execute(
'''SELECT c.competitor_id, c.name, r.ranks, r.movement
FROM Competitors c
JOIN Competitor_Rankings r ON c.competitor_id = r.competitor_id
WHERE r.movement = 0;'''
)

results = mycursor.fetchall()
headers = ["competitor_id","competitor_name","ranks","movements"]
table = tabulate(results, headers, tablefmt="grid")
print(table)

+-----------------------+--------------------------------------+---------+-------------+
| competitor_id         | competitor_name                      |   ranks |   movements |
+=======================+======================================+=========+=============+
| sr:competitor:49363   | Pavic, Mate                          |       1 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:51836   | Arevalo-Gonzalez, Marcelo            |       1 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:87690   | Thompson, Jordan                     |       3 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:15568   | Granollers, Marcel                   |       4 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:16160   | Zeballos, Horacio                    |       4 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:124658  | Purcell, Max                         |      12 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:16151   | Venus, Michael                       |      17 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:53785   | Skupski, Neal                        |      18 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:15548   | Gonzalez, Maximo                     |      22 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:59131   | Glasspool, Lloyd                     |      23 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:52202   | Nys, Hugo                            |      24 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:112805  | Zielinski, Jan                       |      25 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:16275   | Dodig, Ivan                          |      26 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:47834   | Murray, Jamie                        |      27 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:59324   | Pavlasek, Adam                       |      30 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:108099  | Cash, Julian                         |      31 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:81059   | Gille, Sander                        |      37 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:114831  | Erler, Alexander                     |      41 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:47966   | Olivetti, Albano                     |      44 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:15305   | Gonzalez, Santiago                   |      45 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:78793   | Miedler, Lucas                       |      46 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:300540  | Machac, Tomas                        |      49 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:75813   | Zhang, Zhizhen                       |      50 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:15588   | Rojer, Jean-Julien                   |      51 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:66864   | Arends, Sander                       |      52 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:62410   | Johnson, Luke                        |      53 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:69362   | Mansouri, Skander                    |      54 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:49306   | Reyes-Varela, Miguel                 |      59 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:25457   | Nedovyesov, Aleksandr                |      60 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:52244   | Balaji, N. Sriram                    |      65 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:16042   | Haase, Robin                         |      71 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:918463  | Bollipalli, Rithvik Choudary         |      72 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:127646  | Cabral, Francisco                    |      76 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:47975   | Hanfmann, Yannick                    |      85 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:63438   | McDonald, Mackenzie                  |      86 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:129368  | Koepfer, Dominik                     |      87 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:52263   | Hidalgo, Diego                       |      88 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:57163   | Zverev, Alexander                    |      89 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:1020797 | Trhac, Patrik                        |      90 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:16492   | Eysseric, Jonathan                   |      99 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:16823   | Romboli, Fernando                    |     100 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:16854   | Molchanov, Denys                     |     101 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:808628  | Shelton, Ben                         |     102 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:113221  | Niklas-Salminen, Patrik              |     103 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:50037   | Bortolotti, Marco                    |     107 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:119150  | Fancutt, Thomas                      |     111 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:35766   | Begemann, Andre                      |     113 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:14508   | Mahut, Nicolas                       |     114 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:234124  | Stevens, Bart                        |     115 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:209202  | Chandrasekar, Anirudh                |     116 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:163480  | Bublik, Alexander                    |     117 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:305776  | Soto, Matias                         |     118 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:234044  | Kirkov, Vasil                        |     127 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:263917  | Draxl, Liam                          |     133 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:146040  | Gomez, Federico Agustin              |     134 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:55745   | Negritu, Christoph                   |     174 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:284805  | Nava, Emilio                         |     217 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:534043  | Darderi, Luciano                     |     218 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:99377   | Kestelboim, Mariano                  |     219 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:82133   | Dellien, Murkel                      |     220 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:48225   | Dutra Da Silva, Daniel               |     224 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:132834  | Barrios Vera, Marcelo Tomas          |     225 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:289021  | Charlton, Joshua                     |     226 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:79223   | Delaney, Jake                        |     248 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:99587   | Chung, Yun Seong                     |     249 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:352776  | Draper, Jack                         |     250 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:399637  | Cobolli, Flavio                      |     251 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:125006  | Borges, Nuno                         |     252 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:255595  | Cerundolo, Francisco                 |     253 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:156664  | TE, Rigele                           |     265 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:450283  | Mpetshi Perricard, Giovanni          |     266 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:169492  | Aboian, Leonardo                     |     267 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:196672  | Davis, James                         |     268 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:154740  | Delaney, Jesse                       |     272 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:217192  | Ouakaa, Aziz                         |     277 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:38180   | Mena, Facundo                        |     294 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:121248  | Roveri Sidney, Gabriel               |     295 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:57703   | Pouille, Lucas                       |     296 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:15931   | Brown, Dustin                        |     297 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:51141   | Carballes Baena, Roberto             |     298 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:645442  | Genov, Anthony                       |     302 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:103625  | Geerts, Michael                      |     303 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:458575  | Agostini, Simone                     |     322 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:614090  | Pieczonka, Filip                     |     324 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:130442  | Rai, Ajeet                           |     325 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:124934  | Lomakin, Grigoriy                    |     326 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:17046   | Statham, Rubin                       |     327 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:418163  | Perfetti, Noah                       |     432 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:210502  | Kopp, Sandro                         |     433 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:96239   | Durasovic, Viktor                    |     434 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:210592  | Ribeiro, Eduardo                     |     435 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:54975   | Casanova, Hernan                     |     436 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:177686  | Barranco Cosano, Javier              |     437 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:186629  | Kirkin, Ergi                         |     438 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:60592   | Lee, Jeamoon                         |     447 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:111837  | Harris, Billy                        |     448 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:152898  | Gengel, Marek                        |     449 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:373348  | Pucinelli de Almeida, Matheus        |     450 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:114885  | Nikles, Johan                        |     451 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:252233  | Tang, Sheng                          |     452 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:137890  | Vale, Duarte                         |     453 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:570833  | Rodriguez Rodriguez, Johan Alexander |     464 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:501410  | Hignett, Liam                        |     465 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:246745  | Tajima, Naoki                        |     466 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:759758  | Sakellaridis, Dimitris               |     467 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:56361   | Sels, Jelle                          |     468 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:130438  | Ponwith, Nathan                      |     469 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:57327   | Domingues, Joao                      |     470 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:100317  | Turker, Mert Naci                    |     471 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:404753  | Saritas, Gokberk                     |     472 |           0 |
+-----------------------+--------------------------------------+---------+-------------+
| sr:competitor:217038  | Seeman, Johannes                     |     477 |           0 |

In [35]:
#4.Get the total points of competitors from a specific country (e.g., Croatia):

mycursor.execute(
'''SELECT c.country, SUM(r.points) as total_points
FROM Competitors c
JOIN Competitor_Rankings r ON c.competitor_id = r.competitor_id
WHERE c.country = 'Croatia';'''
)

results = mycursor.fetchall()
headers = ["country","total_points"]
table = tabulate(results, headers, tablefmt="grid")
print(table)

+-----------+----------------+
| country   |   total_points |
+===========+================+
| Croatia   |          16901 |
+-----------+----------------+

In [38]:
#5.Count the number of competitors per country:

mycursor.execute(
'''SELECT c.country, COUNT(c.competitor_id) as num_competitors
FROM Competitors c
GROUP BY c.country;'''
)

results = mycursor.fetchall()
headers = ["country","num_of_competitors"]
table = tabulate(results, headers, tablefmt="grid")
print(table)

+--------------------------+----------------------+
| country                  |   num_of_competitors |
+==========================+======================+
| Ukraine                  |                   19 |
+--------------------------+----------------------+
| Turkiye                  |                    4 |
+--------------------------+----------------------+
| China                    |                   34 |
+--------------------------+----------------------+
| USA                      |                   92 |
+--------------------------+----------------------+
| Poland                   |                   15 |
+--------------------------+----------------------+
| Chile                    |                    5 |
+--------------------------+----------------------+
| Netherlands              |                   33 |
+--------------------------+----------------------+
| Cyprus                   |                    1 |
+--------------------------+----------------------+
| Belgium                  |                   12 |
+--------------------------+----------------------+
| Romania                  |                   20 |
+--------------------------+----------------------+
| Germany                  |                   32 |
+--------------------------+----------------------+
| Italy                    |                   42 |
+--------------------------+----------------------+
| Australia                |                   54 |
+--------------------------+----------------------+
| Czechia                  |                   40 |
+--------------------------+----------------------+
| France                   |                   57 |
+--------------------------+----------------------+
| Switzerland              |                   22 |
+--------------------------+----------------------+
| Great Britain            |                   52 |
+--------------------------+----------------------+
| Lebanon                  |                    2 |
+--------------------------+----------------------+
| Slovenia                 |                    5 |
+--------------------------+----------------------+
| Austria                  |                   11 |
+--------------------------+----------------------+
| Egypt                    |                    2 |
+--------------------------+----------------------+
| Mexico                   |                    9 |
+--------------------------+----------------------+
| Brazil                   |                   24 |
+--------------------------+----------------------+
| Denmark                  |                    4 |
+--------------------------+----------------------+
| Spain                    |                   26 |
+--------------------------+----------------------+
| Finland                  |                    5 |
+--------------------------+----------------------+
| Georgia                  |                    5 |
+--------------------------+----------------------+
| Norway                   |                    4 |
+--------------------------+----------------------+
| Argentina                |                   29 |
+--------------------------+----------------------+
| Algeria                  |                    1 |
+--------------------------+----------------------+
| Serbia                   |                    9 |
+--------------------------+----------------------+
| Philippines              |                    2 |
+--------------------------+----------------------+
| Dominican Republic       |                    1 |
+--------------------------+----------------------+
| Sweden                   |                    7 |
+--------------------------+----------------------+
| Greece                   |                   10 |
+--------------------------+----------------------+
| Israel                   |                    3 |
+--------------------------+----------------------+
| Kazakhstan               |                    7 |
+--------------------------+----------------------+
| Portugal                 |                   10 |
+--------------------------+----------------------+
| Slovakia                 |                   12 |
+--------------------------+----------------------+
| New Zealand              |                   10 |
+--------------------------+----------------------+
| Estonia                  |                    3 |
+--------------------------+----------------------+
| Lithuania                |                    1 |
+--------------------------+----------------------+
| Japan                    |                   51 |
+--------------------------+----------------------+
| Colombia                 |                    9 |
+--------------------------+----------------------+
| India                    |                   27 |
+--------------------------+----------------------+
| Hungary                  |                    5 |
+--------------------------+----------------------+
| Russia                   |                    1 |
+--------------------------+----------------------+
| Zimbabwe                 |                    2 |
+--------------------------+----------------------+
| Chinese Taipei           |                   13 |
+--------------------------+----------------------+
| South Africa             |                    2 |
+--------------------------+----------------------+
| Uzbekistan               |                    1 |
+--------------------------+----------------------+
| Jamaica                  |                    1 |
+--------------------------+----------------------+
| Peru                     |                    5 |
+--------------------------+----------------------+
| Ecuador                  |                    4 |
+--------------------------+----------------------+
| Croatia                  |                    7 |
+--------------------------+----------------------+
| Bulgaria                 |                    7 |
+--------------------------+----------------------+
| Canada                   |                   14 |
+--------------------------+----------------------+
| Uruguay                  |                    3 |
+--------------------------+----------------------+
| Latvia                   |                    5 |
+--------------------------+----------------------+
| Antigua and Barbuda      |                    1 |
+--------------------------+----------------------+
| Tunisia                  |                    3 |
+--------------------------+----------------------+
| Republic of Korea        |                   11 |
+--------------------------+----------------------+
| Burundi                  |                    1 |
+--------------------------+----------------------+
| Venezuela                |                    3 |
+--------------------------+----------------------+
| Hong Kong, China         |                    2 |
+--------------------------+----------------------+
| Thailand                 |                    5 |
+--------------------------+----------------------+
| Malta                    |                    1 |
+--------------------------+----------------------+
| Armenia                  |                    1 |
+--------------------------+----------------------+
| Bolivia                  |                    4 |
+--------------------------+----------------------+
| Luxembourg               |                    1 |
+--------------------------+----------------------+
| Monaco                   |                    2 |
+--------------------------+----------------------+
| Jordan                   |                    1 |
+--------------------------+----------------------+
| Indonesia                |                    2 |
+--------------------------+----------------------+
| El Salvador              |                    1 |
+--------------------------+----------------------+
| Bosnia & Herzegovina     |                    1 |
+--------------------------+----------------------+
| Ireland                  |                    1 |
+--------------------------+----------------------+
| Morocco                  |                    1 |
+--------------------------+----------------------+
| Northern Mariana Islands |                    1 |
+--------------------------+----------------------+

In [40]:
#6.Find competitors with the highest points in the current week:

mycursor.execute(
'''SELECT c.competitor_id, c.name, r.ranks, r.points
FROM Competitors c
JOIN Competitor_Rankings r ON c.competitor_id = r.competitor_id
ORDER BY r.points DESC
LIMIT 1;
'''
)

results = mycursor.fetchall()
headers = ["competitior_id","competitor_name","rank","highest_point"]
table = tabulate(results, headers, tablefmt="grid")
print(table)

+---------------------+---------------------+--------+-----------------+
| competitior_id      | competitor_name     |   rank |   highest_point |
+=====================+=====================+========+=================+
| sr:competitor:72376 | Siniakova, Katerina |      1 |            9530 |
+---------------------+---------------------+--------+-----------------+